### ISSUE TITLE
Testcase Debuging Error

### ISSUE THREAD

**Issue by AndreasRusjaev** [nokia/RED#101]
Hi red developers,
When I start test case with context menu, I get an error.

![gebug_error](https://cloud.githubusercontent.com/assets/18263592/24861992/185a2e44-1dfb-11e7-85ee-e96b234e80a7.jpg)

and then i get an second error

![gebug_error2](https://cloud.githubusercontent.com/assets/18263592/24862053/58eaaa56-1dfb-11e7-88ed-13892cd9d9f5.jpg)

Here is copy from console:

Command: c:\devtools\Python27\python.exe -m robot.run --listener C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py:62481 --argumentfile C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\args_62bf0aa7.arg C:\projects\workspace\test
Suite Executor: Robot Framework 3.0.2 (Python 2.7.11 on win32)
==============================================================================
Test                                                                          
==============================================================================
Test.Test-Environment :: Pr�ft, ob auf jeder zul�ssigen Ebene der Edit-Butt...
==============================================================================
Test.Test-Environment.Testsuites                                              
==============================================================================
Test.Test-Environment.Testsuites.Service Platform :: Sammlung von Testf�lle...
==============================================================================
[ ERROR ] Calling method 'start_keyword' of listener 'C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py' failed: ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py", line 459, in _receive_from_server
    return self.decoder_encoder.load()
  File "C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py", line 491, in load
    return self._json_decoder(json_string)
  File "c:\devtools\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\devtools\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[ ERROR ] Calling method 'start_keyword' of listener 'C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py' failed: error: [Errno 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
[ ERROR ] Calling method 'log_message' of listener 'C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py' failed: error: [Errno 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
[ ERROR ] Calling method 'log_message' of listener 'C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py' failed: error: [Errno 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
[ ERROR ] Calling method 'end_keyword' of listener 'C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py' failed: error: [Errno 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
[ ERROR ] Calling method 'start_keyword' of listener 'C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py' failed: error: [Errno 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
[ ERROR ] Calling method 'log_message' of listener 'C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py' failed: error: [Errno 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
[ ERROR ] Calling method 'log_message' of listener 'C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py' failed: error: [Errno 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
[ ERROR ] Calling method 'end_keyword' of listener 'C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py' failed: error: [Errno 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
Traceback (most recent call last):
  File "C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py", line 440, in _send_to_server
    self.decoder_encoder.dump(packet)
  File "C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py", line 484, in dump
    self._file_to_write.flush()
  File "c:\devtools\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] Eine bestehende Verbindung wurde softwaregesteuert

durch den Hostcomputer abgebrochen
Traceback (most recent call last):
  File "C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py", line 440, in _send_to_server
    self.decoder_encoder.dump(packet)
  File "C:\Users\.............\AppData\Local\Temp\RobotTempDir3001012146770949575\TestRunnerAgent.py", line 484, in dump
    self._file_to_write.flush()
  File "c:\devtools\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])

Here is copy of arg file
# arguments automatically generated
--pythonpath c:\devtools\Python27\lib\site-packages:c:\devtools\Python27\lib:C:\projects\workspace\Service.Plattform\test\test-environment\libraries
--suite      Test.Test-environment.Testsuites.Service Platform.Devices-content
--test       Test.Test-environment.Testsuites.Service Platform.Devices-content.check icon mapping

Can you please say, what was wrong.
Thank you in advance

**Comment by KrzysztofJozefowicz** [comment]
Hard to say from the first glance what went wrong. 
Lets start with debug run - is this local debug or remote?

**Comment by AndreasRusjaev** [comment]
I made local run.
Here is copy of my debug config
![debug_config_robot](https://cloud.githubusercontent.com/assets/18263592/24863052/932e95e8-1dff-11e7-9db8-0886c10a62e5.jpg)
![debug_config_listener](https://cloud.githubusercontent.com/assets/18263592/24863058/99269586-1dff-11e7-9a49-be6e0db124eb.jpg)
![debug_config_executor](https://cloud.githubusercontent.com/assets/18263592/24863064/9bf3466a-1dff-11e7-8f81-71837c354a81.jpg)

**Comment by AndreasRusjaev** [comment]
The same configuration in run section is running.

**Comment by michalanglart** [comment]
So far nothing looks suspicious. Could you provide .log file from .metadata directory in you workspace?

**Comment by AndreasRusjaev** [comment]
Here is copy from my .log
[eclipse.log.txt](https://github.com/nokia/RED/files/912459/eclipse.log.txt)
Thank you in advance

**Comment by KrzysztofJozefowicz** [comment]
hmm still we do not see anything unusual from log. What is interesting from eclipse.log.txt is list of eclipse messages about missing proxy (http, socks) which may be .
What we could assume connection was refused before testrun or is connection was closed while testrun. 
Do you have anything set in General->Network Connections ? Mine looks like below
![image 3](https://cloud.githubusercontent.com/assets/3999733/24902495/a3e9d73e-1eaa-11e7-99f7-74ebdf7b2177.png)

Also, could I ask you to verify if this is reproducible on clean RED product (I see from the logs that you have also PyDev installed,maybe other plugins interfere with RED somehow).
[Download RED product](https://github.com/nokia/RED/releases ) ,create clean temporary workspace and import project with tests inside. Try to run it.

**Comment by AndreasRusjaev** [comment]
I had proxy settings to cntlm local proxy. Problem was with SOCKSproxy. I had changed to Native.
New log.
[eclipse.log.txt](https://github.com/nokia/RED/files/912987/eclipse.log.txt)

I think I have the same error as in #102. 
I have new installed 0.7.6, i have made new workspace, after that, I installed pydev 0.5.6, and then i have imported project from disk.

I have installed 0.7.6 second instance without pydev.  I have made new workspace and then i have imported project from disk. I have the same error.
Log from second instance.
[eclipse2.log.txt](https://github.com/nokia/RED/files/912991/eclipse2.log.txt)

**Comment by KrzysztofJozefowicz** [comment]
Hi
I tried to reproduce your case by using Database-library (by hints from your eclipse2.log.txt), in my simple case there is no issue.
Does your error happens only in that test file or is it reproducible on broader tests, is it reproducible in previous RED versions.
Can you somehow provide example testcase which we could reproduce it on our site?

**Comment by AndreasRusjaev** [comment]
Hi,
The error is new. I had tested with 0.7.5-fix without pydev and with pydev.
All runes success. The debug listener stop by break point.
Next days i make Test suite to reproduce the error, an send to you.

**Comment by AndreasRusjaev** [comment]
With this test suite i can reproduce error:
[mytest.zip](https://github.com/nokia/RED/files/921058/mytest.zip)
console output by debug:
[console.log.txt](https://github.com/nokia/RED/files/921064/console.log.txt)
eclipse log:
[eclipse.log.txt](https://github.com/nokia/RED/files/921065/eclipse.log.txt)
Popups by debug:
![first_popup_window](https://cloud.githubusercontent.com/assets/18263592/25027465/1e3c1bd8-20ad-11e7-9bf6-43b37f392a68.jpg)
![second_popup_window](https://cloud.githubusercontent.com/assets/18263592/25027467/20fadb48-20ad-11e7-86b7-177fd9c6a975.jpg)

**Comment by KrzysztofJozefowicz** [comment]
Thank you for your effort! Indeed, it is reproducible on our site,looks like debug has some problems with init files. We will have a close look right away.

**Comment by KrzysztofJozefowicz** [comment]
Looks like having multiple init breaks Debug, we are investigating it right now.

**Comment by KrzysztofJozefowicz** [comment]
ok, seems while fixing border case in remote debug we have broken case with having multiple __init__.robot in tree folder. 
We made a fix in our repo for your case so there should be no error in next release (0.7.7)

This is one of the problems with debug when suite contains multiple files with the same name in different path as debug could not show proper file which was hit by breakpoint (you can replicate it by having multiple test.robot in folder tree, it may happen that while debugging wrong file will be opened). 
I don't know yet if we could manage also fix above in 0.7.7 but it is not as critical as your case (debug is usable but wrong content is shown).

**Comment by AndreasRusjaev** [comment]
Thank you
That work correctly.
I can fix verify.

**Comment by KrzysztofJozefowicz** [comment]
thanks for cooperation :)
