### ISSUE TITLE
RED plugin importing libraries

### ISSUE THREAD

**Issue by lfteixeiraVB** [nokia/RED#109]
Now I'm able to develop my libs and import them to my robot test.
I take an old project that I intend to create tests using RF but seems that I'm not able to import the libraries.

The library appears with a message (non-accessible) (see the attach)
There is any reason that explains this?

![capture](https://cloud.githubusercontent.com/assets/22346035/26127872/01a5e448-3a8b-11e7-8f42-af15549eadc2.PNG)

**Comment by KrzysztofJozefowicz** [comment]
Hi
I am assuming you are using latest RED 0.7.7.
Please check if "Build Automatically" from top menu Project is selected, alternatively you can right click on red entry and choose "Reload" action.

If this is the case,reason is that RED to discover keywords from external libs needs to execute command to ask Robot to provide list of keywords from particular library ( generic info [libdoc](http://robot-framework.readthedocs.io/en/3.0.2/_modules/robot/libdoc.htmll), for python: `pyton -m robot.libdoc <libname> <options>`, for jython include jar in class path first, `jython -m robot.libdoc <ClassName> <options>`).
In case of Build Automatically turn off, RED does not execute this command as this may be preference when generating libdoc for changed library takes too long and should be done on demand (against on-change as default).

**Comment by lfteixeiraVB** [comment]
Hi
I try your answer and some classes actually are available now.
But there is some that still with the same problem.
Do you have another idea of what can be the cause?
Cheers!

**Comment by KrzysztofJozefowicz** [comment]
can you give me any examples? Screenshots or example source code for jython libs.

**Comment by lfteixeiraVB** [comment]
Can you provide me your e-mail? I can send some examples and screenshots

**Comment by KrzysztofJozefowicz** [comment]
You can attach it directly in this issue as this is a vital for us and other RED users to get what is happening and what is the resolution.
Anonymize source code and include it on github.
![image 1](https://cloud.githubusercontent.com/assets/3999733/26191632/ec3eb5c4-3bae-11e7-85f2-664d01c269da.png)

**Comment by KrzysztofJozefowicz** [comment]
no reply since 15 days

**Comment by lfteixeiraVB** [comment]
Sorry for the delay. 
I cannot provide the code even anonymized.
can you please provide me your e-mail? I can show you some examples.
