### ISSUE TITLE
No possibility to download latest versions of RED

### ISSUE THREAD

**Issue by jkurkowski** [nokia/RED#110]
Hi all!

I've noticed that there is a problem with downloading files, i.e. when I want to download latest version of RED which is under:
https://github.com/nokia/RED/releases/tag/0.7.7-fix
I receive an error that page cannot be reached.

Do you have any mirrors which points to that files?
Thanks a lot in advance!

Br!

**Comment by KrzysztofJozefowicz** [comment]
Hi
It looks like network problem or GitHub issue, I can download latest versions without any problems.

Apart from getting RED as a product (Eclipse+RED feature +custom icons), you can install RED into existing/clean Eclipse which will provide you the same experience as RED product. 

Download Eclipse, from Help menu choose Eclipse Marketplace and search for RED.
More info: http://nokia.github.io/RED/help/first_steps/download_install.html

**Comment by jkurkowski** [comment]
Thanks a lot for your prompt response, will try to follow your instructions!
