### ISSUE TITLE
In Debug Variable Panel difference between Robot Dict and Python Dict not visible.

### ISSUE THREAD

**Issue by kootstra** [nokia/RED#111]
When running RED in debug mode and looking at the variable at a break point it is not clear from the overview if a certain dictionary is based on the Robot `DotDict` class or the regular Python `Dict` class. The implications of this is that the Robot dot-notation (`${var.attrib.subattrib}`) not useable on the latter and needs to be addressed using the bracket notation (`${var['attrib']['subattrib']}`). 

In the below image the `${data}` variable is based on the Python `Dict` class and the `${rdata}` is on the Robot `DotDict`. 

![robot-dict](https://cloud.githubusercontent.com/assets/7235521/26286967/581f9bc2-3e71-11e7-986d-787b238485f7.PNG)

My Suggestion is to highlight the difference by using the current way for the dot-notation and use variable name surrounded by brackets when the class is not Robot DotDict.

**Comment by KrzysztofJozefowicz** [comment]
Hi Anne
Can you provide us user scenarios for such change? Indeed,your idea seems valid, we would like to discuss changes using your needs.

**Comment by kootstra** [comment]
The basic user scenario is when someone wants to connect an existing Python Library and the output of the library functions are objects or dictionaries. When using the bracket notation these will be accessible, but a lot of examples use the dot notation. In RED the objects/dictionaries are shown in a way that always suggested to me that dot notation would be possible. 

Through personal experience I've learned that dot notation is subject to using the Robot Dot Dict class. The dot notation has a higher readability and that is why I prefer it over the bracket one. Making it clear in the Variable panel that an object is only accessible through bracket notation would have saved me a lot of time puzzling and experimenting. I'd like to see other not go through the same experience.

**Comment by michalanglart** [comment]
From what I understand the tree structures as depicted on your example are fine, right? Would it be sufficient to add python's type names into labels of presented objects?

Or would like to have those two objects somehow differently structured?

**Comment by michalanglart** [comment]
Hi Anne,

we're currently changing quite a lot in debugger, so that couple of problems regarding remote debugger session will be resolved. 

We will now also send types of dictionaries/lists back to RED, so that this issue can be resolved. How would you like to have it presented in Variables view? Take a look at screenshot, is it fine to just show those types in label, or should it also have somehow different structure?

![types_proposal](https://user-images.githubusercontent.com/14932410/27830153-56f29ce2-60c5-11e7-9bae-803e4c049cc4.png)

**Comment by michalanglart** [comment]
This has been implemented in 0.8.0 in a way depicted above. Additionally one can show additional column where the actual type of an object is shown.

**Comment by kootstra** [comment]
Thanks!
