### ISSUE TITLE
[BUG?]red.xml will be change when rename a file

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#112]
When I rename a file in my project (filename include Chinese chars)
the red.xml will be wrote broken, the library section changed into the filename.

Maybe it is a bug?

**Comment by KrzysztofJozefowicz** [comment]
Thanks for reporting. Indeed,something is wrong when unicode file is renamed while in red.xml referenced library entry is present,  We will look into it.

**Comment by KrzysztofJozefowicz** [comment]
Rename of file,file move or project rename causes the same outcome - referenced libraries part is edited.
It is not caused by unicode/chinees/special characters, it was introduced in "Project Rename" functionality.
Either we will fix it in next release (rewriting) or we will roll back this feature.

**Comment by KrzysztofJozefowicz** [comment]
Project Rename feature was disabled in 0.7.9

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.1
