### ISSUE TITLE
Can I make "auto complete" window auto appear?

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#114]
When I input keywords, I can press Ctrl+Space (In my Chinese version windows, it is ctrl+alt+space) to open auto complete window.

Can I make this window open automatically? I mean when I input the first char, the window will auto appear, do not need to press the Ctrl+Space

**Comment by KrzysztofJozefowicz** [comment]
Hi
It is not proper described in Help but you can setup RED in such way that code assist will be invoke on each key stroke.

Go to **Windows->Preferences -> Robot Framework -> Editor -> Content Assist**
for Auto activation delay - set 0 
for Auto activation triggers - set list of chars which activates Content Assist.
This: https://stackoverflow.com/questions/1959946/ctrl-space-in-eclipse-without-pressing-ctrl-space  suggests adding following string:
**._abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ**

We will add hint in Preferences and in Help

**Comment by Pantyhose-S** [comment]
Thanks， I will try it
