### ISSUE TITLE
Selenium Robot Framework - demo app - FF closes without any input.

### ISSUE THREAD

**Issue by satyendraCoder** [nokia/RED#115]
I am new to Selenium. 
I am using Eclipse with RED. I am trying to  get the demo app going but somehow Firefox closes without any input being filled in for valid_login and invalid_login.  I tried to increase $(Delay) in resource.robot to 10 seconds but although the browser stays up, nothing is  getting input from the scripts.  Please help..
--thanks

**Comment by joanna-may** [comment]
Hi,
we aren't responsible for Selenium library. RED is only editor for robot files, but from my experience I can tell you that you should check all versions of libraries and Firefox that you have installed.
For selenium version greater than 3.0 you should have Firefox > 47 and geckodriver for that specific FF versions:

https://github.com/mozilla/geckodriver/releases

Path where Geckodriver was extracted should be set in PATH variable. 
I tried to launch this demo on my computer today and I succeeded:
system: Windows 
FF: 53.0
Geckodriver: v0.16.1 (not the newest)
robotframework-selenium2library (1.8.0)
selenium (3.4.3)

As a workaround for error connected with proxy setting I setup empty folder for firefox profile.

*** Variables ***
${FF_PROFILE}  d:/empty_folder/prof

*** Keywords ***
Open Browser To Login Page
    open browser   ${LOGIN URL}    ${BROWSER}   ff_profile_dir=${FF_PROFILE}

**Comment by satyendraCoder** [comment]
Hi Joanna,


Thank you for the detailed explanation. I had old geckodriver(15.0) and the selenium2Library was 3.3.1. I updated both of these and I could run the demo app without any problems.


Thank you again for all your help.


Best regards,


satyendra


________________________________
