### ISSUE TITLE
robotframework-lint integration

### ISSUE THREAD

**Issue by AndreasRusjaev** [nokia/RED#116]
Good day,
We use at our buildserver robotframework-lint.
I would like in Red the possibility to use robotframework-lint.
Can you please consider whether you integrate the integration with [robotframework-lint](https://github.com/boakley/robotframework-lint/).
Thank you in advance.

**Comment by KrzysztofJozefowicz** [comment]
Hi
This can be done right now although there is no integration with RED ( RED does not show in editors issues reported by rf-lint). There are some stuff to be provided from RfLint (standardized output https://github.com/boakley/robotframework-lint/issues/33 ) but also on RED side we need to define API so external scripts/plugins would display markers on RED editors and in Problem View

Until than, rflint can be executed by user with custom script. 
Have a look into: http://nokia.github.io/RED/help/user_guide/launching/local_launch_scripting.html 

You need to create a python script (or any other one) which will be executed in Run Configuration,script would take paths of TestSuites from RED and run RfLint with predefined rules.
Output of RfLint will be visible in Console View.

For now, using rflint as script configuration is the only way.

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.1
