### ISSUE TITLE
Debug log view

### ISSUE THREAD

**Issue by hancockks** [nokia/RED#117]
RED currently provides a Message Log view while debugging.  It would also be nice to provide a Debug Log view that would add a --debug debug.log to the parameters.

**Comment by KrzysztofJozefowicz** [comment]
Hi
Actually you can do it right now for existing Debug Configuration.
Open Debug Cofigurations:
![debug-1](https://user-images.githubusercontent.com/3999733/27673541-8a39f5f0-5ca1-11e7-9669-55df46c45693.png)

For selected Debug Configuration, under Robot tab there is a filed for additional robot arguments.
Here you can pass anything to be used by Robot execution.
--debug <path_to_debug> where path is relative to current Project or has a absolute path
![debug-2](https://user-images.githubusercontent.com/3999733/27673605-d97b760c-5ca1-11e7-9f53-32ef8f42e6c4.png)

If you would like to have this "by default" for every new Debug Configuration, go to Windows->Preferences,under Robot Framework -> Launching -> Default Launching Configurations
Note that in this way, Run Configuration will also have this argument attached.
![debug-3](https://user-images.githubusercontent.com/3999733/27673795-de68989c-5ca2-11e7-9318-682856b8ef6d.png)

Is it fine for you this way?

**Comment by hancockks** [comment]
Almost -- in fact I'd previously done as you suggested.  As far as I know, the only think I can't do is get a "tail" view of the debug.txt log.  I had originally posted this request as I figured it would be a easy change to the Message Log view, though I see I could get the equivalent functionality via the LogViewer plugin: http://marketplace.eclipse.org/content/logviewer#group-external-install-button
