### ISSUE TITLE
Cannot delete variable file from red.xml when file does not exist

### ISSUE THREAD

**Issue by soyacz** [nokia/RED#12]
Recently I moved my tests to another directory. Now, in red.xml file, in variable files section I have wrong path - I tried to **right click ->delete** but it doesn't work.
As a workaround, I must delete it from another text editor manually.

**Comment by KrzysztofJozefowicz** [comment]
Hi
I am having difficulties to reproduce your case. Files/folders can be change within RED or under OS level. As I using Win7 I have checked both scenarios (project with testcase, var files under folder, change folder name and file name, try to delete entry from red.xml) and I was able to remove wrong entry. 
Can you provide more details how you made it?

Note: RED does not track changes between filenames/paths and red.xml entries therefore if you rename a folder with var files inside, path will not be changed in red.xml. Refactoring mechanism is planned but not in the nearest release.

**Comment by soyacz** [comment]
I'm using linux.
I loaded my tests on another machine (also linux), also directory has changed.
Original variable directory contained spaces.

**Comment by KrzysztofJozefowicz** [comment]
Thanks for reply, one more thing - from where the path is changed - relative inside Project path or from root?

**Comment by KrzysztofJozefowicz** [comment]
One more remark:
do you happened to use Ubuntu/Mint with GTK? It seems there is an issue under Ubuntu with Eclipse programs (GUI gets messed up). I was able to reproduce it with Mint and Ubuntu, not a case under RH7.
Try to press Delete key, this worked under Ubuntu.

did googling:
http://askubuntu.com/questions/538318/how-to-work-around-eclipse-luna-gtk-bug-339174-change-to-not-use-oxygen
https://bugs.eclipse.org/bugs/show_bug.cgi?id=470994 and linked bugs

**Comment by soyacz** [comment]
Yes, it was Mint on cinnamon, possibly gtk theme. I'll check it later.
Thanks!

2016-04-04 13:34 GMT+02:00 Krzysztof Jozefowicz <notifications@github.com>:

**Comment by soyacz** [comment]
I tried again, also in classic theme, issue still occures. But Delete key
does its job.


2016-04-04 14:10 GMT+02:00 Łukasz Sójka <soyacz@gmail.com>:

**Comment by KrzysztofJozefowicz** [comment]
We will have a look into it but I am afraid that this may be Eclipse/GTK issue which is independent from us.
