### ISSUE TITLE
It seems that variable value mapping can only take string but not from another variable

### ISSUE THREAD

**Issue by ericNokia** [nokia/RED#120]
E.g such example does not work in red.xml file

    <variable name="${ROOT}" value="/home/test/"/>
    <variable name="${RESOURCES}" value="${ROOT}/workspace/foo/resources"/>

The RESOURCES value is not defined as $ROOT valuer can not be resolved

![image](https://user-images.githubusercontent.com/30107647/28106736-47d54928-66e5-11e7-926d-7549f95e3e86.png)

**Comment by KrzysztofJozefowicz** [comment]
Hi Eric,
thanks for report, we will have a look into it.
If you are from Nokia,you can contact me internally so I will create a jira for you.
