### ISSUE TITLE
Is there any way to make table editing with syntax coloring?

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#121]
when I edit script in "source" view, the syntax coloring works well.
But in "test case" view, the table editing, the syntax coloring has no effect.
Is there anyway to turn it on?

**Comment by michalanglart** [comment]
Hi,

no it is not possible to turn it on. Currently there is no syntax coloring in tables

**Comment by KrzysztofJozefowicz** [comment]
This is scheduled to 0.8.4 release

**Comment by KrzysztofJozefowicz** [comment]
released in RED 0.8.4
