### ISSUE TITLE
Why some times auto complete won't work in source view?

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#122]
I have 4 computers installed red with eclipse.
In first days, all of them works well.
But now, 2 of these computers, auto complete window won't show int "source" view.
In "test case" view and "keywords" view, auto complete window still works well.
Is there any thing wrong?

By the way, I am using Chinese version Windows.

**Comment by michalanglart** [comment]
Hi,

we haven't seen such problem. Is there any exception thrown? Any popup with error message? As far as I understand it does not work on those 2 computers regardless of cursor position inside source editor? Does assistant open on auto-activation chars? (those are characters which should trigger assistant popup when typed - you can specify them in Window -> Preferences -> Robot Framework -> Editor -> Content Assist -> Auto activation triggers)

You can take a look into .log file which should be placed in your workspace in /.metadata/.log. This is a file to which eclipse is reporting some errors or warnings. Is there anything suspicious logged in it?

**Comment by Pantyhose-S** [comment]
OK, I will see the log, there is no error popup shown.
May be it is my Chinese input method makes this problem? 
4 of my computers have the same config (auto-activation chars), and in first 2 or 3 days, all of them works well. I did not change any config, it won't work now.

By the way, if the red.xml includes Chinese chars (for example, a project whit Chinese name), there will be a problem. I see the red.xml is UTF-8 encoded, but it looks like the red plug load it in GBK encoding?

**Comment by michalanglart** [comment]
Ok, please check the log file.

As to the encoding: after quick checking in the code it seems that indeed there is a bug. The red.xml is written using UTF-8 (https://github.com/nokia/RED/blob/master/src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/main/java/org/rf/ide/core/project/RobotProjectConfigWriter.java line number 28) however it is read using default charset as taken from system (https://github.com/nokia/RED/blob/master/src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/main/java/org/rf/ide/core/project/RobotProjectConfigReader.java line 48) - InputStreamReader should be created with UTF-8 charset.

**Comment by qianchangchun** [comment]
I have the same problem with the guys. I can only use the content assistant in test case window, but I can not use in the source window, I installed RED in Oxygen in 3 computers, none of them can use content assistant in the source view. One computer run Win7 64 bit Chinese  version, the other two run WIN10 64 bit Chinese version.

**Comment by KrzysztofJozefowicz** [comment]
There was few months of inactivity of this issue, @qianchangchun please provide more information how we could reproduce your behaviour on our site.

**Comment by KrzysztofJozefowicz** [comment]
@qianchangchun can you verify if content assists works when changed those options are selected :
Window -> Preferences -> Robot Framework -> Editor -> Content Assist -> Auto activation enabled,
in field Auto activation triggers: you can put whole alphabet: abcdefgdhijklmnopqrstuwxyzABCDEFGDHIJKLMNOPQRSTUWXYZ

Please verify if this changes anything in your case

**Comment by qianchangchun** [comment]
Yes， it works correctly when I put whole alphabet in field Auto activation triggers, sorry for the delay replay and appreciation.
