### ISSUE TITLE
RuntimeWarning raised by the robot when RED is using Python3

### ISSUE THREAD

**Issue by filug** [nokia/RED#126]
**My setup**
- Eclipse: Oxygen Release (4.7.0)
- RED plugin: 0.7.9.2017062909 (installed via Marketplace)
- distro: Debian Stretch
- python3: 3.5.3
- robotframework: 3.0.2 (installed via pip3 install robotframework)

RED configured to use `python3` as described in #125 

**Issue**

Tests executed via `Run` button in Eclipse are executed but in addtion always following warning is reported 
 
```
/usr/lib/python3.5/runpy.py:125: RuntimeWarning: 'robot.run' found in sys.modules after import of package 'robot', but prior to execution of 'robot.run'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
```

Tests executed via `pybot` or `robot` are no affected by this warning.

** Example test to reproduce this issue**

```
*** Test Cases ***
Show Hello World
    Log    Hello World!
```

**Comment by michalanglart** [comment]
Hi,

This is reported issue for Robot: https://github.com/robotframework/robotframework/issues/2552 - it's exactly this case: RED launches tests using python -m robot.run 

Either it will be repaired by some upcoming RF release or we could see if we can launch tests using python -m robot command line. 

As Pekka stated - although annoying it is probably safe to ignore it.
