### ISSUE TITLE
Is there an "pause on failure" option?

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#129]
There is an option named "pause on failure" in ride, when a keyword failed, the script will auto pause.

This is useful when debugging scripts.

Is there a similar option in RED?

**Comment by michalanglart** [comment]
Hi,

no currently there is no such feature. However it was already raised in #77 - possibility to add breakpoints which supsend debugger when keyword fails.

We are currently making quite a lot of changes in debugger area and it will be possible to easily implement this feature after those changes are made. Those changes will be released with next version (0.7.9+1, probably would be called 0.8.0) - maybe within 1-2 weeks from now. 

With a little bit of luck and time maybe we would be also able to implement such breakpoints with next release. If not - I think they could be implemented in version 0.7.9+2.
