### ISSUE TITLE
Debug doesn't work

### ISSUE THREAD

**Issue by soyacz** [nokia/RED#13]
Hi,
I have problem with debug mode.

1. I open test case file, run tests
2. I switch to debug perspective
3. Set a breakpoint
4. debug the script
5. robot script is automatically terminated:

> <terminated>organizationMembers.robot [Robot]	
> 	Robot Test at 127.0.0.1:36508	
> 		Thread [main]	
> 	<terminated, exit value: 1>/usr/bin/python	

In run window I get message:

> Command: /usr/bin/python -m robot.run -P /usr/local/lib/python2.7/dist-packages/MongoDBLibrary:/usr/local/lib/python2.7/dist-packages/RequestsLibrary:/usr/local/lib/python2.7/dist-packages -V /home/user/Dokumenty/Projekty/project/moje/superProject/tests/localhostTestEnv.py --listener /tmp/RobotTempDir6523292357047703582/TestRunnerAgent.py:36508:True -s Tests.Rest.Organization.OrganizationMembers /home/user/Dokumenty/Projekty/super project/moje/superProject/tests

> Suite Executor: Robot Framework 3.0 (Python 2.7.11+ on linux2)
>+=============================================================================
> Tests                                                                         
> +=============================================================================
> Tests.Rest :: Rest tests do REST api calls and check if responses are ok.     
> +=============================================================================
> Second signal will force exit.

My system: linux ubuntu 16.04 (cinnamon/unity desktop). Run with --launcher.GTK_version
2 option in RED.ini file.

**Comment by adam-wypych** [comment]
Hello,

Can you check with just simple test case like below?
```robotframework
*** Test Cases ***
T1
    Log    ok
```

**Comment by soyacz** [comment]
OK,
I did some research on this issue.
Tried your example, but stiil problem existed.
I started new project and then debug was working.
I got back to my problematic project and removed mongoDBLibrary (which
actually wasn't installed anymore as I changed the system recently) and it
started to work!

So please check if problem isn't due to missing library added to red.xml

Thanks
Łukasz

2016-04-28 7:00 GMT+02:00 adam-wypych <notifications@github.com>:

**Comment by soyacz** [comment]
Hmmm,
Problem got back again on more complicated test. I'll check it later and
let you know how to reproduce it (I hope so).

2016-04-28 21:10 GMT+02:00 Łukasz Sójka <soyacz@gmail.com>:

**Comment by Mateosy** [comment]
Hi,
The problem is fixed. It is related to differences between keyword types in RF version < 3.0 and RF version > 3.0, these types are received and handled during debugging process.
The fix will be available in the next release.
