### ISSUE TITLE
Importing python libraries with arguments seems not possible

### ISSUE THREAD

**Issue by everthuijben** [nokia/RED#130]
I like the functionality that Red can discover automatically all used libraries and add them in your project as 'Robot Referenced libraries'. However some of them give an error, especially the ones which need arguments. When I reload them I got the message (in details): "Test Library '<MyLib>' expected 1 argument, got 0."  However, where can I enter those arguments? I also took a look into the red.xml tab and file, but there seems no field available to enter those arguments. Maybe this  might be a usefull adition to the Red functionality

**Comment by michalanglart** [comment]
Hi,

Yes - this is not supported and remains open in #47 (also look at #65). Hopefully we will be able to implement this soon

**Comment by blueacorn** [comment]
Provide a default value for your class init arguments to allow the library to be imported, e.g.:
```py
class MyClass(object):
    def __init__(self, myarg1=None):
        ''' Constructor '''
```

**Comment by michalanglart** [comment]
Closing, as this duplicates #47
