### ISSUE TITLE
Need support for Pycharm

### ISSUE THREAD

**Issue by jcyrss** [nokia/RED#131]
Now most engineers uses Robot are QA engineers. 
The IDE  they used have switched from Eclipse to Pycharm  as I know.
So I think it's very import to add support for let RED run on Pycharm.

thanks

**Comment by KrzysztofJozefowicz** [comment]
Hi
Most of QA engineers in Nokia uses Eclipse or intend to move to Eclipse due to licensing, in order to support them we focus on Eclipse platform. PyCharm support is postponed until business needs changes or team size gets bigger.

**Comment by michalanglart** [comment]
Still no plans to provide PyCharm support. I'm closing it for now
