### ISSUE TITLE
RED Editor is freezing up when saving .robot file

### ISSUE THREAD

**Issue by blueacorn** [nokia/RED#132]
I am having problems where the RED editor UI freezes up for 30 seconds to several minutes every time i save a .robot file; and then I try to continue editing a file / save another file.
- The progress window shows it is spending several minutes "Building Workspace" ...

I am using the latest 0.7.9 Windows version
https://github.com/nokia/RED/releases/download/0.7.9/RED_0.7.9.20170629090422-win32.win32.x86_64.zip

As a programmer, i instinctively hit save regularly - and it's locking up the editor :/

Can someone please explain how to disable the "Building Workspace" step on save - or if there is something wrong with my setup.

_Thanks,_

**Comment by michalanglart** [comment]
Hi,

It's something wrong with RED rather than your setup. 

First of all validation may take time for bigger projects, however it runs in separate thread, so it shouldn't lock GUI. You may turn it off: uncheck Project -> Build Automatically in toolbar menu. Please do so and check if that helped.

You may also limit validation to run only for certain part of project: http://nokia.github.io/RED/help/user_guide/validation/scope.html

Regardless whether turning off validation helps or not would you be able to provide us call stack (thread dump) of RED performed when GUI is freezed? This would allow us to see why the GUI thread is locking.

**Comment by KrzysztofJozefowicz** [comment]
@blueacorn , could you share some more information about your project? 
How many robot files,what is the size, which python interpreter do you use (python,jython ironpython), 
Does it happen in both source editor and table?

**Comment by blueacorn** [comment]
@KrzysztofJozefowicz sorry for the delay, some more info for you:
2x .robot files
Approx. 10 .py user files, and ? vendor library .py, .pyc files.
Using Windows 7, 
with python26 (The IDE / path is pointing at 27), but the source project files call (legacy) python libraries that require 26.

I've disabled the 'Project -> Build Automatically' option and it's usable now.

Could python26 be causing the issue?

**Comment by michalanglart** [comment]
I guess python 2.6 might be causing this issue. We need to check that to confirm.

**Comment by michalanglart** [comment]
Ok confirming. I cannot make RED work with python 2.6.6. As of now there are syntax problems in our python scripts which RED uses.

We'll have a closer look, maybe it is something we can fix easily.

**Comment by blueacorn** [comment]
Thanks @michalanglart,

I wouldn't spend much time trying to support Py2.6 as it's been deprecated so long ... and no other tools in the chain will deal with 2.6. The only reason we're using 2.6 is because we have a piece of test equipment dependent on it - and we're currently trying to upgrade that to latest.

It was a real PITA trying to get a mixed env where RED and all the rest of the tool chain uses 2.7 - and our source interpreted with 2.6!

Disabling "Project - Build automatically" is suffice workaround :+1:

**Comment by michalanglart** [comment]
Don't worry we'll not spend too much time on it however I would like to take a look anyway. If that's something we can fix quickly then you may expect it to be patched.

We're supporting RF 2.9.x and it should work with python 2.6, so despite the fact that 2.6 is old it would be nice if it works.

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.1
