### ISSUE TITLE
Configuring a Robot project replaces an existing red.xml

### ISSUE THREAD

**Issue by justinclagg** [nokia/RED#138]
If an imported project already has a red.xml file, selecting "Configure as Robot project" will overwrite red.xml.

It would be helpful if there was a check for an existing red.xml, and either no overwrite, or an option to overwrite if desired.

In our case we are storing Robot projects in source control without .project. After importing the project we need to configure it as a Robot project, which replaces our red.xml.

**Comment by michalanglart** [comment]
Hi,

it seems to be a task for up to an hour, so we can probably do it for upcoming release. We plan to provide version 0.8.0 next week.
