### ISSUE TITLE
Installation on mac

### ISSUE THREAD

**Issue by SandeepSvanandan** [nokia/RED#140]
So after installing the RED plugin on Eclipse , ther red.xml gives out an error.. Saying it cant find the RF installtion/. I do a pip RF is installed 
On windows it works absolutely fine.. But how can i make RED work on Mac OSX?

Thanks
Sandeep

**Comment by michalanglart** [comment]
Hi,

what exactly is shown and where? Can you provide some screenshot or logs of the error reported?

**Comment by SandeepSvanandan** [comment]
Hi,
Added a screenshot

**Comment by michalanglart** [comment]
It seems you haven't attached anything

**Comment by sandisiva** [comment]
<img width="1085" alt="screen shot 2017-10-05 at 5 44 36 pm" src="https://user-images.githubusercontent.com/429155/31242744-9e3e0c18-aa25-11e7-8e34-f17f3cd7304f.png">

**Comment by michalanglart** [comment]
Here in this dialog you may define locations for your environment (python+robot). This has to be a path to the directory where python executable is located. If you hover your cursor over one of those entries you will see information like: "The location \Library\Python does not seem to be a valid python directory" - it means that RED didn't found any python executable inside it. 

I suspect that in your case the executable is located in \Library\Python\2.7 so you may try to add this directory.

Apart from that - if you have python added to your PATH environment variable then RED should detect it automatically (or by clicking Discover button)
