### ISSUE TITLE
Provide handy way of pausing test

### ISSUE THREAD

**Issue by michalanglart** [nokia/RED#141]
With RED 0.8.0 it is possible to pause/resume tests launched in Run mode (implemented in #64), however in not really convenient way. Currently user has to:

- launch the tests
- switch to Debug perspective
- select the Process in Debug view
- click pause either in toolbar or from context menu

It should be possible to be done without switching perspective. There should be pause/resume button added somewhere. I think there are 3 options where such buttons could be placed:
- toolbar similarly as in Debug perspecitve
- Console view near Terminate button
- Execution view (although maybe terminate should be added too in that case)

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.1
