### ISSUE TITLE
BUG: Table editor can not deal with "|" charator

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#146]
the script is like  below
send&nbsp;&nbsp;&nbsp;&nbsp;a | b

the string "a | b" is the arg of the keyword send.
in source view, it is ok, but in table editor, when I input this string in cell, I can not leave it,t is locked in this cell.

by the way, "a |b" is ok.

**Comment by KrzysztofJozefowicz** [comment]
workaround in table editors: add escape character \ before |.
`send    a \| b`
We are looking for possible fixes as | is one of special character used for separator (other is space and tab) and can be set as separator regardless of previously used separator in file.

**Comment by michalanglart** [comment]
Fixed in 0.9.0
