### ISSUE TITLE
Unable to import Python Libaries RED 0.8.0

### ISSUE THREAD

**Issue by mrosenhahn** [nokia/RED#147]
I just recently updated from RED  0.7.2 to RED 0.8.0. I have a number of custom libraries written in Python that are used in my tests and prior to upgrading to 0.8.0 I was able to import these libraries into my projects.

After upgrading to 0.8.0, when I attempt to import the library references to my project, the discovery process fails with the below error.

> Status: Not added to project configuration
Source: /etc/barista/packages/caferobot/cafe_common.py
Importers: /etc/barista/packages/caferobot/cafebase.robot
Additional info: RED python session problem. Following exception has been thrown by python service:
            Traceback (most recent call last):
              File "/tmp/RobotTempDir7383895089667181594/robot_session_server.py", line 27, in inner
                result['result'] = func(*args, **kwargs)
              File "/tmp/RobotTempDir7383895089667181594/robot_session_server.py", line 49, in inner
                return func(*args, **kwargs)
              File "/tmp/RobotTempDir7383895089667181594/robot_session_server.py", line 111, in get_classes_from_module
                return __extend_paths(to_call, python_paths, class_paths)
              File "/tmp/RobotTempDir7383895089667181594/robot_session_server.py", line 235, in __extend_paths
                return to_call()
              File "/tmp/RobotTempDir7383895089667181594/robot_session_server.py", line 109, in to_call
                return __cleanup_modules(red_module_classes.get_classes_from_module)(module_location, module_name)
              File "/tmp/RobotTempDir7383895089667181594/robot_session_server.py", line 206, in inner
                return to_call(*args, **kwargs)
              File "/tmp/RobotTempDir7383895089667181594/red_module_classes.py", line 32, in get_classes_from_module
                return _call_with_extended_sys_path(to_call, os.path.dirname(module_location))
              File "/tmp/RobotTempDir7383895089667181594/red_module_classes.py", line 58, in _call_with_extended_sys_path
                return to_call()
              File "/tmp/RobotTempDir7383895089667181594/red_module_classes.py", line 28, in to_call
                loaded_module = _load_module(module_location, module_name, module_name_from_location)
              File "/tmp/RobotTempDir7383895089667181594/red_module_classes.py", line 80, in _load_module
                return importlib.import_module(_get_module_name_by_path(module_location))
              File "/opt/ActivePython-2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
                __import__(name)
              File "/etc/barista/packages/caferobot/cafe_common.py", line 7, in <module>
                from cafe.app import App
              File "/etc/barista/packages/cafe/__init__.py", line 11, in <module>
                from cafe.runner.decorators import test_suite
              File "/etc/barista/packages/cafe/runner/decorators.py", line 10, in <module>
                from cafe.runner.parameters.options import options
              File "/etc/barista/packages/cafe/runner/parameters/options.py", line 3, in <module>
                from cafe import __main__
            ImportError: cannot import name __main__

I reverted back to 0.7.2 and was able to import the libraries into the project. I then upgraded again to 0.8.0 and the added library references were still present in the project.

**Screen snipped of a successful import release 0.7.2**
![successful import](https://user-images.githubusercontent.com/25513789/32566954-9348f102-c46e-11e7-87fd-eeccd4d28a76.JPG)

![succcessful2](https://user-images.githubusercontent.com/25513789/32566976-a463aa72-c46e-11e7-871a-d5e273e443e0.JPG)

**Screen snipped of a failed import release 0.8.0**
![failed import](https://user-images.githubusercontent.com/25513789/32566983-a94ae47e-c46e-11e7-811f-1b1b872d8c8a.JPG)

![failed 2](https://user-images.githubusercontent.com/25513789/32566988-accb26c2-c46e-11e7-907f-7ceb3f2ff261.JPG)

Is there some setting that now needs to be made to import some Python libraries now?

**Comment by KrzysztofJozefowicz** [comment]
Hi
Can you tell us your env setup? Python version/type, Robot. Is the CafeRobot a public library which we could have a look?

**Comment by michalanglart** [comment]
Hello,

It would be also great if you would be able to tell us which RED version breaks it. There is one year gap between 0.7.2 and 0.8.0 so lot of development have been made in this time frame.

**Comment by mrosenhahn** [comment]
@KrzysztofJozefowicz,
  We are currently running our test on CentOS 6.7 and CentOS 7 VMs. The Python distribution we are using is ActivePython-2.7.

  CafeRobot is an in-house, non-public, rework of the existing Robot runner so that we could reuse our prior existing Python test application libraries. I'll need to check with my group to see if I can share these libraries with you for review.

@michalanglart 

  I'll try out the various release since 0.7.2 and try to have an answer back to you within a day or two.

**Comment by mrosenhahn** [comment]
@michalanglart ,

  The last RED release where I was able to import my custom libraries was 0.7.6.201703311037.

  Builds 0.7.7, 0.7.7-fix, 0.7.8, 0.7.9 and 0.8.0 all fail.

**Comment by KrzysztofJozefowicz** [comment]
@mrosenhahn thank you for prompt response, we will check what has changed between 0.7.6 and 0.7.7.

I understands that you reluctant to share your private lib,which is understandable. 
Are you able to do some investigation on your side? 
Create simple project with only one import library to check which lib caused that exception in RED server side (there maybe only one or multiple, in this case pick the smallest). When you would have one, try to remove library logic part at the time to find exact part which is problematic. If you could share it (stripped from logic,internal methods,functions - anonymized) we would highly appreciate it.

**Comment by mrosenhahn** [comment]
@KrzysztofJozefowicz 

  Looking at the stack trace raised by RED, it is having trouble importing the module main. This module is inherited by a number of libraries within our framework and was used for allowing the libraries to be run any of our test cases written in Python to be run in the Python.

  The actual name of the module in question is **__main__.py** and is being imported by the other Python modules as **import cafe.__main__**. This module is not written as a class and other than the package __init__.py modules, is the only other module with a double leading and trailing "__" in the name.

**Comment by KrzysztofJozefowicz** [comment]
we have problems to reproduce this behaviour looking at stack trace, can you provide library snippets?

**Comment by mrosenhahn** [comment]
@KrzysztofJozefowicz 

Attached are some code snippets. The __main__ is all the code, the other files I just have the import statements only.

[cafe.zip](https://github.com/nokia/RED/files/1492564/cafe.zip)

**Comment by KrzysztofJozefowicz** [comment]
Thanks for sources, we still figuring out what can be wrong. Can you try following on your side to check if this is somehow related with PYTHONPATH load/unload modules in recent RED? 

Add to system PYTHONPATH cafe folder: `export PYTHONPATH=${PYTHONPATH}:/etc/barista/packages/cafe` and try to discover libs in 0.8.0.  Is the output the same or different?

**Comment by mrosenhahn** [comment]
@KrzysztofJozefowicz 

I'll try to get you an answer on your last request by next week. It is a short week here this week with the long weekend and I am trying to close out some other issues for the week before heading out.

**Comment by modrz** [comment]
Hi,

It looks like the problem is connected to import cycles in your python libraries.
See [https://stackoverflow.com/questions/744373/circular-or-cyclic-imports-in-python/746067#746067](url)


I have simplified attached libraries and created simple RED project here [GitHub #147.zip](https://github.com/nokia/RED/files/1600072/GitHub.147.zip)
Import problem can be reproduced by following steps:
1. Add **libs** folder from **`GitHub #147.zip`** to PYTHONPATH
2. Import **cafered** project from **`GitHub #147.zip`**
3. Run adutodiscovering
4. All libraries will be found
5. Switch import type in libs\cafe\runner\parameters\options.py (**lines 1-2**)
6. Run adutodiscovering
7. Finding some libraries will fail

Can you verify it in your environment?

**Comment by mrosenhahn** [comment]
Will do, I have past your request along to the keeper of our framework to test things out and try to have an answer back in a couple of days.

**Comment by parul001** [comment]
hello
i am trying to import a custom  java library but its showing error Status: not added to project configuration .
in order to add library i am making a public class with public methods  exporting it to a jar  and then adding it to red .xml as java library. i am also defining path to jar file in Classpath field of red.xml.
please help i got stuck here . my configuration is :
Robotframework with jython version :3.0.2
Editor : RED 
thanks 
Parul Bhargava
