### ISSUE TITLE
Java memory leak during use of the message log

### ISSUE THREAD

**Issue by everthuijben** [nokia/RED#149]
When the 'message log' pane is used, the java process is continuesly increasing it's memory usage, especially when the logging is set to 'TRACE'.
In my case initially the java process takes around 800mB of memory and when running tests for half an hour with trace logging, I end up with 9.2GB. Also when you run a next set of tests, the memory is not cleared. It seems that 'message log' and 'console' pane data is sent to memory. when to log is set to 'ERROR' only a small increase of memory is found. 
Only a restart of eclipse is setting back the memory usage to 800mB. Running from console does not have these issues, since the Java process is not used.
Found with Java version 8, Ubuntu16.04, Eclipse Oxygen and Red 8.0

**Comment by KrzysztofJozefowicz** [comment]
Thanks, we will look into it closely, it seems critical for RED as Message Log and Console panes are activated by default.

**Comment by KrzysztofJozefowicz** [comment]
There is a couple of things going on under the hood when message log is saved and resolution needs to be evaluated,thus we will not be able to provide final fix in upcoming 0.8.1 release. 
Internally there is no space limit for message log, also RED keeps history of last 100 launches (idea behind that was to allow in future to run concurrent launches  so in case of bug amount of tests and message logs (we estimated this as a rare case) you hit the memory issue. If you could click 100 run button for small tests,memory would be freed but this is not a valid workaround ;)

What we could do in upcoming 0.8.1 is to limit message log launch history to 1 and add button to clear/flush message log - there is already button to save it to file so in some cases this could help a bit. 

We will evaluate what to do with size of message log during the run time - most probably we will use some kind of sliding window with set size to discard older logs (or to save it to file in temp dir). Can you give a comment about it? Do you need to have all execution logs or just last n-th,do you need to save it specific folder etc. We would be grateful for your input.

**Comment by everthuijben** [comment]
Hi,
Setting the limit to 1 is already a good workaround, as there is no need anymore to restart Eclipse to free memory. 
Setting a sliding window seems a good solution, since I usualy only dive into the latest lines of (TRACE) logging. If there is a need to dig into all other logging, a logging file is a good idea, however in most cases the test has stopped at an error, so that is usualy the latest logging. Besides that, there is also the possibility to do debugging, so an external file is not a must.
Thanks for the quick investigation,
Regards,
Evert Huijben

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.1
