### ISSUE TITLE
Resource importing another resource

### ISSUE THREAD

**Issue by fictor** [nokia/RED#15]
Hi,

Me and my team started a few week ago to use the RED plugin and it works very well. But, we have one very annoying issue and it is when we import a resource file inside another resource file. When we it, the RED plugin is complaining that the newly imported resource is not available in the project(no link). But, the newly imported resource imports the required files using relative paths and Python is able to run the code without any issue.

Currently, we have import and link every resource and their dependencies for every projects. Here is an example to help you understand the issue: if I import a new resource to a resource being used by X projects, I will need to add a link of this new resource for all the X projects and if this newly imported resource needs resources that one of these X projects don't have, we have to import the missing links to these projects until all the links are imported for every projects.

Do you have a solution for this issue? We are searching for a solution similar to C headers where you can include a header that includes other headers and the newly included headers use the relative paths to find the other dependencies.

Thank you,
Felix

**Comment by adam-wypych** [comment]
Hello,

Sorry I have one question, do you using virtual files eclipse feature? Means you adding this parent resource with other depend resource via File->Import->File System->Create links in workspace option?

Best Regards,
-Adam.

**Comment by fictor** [comment]
Tes, exactly

Sent from my Windows Phone
________________________________

**Comment by adam-wypych** [comment]
Currently the only option, which I see is to link whole directory where resource files are stored. 
I will disscuss with team, if is possible to extend current functionality to follow links location.

**Comment by fictor** [comment]
Ok, thank you for you answer.
