### ISSUE TITLE
eclipse red plugin cann't stop python.exe

### ISSUE THREAD

**Issue by cay914** [nokia/RED#150]
Hi, I use eclipse to debug robot framework script.
It can open browser, but python process cann't stop when it finish testing.
![eq mr olav5 usit_ k](https://user-images.githubusercontent.com/6037435/32932746-c3007db6-cba3-11e7-82b4-fe09949f80b1.png)

RED can't stop chromedriver.exe in eclipse.
![yzp2vcu b a56dwfe2 o57](https://user-images.githubusercontent.com/6037435/32933226-b169ce26-cba4-11e7-9b52-40a48161a8c7.png)
please fix it up, thank you!

**Comment by KrzysztofJozefowicz** [comment]
This looks like SeleniumLibrary & ChromeDriver issue, not RED/Eclipse. 
Do you execute anywhere Close Browser like suggested in https://github.com/robotframework/SeleniumLibrary/issues/692 ?

**Comment by cay914** [comment]
This issue doesn't appear. It maybe my eclipse's problem. thanks
