### ISSUE TITLE
Is there some way to execute  script after rf tests.

### ISSUE THREAD

**Issue by aihuasxy** [nokia/RED#151]
For example,after tests is done, execute script to analyze the result.

**Comment by KrzysztofJozefowicz** [comment]
Hi
RED can either execute robot directly or execute user script which is what you are looking for.
In essence, you should create script which accepts arguments and pass them to run robot tests and after tests are done, additional logic should be done. 
Scripts can be either *.bat, *.exe or *.com,  for others (like .py or bash scripts) interpreter needs to be set as executable file with argument to script.

Please have a look into example: [http://nokia.github.io/RED/help/user_guide/launching/local_launch_scripting.html](http://nokia.github.io/RED/help/user_guide/launching/local_launch_scripting.html) 
If you need any assistance,please leave here a message

**Comment by michalanglart** [comment]
Latest RED version 0.8.0 is based on eclipse oxygen in which you may use launch groups: https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fdebug_launch_groups.htm

Assuming that your eclipse/RED has e.g. pyDev installed you may setup a launch group which will firstly run robot tests and then execute some python script.

**Comment by aihuasxy** [comment]
Thanks very much!
exactly what i what !!

**Comment by michalanglart** [comment]
Just out of curiosity, which one? Wrapping script or launch groups?
