### ISSUE TITLE
Why the "Remote" library in STDLIBS is not imported?

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#153]
I am using robotframework 3.0.
There is a library named "Remote" in STDLIBS.
When I create a robot project, other STDLIBS will auto be useable, but except Remote.
If I import the Remote.py in red.xml manualy, it will shows non-accessable

**Comment by modrz** [comment]
Hi,

Please check robot documentation: [http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#remote-library-interface](url)

> This library does not have any keywords of its own, but it works as a proxy between the core framework and keywords implemented elsewhere

You can add it to red.xml with "Add remote location" in Reference libraries section.
