### ISSUE TITLE
BUG? Some times run on "Test Cases" node got wrong script.

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#157]
In project explorer, the .robot file will show as 3 level like "a.robot  >> Tese Cases >> case 1.1".
I select the "Tese Cases" element and click Run command in context menu, most times it will run all the cases in the file, some times it will run the "default lunch config", equal to click the run button in toolbar, that will run the wrong cases.

**Comment by joanna-may** [comment]
Hi,
is it still reproducing? I tired to reproduce it but I couldn't on simple test like this:
```robotframework
*** Test Cases ***
test1
    log  1
    
test2
    log  2
    
test3
    log  3
```    
About Run button on toolbar - when editor is open it searches for run config for entire file. If it's not exist, then it is created. If no editor is not open then it checks Preference (Preference -> Run/Debug -> Launching) and by default is run previous run configuration. 

If it will happen again, please send us information about:
1. The Preference (Preference -> Run/Debug -> Launching)
2. Where was selection (editor, project explorer)
3. Check the list of run config in Run -> Run Configuration and check how many of the are in list
4. Which of this run config was run
5. Which of the should be run

**Comment by michalanglart** [comment]
Assuming this is not happening anymore. Please reopen or open new issue if this occurs again. Closing for now
