### ISSUE TITLE
Vaildation and auto complete will be wrong when I use 2 remote libraries

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#158]
I add 2 remote locations in red.xml, in red.xml, it shows green light.

In .robot file, I add these 2 libs
Library Remote 10.0.0.10:8270 WITH NAME LibA
Library Remote 10.0.0.11:8270 WITH NAME LibB

The script runs ok, both LibA and LibB are use able.

But some thing in RED is wrong.

First, the auto complete func can only deal with LibA, when I using LibB, it still shows LibA's keyword.

Second, in project explorer, the Remote lib(two were shown) in "Robot Standard libraries" is none access able, this makes script vaildcation fail.
And in "Robot Referenced libraries", there is one "Remote" library, keywords under it isin LibA.

**Comment by KrzysztofJozefowicz** [comment]
Hi
Verified, looks like KWs from first remote server from red.xml is taken into content assist, other remotes are not. If remotes are switch places in red.xml, first one is taken into content assist. 
This also applies with WITH NAME aliases, for each alias, only KWs from first remote from red.xml is used.

Libdocs for all remotes included in red.xml are generated and visible in Project Explorer.

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.2
