### ISSUE TITLE
I want to say this comment code is too gray :)

### ISSUE THREAD

**Issue by cay914** [nokia/RED#159]
![image](https://user-images.githubusercontent.com/6037435/33411878-0a2f0a4e-d5c3-11e7-9f8e-0c1e0d9aed93.png)

This is RED 's default setting.
I think comment code 's color is too gray.

**Comment by KrzysztofJozefowicz** [comment]
Default gray color for comments are set for default/white background which may not be visible if you change background color.
You can change comments color under: Windows->Preferences -> Robot Framework -> Editor -> Syntax Coloring.  You may notice that there are 3 profiles: default (for default/light theme),heliophobic (suitable for dark/darkest dark theme). Any changed to those two profiles are saved to "custom"

Background color of Source editor can be changed in Windows->Preferences -> General -> Editors -> Text Editors under Background color
