### ISSUE TITLE
Eclipse console can't display Chinese word

### ISSUE THREAD

**Issue by cay914** [nokia/RED#160]
![image](https://user-images.githubusercontent.com/6037435/33411983-c5a44f82-d5c3-11e7-8786-bf38cdddb2ae.png)

Environment:
win10
sts 3.9.1
python 2.7
robot framework 3.0.2

Eclipse console can't display Chinese word.
I have tried some way, but it doesn't work.
1) set robot code to utf-8 coding
2) set debug config to utf-8
3) set eclipse.ini to utf-8

and I found this robot script display well in windows console.
Maybe this is an eclipse 's issue or RED 's issue?

Thanks

**Comment by KrzysztofJozefowicz** [comment]
Thanks for info, i assume you user Chinees OS. Can you share locales and
keyboard Type? I will try to get hands on chinees VM Windows 7

30.11.2017 04:53 "Eric" <notifications@github.com> napisał(a):

**Comment by KrzysztofJozefowicz** [comment]
another note, does this also happens when you execute robot tests directly from console/cmd.exe?

**Comment by michalanglart** [comment]
Theoretically you are able to change console encoding in launch configuration as described for example here: https://www.mkyong.com/java/how-to-display-chinese-character-in-eclipse-console/

However it looks like RED does not react to changes of this setting, so I would say it's our issue.

**Comment by cay914** [comment]
1) run robot script in window  10 console
![image](https://user-images.githubusercontent.com/6037435/33426636-8b99514a-d5fd-11e7-8c14-e6c2b173936d.png)
It's OK.

2) locales and keyboard Type
![image](https://user-images.githubusercontent.com/6037435/33426873-4d62a9ac-d5fe-11e7-940d-b8a8bda37ccb.png)
![image](https://user-images.githubusercontent.com/6037435/33426878-5183ab6c-d5fe-11e7-8953-0bb9da3050e1.png)

3) about changing console encoding 
![image](https://user-images.githubusercontent.com/6037435/33426981-9b1ea560-d5fe-11e7-8955-79e4316ed480.png)
I have been set to utf-8

but in eclipse console is wrong.
![image](https://user-images.githubusercontent.com/6037435/33427000-b552e446-d5fe-11e7-860e-67ee9d5dad18.png)

**Comment by michalanglart** [comment]
Hi,

I was able to take a closer look and it seems to be related to python/robot/os.  I was testing with polish non-ascii characters and:

- when debugging it can be seen that the bytes coming to eclipse/RED from running python process stdout are invalid, so it is not a matter of console interpreting those bytes wrongly
- had no problems when running on linux (ubuntu)
- on windows it depends upon python versions: different characters (both incorrect, but just different) are printed when python 3.6 is used than those printed with 2.7
- with python 2.7 characters were fine when robot 2.9.2 was used, wrong with 3.0.x
- with python 3.6 and RF 3.0.x I was able to get proper characters by setting PYTHONIOENCODING=utf8 environment variable (try that)

Unfortunately so far I wasn't able to get proper characters when python 2.7 with RF 3.0 is used under Windows.

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.3
