### ISSUE TITLE
Possibly incorrect "Invalid Variable syntax" error with list and dictionary variables

### ISSUE THREAD

**Issue by hpschry** [nokia/RED#162]
Hi, 
I like the great work in RED and the progress it makes from release to release!

I think, there is an error in parsing some variable uses: while RED seems to accept "${${var_name}}" it prints an error "Invalid variable syntax" on "@{${var_name}}" or "&{${var_name}}". Both usages are accepted by robot framework and do work as expected there.

**Comment by KrzysztofJozefowicz** [comment]
hi
can you show us test suite example? Where do you get that error?

**Comment by hpschry** [comment]
Hi, 
for the dictionary variable the following produces this error:

`Create Suite Dict Var
    [Arguments]    ${var_name}    &{kwargs}
    ${var_name}=    Get Variable Value    ${${var_name}}    ${var_name}
    Set Suite Variable    &{${var_name}}    &{kwargs}`

produces:
Invalid variable syntax '&{${var_name}}'	

For the list case:

`Path "${path}" XML "${file}" Matches "${table}"
    @{table}=    Get Variable Value    @{${table}}    @{table}`

produces: Invalid variable syntax '@{${table}}'

**Comment by hpschry** [comment]
Sorry for the formatting, unfortunately line breaks removed, hope it is clear anyway, otherwise please let me know.

**Comment by hpschry** [comment]
Create Suite Dict Var 
    [Arguments] ${var_name} &{kwargs} 
    ${var_name}= Get Variable Value ${${var_name}} ${var_name} 
    Set Suite Variable &{${var_name}} &{kwargs}

Path "${path}" XML "${file}" Matches "${table}" 
    @{table}= Get Variable Value @{${table}} @{table}

**Comment by KrzysztofJozefowicz** [comment]
Thanks, I can see the error markers on line` Set Suite Variable &{${var_name}} &{kwargs}`  and `@{table}=  Get Variable Value  @{${table}}  @{table}`

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.3
