### ISSUE TITLE
Delete file/folder in robot project sometime report errors.

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#168]
Using the delect menu in project explorer view, some times itis ok, sometimes it report error. and sometime the file is deleted but still a error dialog is shown

In Eclipse error log, It report a java.nio.file.FileSystemException, and the message is "another program is using this file"

I am sure there is no other process using this file except Eclipse. maybe is RED locked the file?

**Comment by KrzysztofJozefowicz** [comment]
how often does this happens? File can be locked by another process from validation, lib discovery rflint analysis etc., I will try to reproduce it, if you will be able to reproduce it on your side please let us know.

**Comment by Pantyhose-S** [comment]
This will happen very often, some times I try to delete it again and will successful.
And when it happens, I can delete this file in windows explorer, no need to close eclipse.

**Comment by joanna-may** [comment]
The only thing that we know that is blocking is .jar file used in red.xml. If you try to remove project/folder where .jar is used then it cannot be deleted. There is problem too when you try to remove folder with interpreter that is located and used in project. 
If it still happening try to check what is blocking using. If I remember correctly
- on Windows: Resource Monitor
- on linux: lsof command (lsof -p 1753)

**Comment by michalanglart** [comment]
I'm closing it now. Please reopen if this issue repeats
