### ISSUE TITLE
"Run Rflint analysis" menu can not handle Chinese  character filename.

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#169]
When I select a file or folder with Chinese chars and  "Run RfLint analysis". It will report a exception.

robot_session_server.py line 47 in <lambda> 
UnicodeEncodeError
But in windows cmd, rflint can receive the chinese filename.

**Comment by KrzysztofJozefowicz** [comment]
confirmed with polish chars in filename.

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.3
