### ISSUE TITLE
Question : how to add external .py variable file

### ISSUE THREAD

**Issue by Formartha** [nokia/RED#172]
Hi,

I'm trying to add some external .py variable file to the IDE itself without declaring it in the robot runner.
The reason I'm trying to do it is to avoid the issue where RED shouts that there is no variable declared with a value.

What's the best approach for doing it?

The use case is to create a variable file with all the SUT (system under test) parameters (such as ip addresses, protocols etc.) that will be generated by jenkins while building the system for testing.

Thanks,
Mor

**Comment by modrz** [comment]
Hi,
You can use variable files section from red.xml file.
It is described in RED help:
http://nokia.github.io/RED/help/user_guide/working_with_RED/variable_files.html
