### ISSUE TITLE
RED robot framework

### ISSUE THREAD

**Issue by parul001** [nokia/RED#176]
hello
i am trying to import a custom java library but its showing error Status: not added to project configuration .
in order to add library i am making a public class with public methods exporting it to a jar and then adding it to red .xml as java library. i am also defining path to jar file in Classpath field of red.xml.
please help i got stuck here . my configuration is :
Robotframework with jython version :3.0.2
Editor : RED
thanks
Parul Bhargava

**Comment by adam-wypych** [comment]
There is few possibilities to use Robot Framework with Java:
a) maven plugin
b) Jython installed with Robot Framework
c) standalone distribution (jar)

Which of them are you using?

**Comment by parul001** [comment]
Option B
I am using Jython installed with Robot Fremwork

**Comment by modrz** [comment]
Hi,

Do you follow robot user guide topic about [creating test libraries](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#creating-test-libraries)?
I checked RED 0.8.0 and managed to import sample library from robot documentation.
![image](https://user-images.githubusercontent.com/22540835/35328772-c1ce1414-00fd-11e8-9743-db4256eac988.png)

If you stil have problems can you provide source code for library you want to import?

**Comment by adam-wypych** [comment]
if you have class inside package you need to add package name as well to library import or just create class without package which extends class with keywords. You can use SwingLibrary project as an example - [https://github.com/robotframework/SwingLibrary/tree/master/src/main/java](url)

**Comment by parul001** [comment]
hello,
when i run my robot tests its showing this error 
Unable to Launch robot .
![untitled](https://user-images.githubusercontent.com/20571722/35844678-aebbd3a2-0b34-11e8-9150-cef07040e4f1.png)

**Comment by adam-wypych** [comment]
hello,

Are you able to start problematic suite from command line?

BR,
-Adam.

**Comment by parul001** [comment]
hello,
i am able to start suite from command line by both jybot and robot command  . but when i run this test through RED ide  it is showing me the error .
please help me in setting ide's  Run Configuration for robot framework with jython installed .Please note Python 3 is also installed , are these conflicting among themselves ?
BR,
parul

**Comment by KrzysztofJozefowicz** [comment]
can you share screenshot from launch configuration?

**Comment by adam-wypych** [comment]
Please attach console log - it should contains an information what is the root cause of the error.

BR,
-Adam.

**Comment by parul001** [comment]
hi,
Command: C:\jython2.7.0\bin\jython.exe -J-Dpython.path=C:\jython2.7.0\Lib\site-packages -J-cp .;C:\Users\parulb\Desktop\Beach.jar -m robot.run --listener C:\Users\parulb\AppData\Local\Temp\RobotTempDir2551060582504992487\TestRunnerAgent.py:49604 --argumentfile C:\Users\parulb\AppData\Local\Temp\RobotTempDir2551060582504992487\args_3526f9e4.arg C:\Users\parulb\eclipse-robotframeworknew\robotlogin
Suite Executor: Robot Framework 3.0.2 (Jython 2.7.0 on java1.8.0_131)
==============================================================================
Robotlogin                                                                    
==============================================================================
Robotlogin.Samplesuite                                                        
==============================================================================
testcase1                                                             | FAIL |
OSError: Cannot run program "chromedriver" (in directory "C:\Users\parulb\eclipse-robotframeworknew\robotlogin"): CreateProcess error=2, The system cannot find the file specified
------------------------------------------------------------------------------
Robotlogin.Samplesuite                                                | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Robotlogin                                                            | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  C:\Users\parulb\eclipse-robotframeworknew\robotlogin\output.xml
Log:     C:\Users\parulb\eclipse-robotframeworknew\robotlogin\log.html
Report:  C:\Users\parulb\eclipse-robotframeworknew\robotlogin\report.html
this is my console log above
n below is my code i just want to open browser but its not happening
![untitled](https://user-images.githubusercontent.com/20571722/35849323-3ada72a0-0b47-11e8-9647-a7b3abb133c4.png)

**Comment by parul001** [comment]
please note that my chromedriver.exe is present in that given path in code .but dont know why error is showing cant find the file specified.:(

**Comment by parul001** [comment]
hi,
 i tried to add path to referenced libraries tab but its not taking .exe extensions as it only takes libraries that contains classes.

**Comment by adam-wypych** [comment]
ok, I think I miss sth - the errors says that 

> OSError: Cannot run program "chromedriver" (in directory "C:\Users\parulb\eclipse-robotframeworknew\robotlogin"): CreateProcess error=2, The system cannot find the file specified
so I think its try to find chromedriver in this directory. Could you put temporary chromedriver.exe to this directory and then if it works just check if your Setup keywrods do not point to this directory?

**Comment by adam-wypych** [comment]
Please put chromedriver.exe to C:\Users\parulb\eclipse-robotframeworknew\robotlogin and run RF via RED.

**Comment by joanna-may** [comment]
Hi,

I run the same script as yours and I have the same error. Somehow jython doesn't see variable: webdriver.chrome.driver. The same error is shown when I run test from command line so this is not problem with RED.

There are 2 solutions that I found:
1.  add this path for chromedriver to PATH  or
2.  run chrome by other command:

Create Webdriver  Chrome   executable_path=c:/selenium_drivers/chromedriver.exe     
    go to   https://www.google.com

**Comment by adam-wypych** [comment]
here you have the answer why it is not working - for Java you need to set Java system property - https://stackoverflow.com/questions/28537290/how-to-set-path-chrome-driver-in-robot-framework .
