### ISSUE TITLE
Question: Support for TODO / Tasks?

### ISSUE THREAD

**Issue by maxweissboeck** [nokia/RED#177]
Is there any support for the Eclipse TODO / Tasks view planned?
This is a very handy feature that we are missing...

Thanks, Max

**Comment by KrzysztofJozefowicz** [comment]
Not for now but we may think about it.  We will discuss how it should be handled in Source and Tables editors and update this issue afterwards.

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.4
