### ISSUE TITLE
Is there anyway to disable RED functions in no-robot projects?

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#178]
I have 2 type projects in my eclipse, tcl and robot.
In old version(eclipse 4.5/RED 8.0), both 2 type projects works well.

In eclipse 4.7 with RED 0.8.2, when I click the run button in tcl project with a .tcl file, some times it will run as robot file and report an error.

Is there anyway to disable all RED functions in tcl project/script files?

**Comment by michalanglart** [comment]
Basically RED functions should be only active for projects which have "Robot nature". This can be checked in .project file. If you see an entry like this:

```
<nature>org.robotframework.ide.eclipse.main.plugin.robotNature</nature>
```

then it means the projects has Robot nature. You may remove it manually, or by opening context menu on selected project and choosing `Robot Framework -> Deconfigure as Robot Project`

If your project has no Robot nature then this looks like some bug.
