### ISSUE TITLE
Sync of RFLint settings

### ISSUE THREAD

**Issue by SCHLUPP42** [nokia/RED#180]
Right now we are searching for a proper way to roll out these settings for new team members and to keep the settings in sync inside the team.

My first thought was to keep the settings in git and sync them via script with the settings of each individual developer. But I could not find their location. Where do rflint settings, which are displayed in the preferences, get saved?

My second thought was to ask the RED developers to integrate such a feature ;o)
- dynamically read settings from external file on startup (file needs to be configured via import button,
ideally with extra reload button)

**Comment by KrzysztofJozefowicz** [comment]
Hi
I  thing your case may be already possible in RED although with different approach than above.
When RED runs rflint, it uses rflint rules defined in Preferences (Window->Preferences->Robot Framework-> Errors/Warnings ->Rflint validation:
![image 1](https://user-images.githubusercontent.com/3999733/36031208-3f644bce-0daa-11e8-9482-4cf214761494.png)
By default there are no rules defined in this place so rflint own default ones.
User can either create rules by themself or include rule file in Additional rules files. 
Using [rules files](https://github.com/boakley/robotframework-lint/wiki), you can define rules to be used by all team members.
In this case,everyone would have to add rule file to Preferences. 

Preferences can be exported/imported by File -> Export/Import menus - Export creates .epf (text based file with preferences)

Unfortunately, rflint rules files have absolute paths so this has to be taken into account (simple script to change paths in epf file for rule files should do the trick in most cases.).

**Comment by KrzysztofJozefowicz** [comment]
Anne requested use of env variables to be recognised in commands in RED #184, this could be extended to allow to define path to rule files using env parameters which could be more convenient than using absolute paths.

**Comment by SCHLUPP42** [comment]
Your hint with the .epf files should do the trick. I will investigate that further. Thanks.
