### ISSUE TITLE
Prefilled RFLint settings

### ISSUE THREAD

**Issue by SCHLUPP42** [nokia/RED#181]
Right now I have to manually add all the rules names to configure them.

It would be nice if the configuration panel for rules would show all the rules I have in stock. This includes the predefined rules which come with RFLint and the ones added via additional files.
If I add an additional rules file it should add all the new rules from the file to the configuration panel.
If I delete an additional rules file it should also delete the rules from the file in the configuration panel.

**Comment by KrzysztofJozefowicz** [comment]
We will add a command line field to rflint Preferences to allow to past field configurations via parameters or argument files. I am against populating rule list from rflint defaults and rule files as it will clutter this view. It would be easier to store long list of rule settings in separate file.

**Comment by SCHLUPP42** [comment]
I want to use this panel to get an overview of all rules which get applied by rflint analysis. If it only shows a few selfadded rules an I still have to dig into the rules files themselves it misses some value in my opinion.

**Comment by michalanglart** [comment]
RfLint integration have been enhanced in 0.8.13. For more info please see help topic: http://nokia.github.io/RED/help/user_guide/tools_integration/rflint.html
