### ISSUE TITLE
Referenced Library reload

### ISSUE THREAD

**Issue by SCHLUPP42** [nokia/RED#182]
It would be nice to have an option to reload all libraries via reload on the "Robot Referenced libraries" node and it would be nice to trigger the reload (depending on the selected node) via key f5 or something similar.

**Comment by KrzysztofJozefowicz** [comment]
There is right click menu on libraries (one or multiselect) to reload library after the file change.
Also reload can be triggered after file change (in case of libs inside Project) - setting in red.xml.

**Comment by SCHLUPP42** [comment]
Damn me,  I did not think of multiselect. Thanks for the enlightment ;)

As for the red.xml parameter 'isReferencedLibrariesAutoReloadEnabled': I have it enabled, but the autoreload was not triggered, as the file got edited outside the project. Is the fact that ist was edited outside the problem? I am going to reproduce this asap.

**Comment by KrzysztofJozefowicz** [comment]
Library refresh works both when lib is in workspace and outside of it.  Do you have enabled (default setting) Project menu -> Build Automatically  and in red.xml under General : Automatically reload changed libraries?

**Comment by SCHLUPP42** [comment]
Sorry for the delay.
I tried to reproduce the behavior but it always worked well now. With that in mind, I am going to close this issue. Thank you for your support.
