### ISSUE TITLE
Support for Eclipse Environment variables in Robot Framework Run Arguments

### ISSUE THREAD

**Issue by kootstra** [nokia/RED#184]
When wanting to store the log files in a seperate directory with the corresponding attachments I have to use a seperate executor to do so. It would be nice if the standard Eclipse environment variables are also available in the Robot Framework Argument section.

**Comment by KrzysztofJozefowicz** [comment]
Hi Anne
We have similar case already high in the backlog - define a place (red.xml or preferences) to have a list of parameters with possible values, those parameters could be used in run/debug configuration to create command line, there could be also additional view to show what are the current values of parameters (for choices defined in red.xml/preferences). 
I don't see reasons to also not provide resolving of env variables as this is the similar case as above.
Apart from run/debug, this could be also used in command line argument for rflint (at least for rule files).

**Comment by michalanglart** [comment]
fixed in 0.8.5
