### ISSUE TITLE
Double click can not select whole keyword with spaces.

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#186]
In source view, when I click a keyword, it will be highlight.And if I double click it,the keyword will be selected.
But, if the keyword includes space or Chinese chars, it can not be fully selected, only one word will be selected.

**Comment by KrzysztofJozefowicz** [comment]
right, double click selects part delimited by space,I would propose triple click to select whole keywords with spaces inside.  Now triple click selects whole line. 
I assume this is useful for removing whole keyword,no it is tedious to select keyword with space by hand/mouse

**Comment by Pantyhose-S** [comment]
HI, is there any plan that this problem will be fixed?

**Comment by Pantyhose-S** [comment]
HI, is there any plan that this problem will be fixed?

**Comment by michalanglart** [comment]
Fixed in 0.8.11
