### ISSUE TITLE
Libraries which class name is different than module name cannot be discovered any more.

### ISSUE THREAD

**Issue by Mario-P** [nokia/RED#188]
I've just upgraded Eclipse to Oxygen and realised that QickFix stopped working. See attached project and screen with error. There is no issue (with library3) when auto discover is done. It was working fine on Eclipse Neon+RED 0.8.0.

Project - [RED_Tests.zip](https://github.com/nokia/RED/files/1774589/RED_Tests.zip)
QuickFix error:
![quickfixerror](https://user-images.githubusercontent.com/22638505/36893858-e531ad8e-1e09-11e8-8efa-317bd0169ad5.JPG)

Auto Discover works fine:
![autodiscover](https://user-images.githubusercontent.com/22638505/36893993-4eb359e2-1e0a-11e8-8593-5e2dffbf8ace.JPG)

**Comment by KrzysztofJozefowicz** [comment]
released in RED 0.8.4
