### ISSUE TITLE
Editing from the grid not apply the changes.

### ISSUE THREAD

**Issue by jrvilda** [nokia/RED#19]
When you edit, add or remove variables of a keyword from the tab "Keyword", the change is not applied after saving.

**Comment by michalanglart** [comment]
Hello,


this is known issue. It has highest priority and we are working on it currently. It is mentioned in release note: https://github.com/nokia/RED/releases/tag/0.6.4 - in section Known Issues:

> Table editors edits are not persistent, changes done in Table editors will not be visible in source nor saved to file. Sync is done from Source -> Table only.

Next section states that tables persistency is in short term plan. 

Upcoming releases should gradually improve tables and they should start working and then get better.
