### ISSUE TITLE
"generating libdoc for Selenium2Library" blocks RED

### ISSUE THREAD

**Issue by NicolasHEnssat** [nokia/RED#193]
Hello!
I'm having some troubles with the configuration (?) : 
Whenever I start a test case, the pop-up below shows and does nothing. I can't cancel, I can't close, I have to kill RED with the task manager (I tried to wait 1 hour, nothing more happened).
![generating_libdoc](https://user-images.githubusercontent.com/35795421/37704942-af9df1f0-2cfa-11e8-82ce-bd33a3ae031d.PNG)

I tried several things, like re-installing RED, modifying the red.xml, creating a whole new project in a new worspace, importing a working project. I tried to change the version of Python, the version of Java too, I tried to make the simplest test possible (open a page on firefox).
Sometimes, when I modify my red.xml, this message shows as well.

I'm new to this, may be I didn't configure something well? 
The tests do work but after every execution I have to kill RED , and then open it again...

Can someone help me please?
Thank you in advance!

Nicolas

**Comment by michalanglart** [comment]
Hi,

please provide us with information about your environment: OS, version of RED, version of Robot Framework/Python/Java could also be helpful.

It would be also great if you could attach the simplest project you've mentioned on which you're experiencing this issue.

**Comment by KrzysztofJozefowicz** [comment]
Using latest RED 0.8.4 ,with python 2.7 and pyt3.6 and robotframework-seleniumlibrary-3.1.1, I was able to import SeleniumLibrary by import in resource/suite: `Library    Selenium2Library` and by selecting __init__.py from Selenium2Library from respective python's site-packages folder.

Please share relevant info as @michalanglart suggested.

**Comment by NicolasHEnssat** [comment]
Yes of course, sorry I forgot to do that.
OS : Widows 7 entreprise SP1
RED : 0.8.3 and then 0.8.4
Python : 2.7.14
Java (jre) : 1.8

And here is the project (this is an exercise to begin with robotframework and Selenium)
[OpenBrowser.zip](https://github.com/nokia/RED/files/1833376/OpenBrowser.zip)

In this project, here is basically what I have : 

![test](https://user-images.githubusercontent.com/35795421/37712310-c48832b0-2d13-11e8-8176-a19b487775d9.PNG)
![functions](https://user-images.githubusercontent.com/35795421/37712314-c6fbcf84-2d13-11e8-83f1-97c0a2882464.PNG)

The 2 other files are still empty. I changed the red.xml : I imported the selenium2library from the Python directory.

I forgot to say that apparently, this happens when I use the "wait until element is visible"
(Functions_OpenFirefox -> line 7), mays be I made a mistake during the importation of the library?

**Comment by KrzysztofJozefowicz** [comment]
Autodiscovery is not connected anyhow with testcase body,autodiscovery is triggered on library imports 
(with default settings,it will try to discover libs even without Keywords or Testcase parts.
What is in Robot Referenced libraries? There should be libdoc generated as validation does not underlines Selenium2Library, 
If you may, please include .log file from .metadata folder of your workspace - .log stores all Eclipse/RED logs which may tell us something. For now I don't see anything suspicious.   
Summarise, in some instances, Selenium2Library libdoc generation is stuck,right? What happens when you expand Robot Referenced Libraries,right click on Selenium2Library and do "reload"?

**Comment by NicolasHEnssat** [comment]
Here is what I have in the Robot Referenced Libraries : 
![robotreferencedlib](https://user-images.githubusercontent.com/35795421/37713849-6419aa58-2d18-11e8-83e5-e08caf364316.PNG)

And here is the last session of the .log : 
[log.txt](https://github.com/nokia/RED/files/1833532/log.txt)

I put the full version too, but I deleted a project, and RED tried to open the opened tab, so there are some errors related to the ThisIsATest project : 
[log-full.zip](https://github.com/nokia/RED/files/1833552/log-full.zip)

The libdoc generation is indeed stuck. 
When I reloaded the Selenium2Library, it just did the same. This time 2 pop-up appreared (the same, but in double).

**Comment by KrzysztofJozefowicz** [comment]
Nothing strange in .logs apart from problems with proxy. As RED starts autodiscovery,it starts python server with discovery service and communicates to RED by random port on loopback. 
Lets check if this is related with port blocking on loopback by 3rd party application - in RED there is possibility to turn off server and force RED to ask about libs directly to robot&python without loopback.
 
In RED.ini or eclipse.ini (depending on installation) file,add following in the part with -vmargs where memory allocation is defined (snippet is from RED.ini from default installation):
```
-vmargs
-Xms512m
-Xmx2g
-Dred.useDirectInterpreter=true
```
Close and reopen RED, enter red.xml under tab Referenced Libraries remove Selenium2Library and do the discovery again.

**Comment by NicolasHEnssat** [comment]
Well, I did it, with auto-discovery and manual discovery, and with the "refresh (in Robot Referenced Libraries) but still the same problem.
From the 4 lines/args you gave above, I only had to add the last one, the 3 others were already written.

In the mean time, I tried to execute RED in as administrator, not better. 
Then I had another problem : RED told me that red.xml didn't exist. I tried to rename the project to add "[bug]" in the end, and to create another project after that, but a pop up said that the project was "out of sync with file system".

![failrename](https://user-images.githubusercontent.com/35795421/37777247-59c4f48e-2de7-11e8-98fe-c671bff0f7af.PNG)

I just give this as info, it may help, but this problem didn't happened again.
I'm going to try an istallation on an other windows, and on a Linux. I'll keep you updated.

**Comment by KrzysztofJozefowicz** [comment]
Quick note, if there is no red.xml in project, RED/eclipse somehow removed
'nature' of project (in other words project is not robót Type but
defalut/other). Right click on project, from Robot Framework select
Configure as Robot Project (if not visible use deconfigure and then
Configure). Do you have clean RED or does it have additional features
installed (as PyDev for instance)?

22.03.2018 15:46 "NicolasHEnssat" <notifications@github.com> napisał(a):

**Comment by NicolasHEnssat** [comment]
In theory, I have a clean RED. I installed the latest version and nothing more (appart from the project configurations...).
I deconfigured/re-configured, and this is what happened : 

![building](https://user-images.githubusercontent.com/35795421/37780170-7c5c577e-2dee-11e8-9810-c2a1d55fc35d.PNG)

I already tried to fix this, but I didn't manage to.

**Comment by KrzysztofJozefowicz** [comment]
There is something critically wrong, I don't know what but RED does not produces such errors on our machines (local laptops winth Win7, VM with Win2008 and RH7). 
Try on other hosts and let us know if you can reproduce your issues.

**Comment by NicolasHEnssat** [comment]
Hello!
This issue seems to be fixed now!
I created my project in a directory where I have admin rights. I installed my dependencies (jre, python, etc...) there too, but RED didn't like it.
So I (well, not alone) ended up creating a virtualenv with python in the workspace. 
Everything is working well now, apparently I didn't have all the admin rights . . .

Thank you very much for your support, and implication :D

**Comment by KrzysztofJozefowicz** [comment]
> I created my project in a directory where I have admin rights. I installed my dependencies (jre, python, etc...) there too, but RED didn't like it.
Thanks for feedback! We will look into it,I will play around with different user rights under Windows to see what may be a problem here as RED does not need to have admin rights to wior.

Can you tell us what was the setup when RED did not work? 
- Java was installed for everybody or just for admin?
- Python - the same as above?
- Folder with workspace - it was lower permission level than admin, what about read/write access?

**Comment by NicolasHEnssat** [comment]
Well, everything was in the same directory (a big folder for everything that needs special rights), and in theory it makes me get read/write rights for everything in it. Apparently, windows has a certain way to manage the rights...?

As I am the only user of this computer, I install softwares only for me (admin) (like Python and Java), may be it comes from here, although I never had this kind of problem before...
