### ISSUE TITLE
The Perspective does not appear in eclipse oxygen

### ISSUE THREAD

**Issue by micsurin2** [nokia/RED#196]
Hi guys,

I started the installation from scratch to try ROBOT at home, but somehow after a successful RED installation Eclipse does not show the ROBOT perspective. 

Eclipse IDE for Java Developers

Version: Oxygen.3 Release (4.7.3)
Build id: 20180308-1800

RED - Robot Editor version 0.8.4
GitHub https://github.com/nokia/RED
Twitter @RED_RobotEditor
Update Site http://master.dl.sourceforge.net/project/red-robot-editor/repository

Did anyone met this problem?

Br,
Attila

**Comment by KrzysztofJozefowicz** [comment]
We have not such problems either on our regression builds or in my local PC (Win7, java 1.8, clean Eclipse Java IDE: eclipse-java-oxygen-3-win32-x86_64.zip,  Eclipse IDE for Java Developers	4.7.3.20180308-1800 RED installed from marketplace and from RED_Feature zip file). 
To make it clear - list of all perspectives are under _Window- >Perspective->Open Perspective -> Other_
 There was an issue with other problems from clean installation #193 but we are out of ideas what may interfere with Eclipse+RED to behave as in your case or in #193 .
What is your java version, do you have any antyvirus software?

**Comment by micsurin2** [comment]
I don't know what was the problem, but I reinstalled everything, included windows, and after that I installed Eclipse 32 bit instead of 64 and it works now. 
Thanks,
Fellow nokian from Budapest site

**Comment by KrzysztofJozefowicz** [comment]
Hi
thanks for feedback, I'm glad that you resolved it by yourself. In case of support in Nokia, you can contact us anytime via mail/chat as it is faster than answering on GH.
