### ISSUE TITLE
Test case level setting in view mode?

### ISSUE THREAD

**Issue by luisxiaomai** [nokia/RED#198]
Currently there is test suite level setting in view mode? Can you consider test case level setting in view mode?

**Comment by joanna-may** [comment]
Hi,
we are sorry but we missed somehow your question. Do you mean as a suite level setting in view mode the "Settings" tab in editor view? If yes then we have no plans to add this kind of view for Test cases. We have only in plans adding some more useful editor for Documentation settings for test case/keyword.

**Comment by michalanglart** [comment]
There is no plan to make test case/keyword settings editable in separate tab of editor (if that was desired functionality). I'm closing it
