### ISSUE TITLE
Errors when the Robot project is imported as General->File System (eclipse symlink)

### ISSUE THREAD

**Issue by dmskibba** [nokia/RED#2]
This is a new install.  When I view my source files in source mode, I get error : "Resource import 'include.txt' is invalid: file does not exist".  This file exists and is in the same folder as the source files. This error is the root cause of keyword reference errors because the location of the keywords was in the resource file. The tests run OK but hang if I attempt to run in debug mode.

I did not see any setup instructions regarding the specification of folders etc.

**Comment by adam-wypych** [comment]
Hello,

could you answer below questions and provide need files?

1. Which version of RED feature you are using?
2. Which Operating System you are using?
3. Which python interpreter you are using?
4. Can you attach your project zipped (please follow instruction http://agile.csc.ncsu.edu/SEMaterials/tutorials/import_export/index.html#section1_0 ):
5. Could you attach .log file from workspace directory?

**Comment by dmskibba** [comment]
Please see the attached document. 

Dan

**Comment by adam-wypych** [comment]
Hello,

I ass I see github do not support attaching any kind of document. Can you put it as text?

Best Regards,
-Adam.

**Comment by dmskibba** [comment]
Thank you for your prompt response. 




I could not send you the project because of non-disclosure issues and decided it would be simpler to reproduce the problem with non-proprietary information. 




I created a new Robot project referencing an existing empty directory as the project directory. I got the following error during the project creation: 




An internal error occurred during: "Validating". 

java.lang.NullPointerException 




I have no idea what caused the error. It created the .projects and red.xml files and the Robot Standard libraries show in the project explorer. 




RED Version: 	

1.0.0.201511040856 


Operating System: 	

Windows 8.1 Enterprise 
Python Interpreter: 2.7.8 (64 bit) 



My scaled-down project contained 2 files, with one referencing the other. 




The file with the reference flagged the reference as an error (file did not exist). I changed the reference to the fully qualified path and it then showed a warning and an error. The warning was about using a fully-qualified path. The error said the file was not in the workspace. 




Apparently, RED requires the project to be in the workspace. I was not in the habit of doing that because I am used to mapping an eclipse project on top of a snapshot view and wanted to minimize the number of non-artifact files in my view area. In any case, I removed the old project and created a new one inside the workspace. The file not found errors went away. 




Now the resource references show error “Given file is not a resource file”. The file has a .txt extension. Is the .robot extension required? 




I also hit two other issues. 




An internal error occurred during: Revalidating model:.GC overhead limit exceeded. 




An internal error occurred during: "Validating". java.lang.StackOverflowError 




1) I would like to run a single test in a suite. The only option I see is to right-click on the test name in the Project explorer and click the run icon. This runs the single test but there is no way to provide the command line options the way I can in a run configuration. Will there be future support for running single tests that incorporate command line options? 




Thanks 









----- Original Message -----

**Comment by adam-wypych** [comment]
Could you put here .log file content from workspace?

Thanks in advance.

**Comment by KrzysztofJozefowicz** [comment]
Hi
Resource issue may be the same as  #3 , you can check if it is the case by renaming the resource extension from .txt to .robot 
This will be fixed in upcoming release.

**Comment by dmskibba** [comment]
Since now is not a good time to rename a significant number of files, I will wait for the next release. Is their a notification process to which I can subscribe? 

Thank you for your efforts. The RED plugin will be a real godsend for us. 

Dan 


----- Original Message -----

**Comment by adam-wypych** [comment]
Will you be able to provide need data?

1) .log file content from the workspace
2) answer for questions:
    a) which Java version You are using?
    b) what Eclipse version You are using?
    c) what Robot Framework version You have installed?

Thanks in advance!

**Comment by dmskibba** [comment]
See attached document. 

----- Original Message -----

**Comment by adam-wypych** [comment]
Could you put .log file content here as it is? GitHub has problem with attached files different than pictures.

**Comment by KrzysztofJozefowicz** [comment]
As no response, I close this issue.
