### ISSUE TITLE
Install fails with: No repository found at http://master.dl.sourceforge.net/project/red-robot-editor/repository.

### ISSUE THREAD

**Issue by rjmarshall17** [nokia/RED#207]
I'm attempting to install RED via the Marketplace in both Eclipse Luna (4.4.2) and Oxygen (4.7.3a) and I'm getting the error:

No repository found at http://master.dl.sourceforge.net/project/red-robot-editor/repository.

**Comment by KrzysztofJozefowicz** [comment]
Hi
Repository is up and running (I was able to install RED from my PC via Marketplace and directly via repository), there is configuration case on your side.
Luna is not supported, you should stick to Oxygen.
Check network settings under Windows->Preferences -> General -> Network Connections

For direct install using sourceforge repo, go to Help -> Install New Software -> Add:
![red-1](https://user-images.githubusercontent.com/3999733/39691252-437b0636-51dd-11e8-8a54-6b946ff32dca.png)

**Comment by LuDur** [comment]
I have the same problem. Version: Oxygen.3 Release (4.7.3)
![snimek z 2018-05-17 07-53-20](https://user-images.githubusercontent.com/35295844/40159008-b0cdcf30-59a7-11e8-9695-ca1ad6f95c2d.png)

**Comment by michalanglart** [comment]
Hi,

I've checked that and I also have some issues connecting to update site. Before we figure out what is happening you may update RED by downloading feature zip: https://github.com/nokia/RED/releases/download/0.8.5/RED_feature_0.8.5.201805161001.zip and then in your eclipse installation:

Help -> Install New Software -> Add -> Archive

Select the zip file you've just downloaded and check new version. Proceed by clicking next until newest RED is installed.

**Comment by michalanglart** [comment]
I was however able to install RED using this link: http://sourceforge.net/projects/red-robot-editor/files/repository

Looks like something is down at sourceforge side.

**Comment by michalanglart** [comment]
Closing as there were no more complaints over marketplace installation.
