### ISSUE TITLE
argument file starting from home directory is not working

### ISSUE THREAD

**Issue by p74** [nokia/RED#208]
`- A ~/robotframeworktest/argumentfiles/bla.txt`

i need to set whole path

greetings Ruud

**Comment by michalanglart** [comment]
Hi,

in which place are you trying try to use this path?

**Comment by p74** [comment]
Hi.

In "Run Configurations" screen , tab "Robot" field,  "Arguments"

2018-05-18 12:38 GMT+02:00 michalanglart <notifications@github.com>:

**Comment by adam-wypych** [comment]
what is your operating system?

**Comment by p74** [comment]
Linux Ubuntu 17.10

Op vr 1 jun. 2018 09:31 schreef adam-wypych <notifications@github.com>:

**Comment by adam-wypych** [comment]
I think the problem is because `~` is resolved by shell and with the python is even more complicated (just see: https://stackoverflow.com/questions/11587343/difference-between-home-and-tilde ). Therefore please try to use '$HOME' instead of tilde.

**Comment by modrz** [comment]
Since RED 0.8.5 Eclipse string substitution variables are supported in run configuration text fields.
On linux you can replace tilde by:
`-A ${env_var:HOME}/robotframeworktest/argumentfiles/bla.txt`

**Comment by adam-wypych** [comment]
@p74 could you try suggestion from @modrz https://github.com/nokia/RED/issues/208#issuecomment-397284164

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.7
