### ISSUE TITLE
testtemplate: missing header when using testdata 

### ISSUE THREAD

**Issue by p74** [nokia/RED#209]
I am missing the header discription of the testdata when using a testdata template

source: 

*** settings ***
Test Template     MachineTest: Expect error

*** Test Cases ***    Test Description                                               Test           production 
                               a                                                                      b               c

When press tab: Test Cases
i am missing the header description of the table like Test Description    Test   production

**Comment by michalanglart** [comment]
Hi,

If I understand that correctly this is the same issue as in #100, isn't it?

**Comment by p74** [comment]
yes it is sorry for it

2018-05-18 12:37 GMT+02:00 michalanglart <notifications@github.com>:

**Comment by michalanglart** [comment]
No problem, we'll have a look at this one.

I'm closing it as a duplicate
