### ISSUE TITLE
Autodiscovery don't work for RemoteSwingLibrary in RED 0.8.5

### ISSUE THREAD

**Issue by adam-wypych** [nokia/RED#210]
Additional info: RED was unable to find class 'RemoteSwingLibrary' inside 'file:///C:/Python27/Lib/site-packages/remoteswinglibrary-2.2.1.jar/RemoteSwingLibrary.py' module.

I checked it a little bit more and the last working version is 0.8.2

**Comment by modrz** [comment]
Hi Adam,
The workaround for now is adding library manually by using **"Add java library"** option from red.xml

**Comment by modrz** [comment]
Fixed in 0.8.6
