### ISSUE TITLE
Does RED provides keyword refactoring support ?

### ISSUE THREAD

**Issue by gvasanka** [nokia/RED#211]
I have implemented page resource model with robot framework and looking on keyword refactoring support on IDE,
Basically my expectation is when i refactor some keyword, RED IDE should refactor all the related references. 
As i tried out refactoring wasn't working as per my expectation. 

So my question is does RED provides refactoring capabilities?

**Comment by KrzysztofJozefowicz** [comment]
Hi
RED currently does not provides "smart refactoring" thus does not update related references automatically. Current search/find references is based on simple pattern search.
We have refactoring functionality in our backlog but it is constantly delayed by other, more important issues.

**Comment by gvasanka** [comment]
Appreciate your quick response. Saved my time.

**Comment by adam-wypych** [comment]
connected to #25

**Comment by KrzysztofJozefowicz** [comment]
let me close this one, #25 can be used for tracking
