### ISSUE TITLE
Content Assist not working with Ctrl+Space

### ISSUE THREAD

**Issue by kootstra** [nokia/RED#213]
When working with RED in the standalone application as well as the Eclipse plugin the content assist feature is no longer working. When applying the suggestion in _Why some times auto complete won't work in source view?_  #122 I can see the content assist pop up automatically. 

However, when I remove the `abc..ABC..` string, and use <kbd>Ctrl+Space</kbd> then I don't get to see the same content assist window. This is the main issue.

I checked the Eclipse key bindings and there is a mapping for the <kbd>Ctrl+Space</kbd> and confirmed that there are no conflicts. 
> **Description**: Content Assist
> **Binding**: <kbd>Ctrl+Space</kbd>
> **When**: In Dialogs and Windows

Having content assist always on isn't always that convinient and then the key combination is preferred.

**Comment by michalanglart** [comment]
Hi,

have you tried setting different mapping and trying if it works?

We've also had this one: #118 and in particular the question I've linked to in one of comments:  https://superuser.com/questions/327479/ctrl-space-always-toggles-chinese-ime-windows-7 Please have a look if this is helpful.

**Comment by KrzysztofJozefowicz** [comment]
@kootstra Hi Anne, were you able to fix it?

**Comment by michalanglart** [comment]
> As I no longer have access to that setup I'm unable to replicate or help with this problem

Closing then
