### ISSUE TITLE
Java library not-accessible

### ISSUE THREAD

**Issue by rumensoft** [nokia/RED#215]
Hi,

I added Executable jar file and there is error - Java library not-accessible.
I have this .jar in CLASSPATH. I'm using latest version of RED.
![rf](https://user-images.githubusercontent.com/39481469/40658543-47bb1d84-6354-11e8-857e-3533810f9dd6.png)

When I try to Reload the library, there is error:

> Library specification generation problem
Problem occurred during generating libdoc for 'com.keywords.Sikuli' library located at C:\lib\RFKeywords.jar.
RED python session problem. Following exception has been thrown by python service:
            Building library 'com.keywords.Sikuli' failed: NoClassDefFoundError: org/sikuli/script/FindFailed    
            Try --help for usage information.
            Traceback (most recent call last):
              File "C:\Users\*\AppData\Local\Temp\RobotTempDir912894619825912105\red_libraries.py", line 74, in <module>
                print(create_libdoc(libname, format))
              File "C:\Users\*\AppData\Local\Temp\RobotTempDir912894619825912105\red_libraries.py", line 37, in create_libdoc
                raise Exception('Unable to generate library specification file for library: \'' + libname + '\'')
            Exception: Unable to generate library specification file for library: 'com.keywords.Sikuli'

RF version: 3.0.4
Thank you.

**Comment by adam-wypych** [comment]
From the error message it seems that you are missing dependencies to sikuli `Building library 'com.keywords.Sikuli' failed: NoClassDefFoundError: org/sikuli/script/FindFailed`. You can either add classpath dependencies to RED.xml or if you are using maven just use shade plugin to include all other dependencies in RFKeywords.jar

**Comment by rumensoft** [comment]
Hi, thank you for the answer. After you response, I found that, I extracted the executable jar in wrong way. The library was in .jar file in the .jar file and there was no access. So, when I extracting the .jar file, I selected "Extract required libraries into generated JAR" and now the library is correct imported in RED.

Thank you!  :+1:
