### ISSUE TITLE
Imported existing source, doesn't validate correctly

### ISSUE THREAD

**Issue by rumensoft** [nokia/RED#216]
Hi,
I have latest version of RED and I checkout source code form SVN. Till now, I didn't use RED plugin for RobotFramework and there are no validation of keywords, variables and so on. Everything on SVN works, but when I download and start to work with RED plugin, all the variables and comment are in red.
![red_errors 1](https://user-images.githubusercontent.com/39481469/40659172-2627a064-6356-11e8-8737-0fdc782d19a6.png)
![red_errors 2](https://user-images.githubusercontent.com/39481469/40659173-26486f7e-6356-11e8-8119-14ba69717761.png)
![red_errors 3](https://user-images.githubusercontent.com/39481469/40659174-2678d04c-6356-11e8-8f1e-ae83538b5c18.png)

Why this is happen?

Thank you

**Comment by KrzysztofJozefowicz** [comment]
can you make a screenshot of Project Explorer so we could see if Project is properly configured?

**Comment by rumensoft** [comment]
Project Explorer, you mean this?
![pe](https://user-images.githubusercontent.com/39481469/40659525-34cac0dc-6357-11e8-898e-24f01bb454bd.png)

**Comment by KrzysztofJozefowicz** [comment]
hmm, case is that there is no place in RED sources where validation returns "Variable must end with }".  Error  is similar to https://github.com/NitorCreations/RobotFramework-EclipseIDE/issues/47 

I would propose to download RED Product (zips starting with RED_0.8.5.*.zip) from : https://github.com/nokia/RED/releases and open workspace from it.

**Comment by rumensoft** [comment]
Hmm, I'm not sure if I understand you. OK, I downloaded the zip file, but I should create project in the workspace?

**Comment by KrzysztofJozefowicz** [comment]
Hi, unzip RED product, start it and select workspace which you already have (the one from screenshots).

**Comment by rumensoft** [comment]
Alright, now there are no errors with RED Editor. Maybe I should use it, is faster and based on Eclipse.

Thanks
