### ISSUE TITLE
Code coloring when a kw as a kw as arg

### ISSUE THREAD

**Issue by KikitheKing** [nokia/RED#221]
Hi RED Team !

Before using RED, i was using Eclipse + robotide for code coloring.
Your code coloring is good but there is only one thing i don't like, it's about kw with kw as argument.

For example in robotide:
![robotide](https://user-images.githubusercontent.com/39904817/40913730-c8fe47e0-67f5-11e8-9a2d-939304e10d84.PNG)

The same thing in RED:
![red](https://user-images.githubusercontent.com/39904817/40913741-d405796a-67f5-11e8-98c2-a4127c37b621.PNG)

I don't know if you can plan to add an option to change this but i will appreciate !

**Comment by adam-wypych** [comment]
This issue is related to #28 . RED hasn't any special table of keywords, which takes as arguments a keyword name and its arguments.

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.7
