### ISSUE TITLE
Use PYTHONPATH to search for resources / variables files / libraries

### ISSUE THREAD

**Issue by Biiosense** [nokia/RED#226]
Hey

Like the RobotFramework does (http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#module-search-path)
, it would be great to have RED to search for resources, libraries and variables files in the PYTHONPATH variable.

**Comment by michalanglart** [comment]
Hi,

RED supports it for quite a long time already (a year or so??).

If you have an example in which it does not work please share it, maybe there is some bug there...

**Comment by Biiosense** [comment]
I was using RED v0.6. Now I upgraded to v0.8.
However, I can't find the pythonpath field anymore in the red.xml, and the documentation isn't up-to-date with the new interface.

**Comment by michalanglart** [comment]
You've upgraded to 0.8.0 or 0.8.5?

The field for augmenting PYTHONPATH is still there at Referenced Library path.

Can you you please point a place which is not up to date?

**Comment by Biiosense** [comment]
Oh ! And your plugin is freaking amazing ! :D
Thank you for your good work and for being active !
