### ISSUE TITLE
Integer as default values are considered as variables in keyword arguments definition

### ISSUE THREAD

**Issue by Biiosense** [nokia/RED#229]
In a resource file, when defining the default value of an argument, an integer value put inside brackets (`${0}`) is considered as a variable and then it raises an error : "Variable '${0}' is used, but not defined".

Example : 
`My keyword`
`[Arguments]`  `${timer}=${0}`

**Comment by joanna-may** [comment]
Hi,
you are right this is a bug. Probably we will correct it in next release.

**Comment by adam-wypych** [comment]
It seems that `VariableType` is ignored - https://github.com/nokia/RED/blob/master/src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/main/java/org/rf/ide/core/testdata/model/table/exec/descs/ast/mapping/VariableDeclaration.java .

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.7
