### ISSUE TITLE
[MAC] RED always point to pre-installed Python app by apple 

### ISSUE THREAD

**Issue by learningandworking** [nokia/RED#230]
Hi all,

 I am using RED interacting to python installed by Pyenv (/Users/username/.pyenv/shims/python). But when I map it with the Python, it always detect the default python on MAC OS /usr/bin. On the Preference > Robot > Installed framework: it just have "Discover" button which always point to "/usr/bin/python", and dont have the place to type the path.

Note: /.pyenv is not visible on the MAC if we use the ADD button 

which python
`/Users/username/.pyenv/shims/python`

whereis python
`/usr/bin/python`

~/.bash_profile
```
export JAVA_HOME=$(/usr/libexec/java_home)
export PATH=$PATH:$M2_HOME/bin
export ANDROID_HOME=/Users/username/Library/Android/sdk
export PATH=${JAVA_HOME}/bin:$PATH

#PYENV
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```
Anyone encounters this issue before, could you please share your ideas or work-around how to fix it

**Comment by modrz** [comment]
Hi,

Have you tried selecting "Show Hidden Files" option in directory selection dialog context menu?
![image](https://user-images.githubusercontent.com/22540835/41892332-f7ce240e-7917-11e8-9cd5-7da266a5880c.png)


It works on linux, I am not sure about MAC OS.

You can also try "AppleShowAllFiles" preference described in https://bugs.eclipse.org/bugs/show_bug.cgi?id=109353

**Comment by modrz** [comment]
Actually problems looks the same like #202

**Comment by learningandworking** [comment]
@modrz : 
1. I configured MAC to display all hidden folders. 
=> Open Finder > check the hidden folders displaying as expected.
2. Use Eclipse , Preference > Robot framework > Installed framework. Click Add button, cannot find the hidden folders (/usr/local/ or even in the $HOME folder )

**Comment by modrz** [comment]
Have you enabled hidden files showing in dialog that is opened after selecting Add button in Preference > Robot framework > Installed framework, or somewhere else in system?
Directory and file selection dialogs  are system specific. 
I don't have MAC to check it myself, only verified it on Linux.

**Comment by learningandworking** [comment]
@modrz : I enabled all hidden folders/files can be see on MAC, but from Eclipse it cannot
