### ISSUE TITLE
Argument names of a keyword can be used as variables

### ISSUE THREAD

**Issue by Biiosense** [nokia/RED#232]
When you call a keyword that expects mandatory arguments, you can use the name of those arguments as variable that doesn't exist in this context. 

Exemple : 
[Keyword definition]
`My keyword`
`[Arguments]`  `${my_arg}`
`No Operation`

[Keyword call]
`My keyword`   `${my_arg}`
Without declaring variable `${my_arg}` in my test, it is recognized as a variable (highlighted) and doesn't raised an error "Variable used but not declared."

**Comment by joanna-may** [comment]
Hi,
in the similar case I have markers on keyword call (checked in in newer version 0.8.6):
![args](https://user-images.githubusercontent.com/15103418/41975407-e2e7a0e8-7a1a-11e8-8424-7e3d6f319d69.PNG)

Do you have something more in your test?

**Comment by joanna-may** [comment]
So you have something similar to this:
![args](https://user-images.githubusercontent.com/15103418/41978315-df5bbf34-7a21-11e8-8712-b769e678a65d.PNG)

Naming in Robot can be tricky :)

**Comment by Biiosense** [comment]
Exactly ! 
Yes, I find this feature a bit confusing ..
