### ISSUE TITLE
Oxygen.3a Release (4.7.3a) RED-0.8.6 PyDev-6.4.3 pydevd-1.3.2 debug with pydev not working

### ISSUE THREAD

**Issue by rayjiang2013** [nokia/RED#234]
I have followed exactly as http://nokia.github.io/RED/help/user_guide/launching/debug/robot_python_debug.html 

$ pip list | grep pydevd
pydevd                             1.3.2  
<img width="635" alt="screen shot 2018-07-22 at 4 16 37 pm" src="https://user-images.githubusercontent.com/12944134/43051190-bb36315e-8dca-11e8-8ea8-1b461e2c0d7d.png">
<img width="631" alt="screen shot 2018-07-22 at 4 15 49 pm" src="https://user-images.githubusercontent.com/12944134/43051191-bb4e3736-8dca-11e8-81b8-927b52cf063f.png">
<img width="623" alt="screen shot 2018-07-22 at 4 15 44 pm" src="https://user-images.githubusercontent.com/12944134/43051192-bb657b58-8dca-11e8-93e6-46f1aaff483f.png">
[
<img width="429" alt="screen shot 2018-07-22 at 4 22 13 pm" src="https://user-images.githubusercontent.com/12944134/43051227-864fcd28-8dcb-11e8-8f9f-f7105b7de75b.png">
](url)

When debugging, i always get below: it was only able to step into robot file but not into python library
<img width="1434" alt="screen shot 2018-07-22 at 4 08 04 pm" src="https://user-images.githubusercontent.com/12944134/43051193-bb7e49e4-8dca-11e8-8d05-9160f1bdd351.png">

Also I was using the https://github.com/robotframework/QuickStartGuide/blob/master/QuickStart.rst to try this

I was able to "hack" it to work by using "attach to process" in PyDev, but has to do this every time starting a debug session is really annoying...

Can someone please help?

**Comment by michalanglart** [comment]
Hi,

please have a look here #227 There are some changes in `runPyDevDebug.py` script which will be released with next RED version. You may however manually change the file as described in #227.

Let us know if that helps

**Comment by rayjiang2013** [comment]
@michalanglart Thanks for the quick feedback! 

I have tried that, unfortunately, did not work...

**Comment by rayjiang2013** [comment]
@michalanglart Any other suggestions?

**Comment by michalanglart** [comment]
As noted previously in next release we're going to provide `runPyDevDebug.py` script with couple of changes (a bit more than those described in #227). 

We originally planned to release next version this week, but I'm not sure if it's going to happen today - monday seems more probable.

This is how the script will look like in next version. Please try using it:

```python
import os
import sys
import subprocess
import inspect


def run_process(command):
    p = subprocess.Popen(command, stdout=subprocess.PIPE)

    while True:
        nextline = p.stdout.readline() if sys.version_info < (3, 0, 0) else str(p.stdout.readline(), 'utf-8')
        if not nextline and p.poll() is not None:
            break
        sys.stdout.write(nextline)
        sys.stdout.flush()


def find_robot_run_path(custom_path):
    try:
        # try to get path from local Python interpreter
        import robot
        path = os.path.join(os.path.dirname(inspect.getfile(robot)), 'run.py')
    except:
        # if not found use user defined
        path = custom_path

    if not os.path.isfile(path):
        raise RuntimeError('"%s" does not point to an existing file' % (path))

    return path


def find_pydevd_path(custom_path):
    try:
        # try to get path from local Python interpreter
        import pydevd
        path = os.path.join(os.path.dirname(inspect.getfile(pydevd)), 'pydevd.py')
    except:
        # if not found use user defined
        path = custom_path

    if not os.path.isfile(path):
        raise RuntimeError('"%s" does not point to an existing file' % (path))

    return path


def run_local_python_debug(pydevd_ip, pydevd_port, pydevd_path, robot_run_path):
    pydevd_args = ['--multiprocess', '--print-in-debugger-startup', '--vm_type', 'python',
                   '--client', pydevd_ip, '--port', pydevd_port, '--file', find_robot_run_path(robot_run_path)]
    robot_run_args = sys.argv[sys.argv.index('robot.run') + 1:]

    command = [sys.executable, '-u', find_pydevd_path(pydevd_path)] + pydevd_args + robot_run_args

    print('Running command: ' + ' '.join(command))
    run_process(command)


if __name__ == '__main__':

    pydevd_ip = '127.0.0.1'
    pydevd_port = '5678'
    pydevd_path = 'change this to reflect to pydevd.py file, check your local Eclipse/Red with installed PyDev <eclipse_or_RED_with_PyDev>/plugins/org.python.pydev/pysrc/pydevd.py'
    robot_run_path = 'change this to reflect to run.py file, for example C:/Python36/Lib/site-packages/robot/run.py'

    run_local_python_debug(pydevd_ip, pydevd_port, pydevd_path, robot_run_path)
```

**Comment by michalanglart** [comment]
By the way:

The message you're seeing which you've shown in first comment is ok. This happens because RED debugger only operates on robot sources level  but it is unable to follow the execution in python code below the keywords. When debugging with RED & PyDev you have in fact two sessions: one from RED which is able to perform stepping in robot sources and second from PyDev which is able to do the stepping in python sources.

**Comment by KrzysztofJozefowicz** [comment]
@rayjiang2013 - can you check newest release 0.8.7 and confirm if your issue is fixed?

**Comment by michalanglart** [comment]
No confirmation till today so I'm assuming it's fixed. Closing
