### ISSUE TITLE
Getting [Errno 10061] No connection could be made because the target machine actively refused it> error while executing RF code

### ISSUE THREAD

**Issue by Paramashiva** [nokia/RED#235]
I'm executing a robot framework script in Windows 10 machine and I'm getting a error : "**Getting [Errno 10061] No connection could be made because the target machine actively refused it>** error while executing RF code ". Not even the browser is getting opened. Can anyone help me out!!!

**Comment by joanna-may** [comment]
Hi,
are you running test from RED? What kind of test it is (Selenium, socket)? Do you have more logs?

**Comment by Paramashiva** [comment]
I'm running it from RED. It is a selenium kind of test. No more are available instead I'm getting this error message ""Getting [Errno 10061] No connection could be made because the target machine actively refused it>"

**Comment by adam-wypych** [comment]
Can you check firewall? Connection actively refused sounds like the problem with network configuration.

**Comment by joanna-may** [comment]
This is not related to RED. Please check if HTTP_PROXY/NO_PROXY variable is required or graphical environment is configured. This can be problem with selenium driver. Check geckodriver.log too if there are any information.

**Comment by Paramashiva** [comment]
I tried with chrome driver and it is working fine but I have an issue with IE browser

**Comment by Paramashiva** [comment]
@adam-wypych I checked with the firewall also and I had provided the firewall access .

**Comment by Paramashiva** [comment]
I tried with command line also, I'm getting the same error.

**Comment by Paramashiva** [comment]
I tried this code "Set Environment Variable     no_proxy     127.0.0.1" before the open browser statement. Now I'm able to launch the URL and hit the URL. But I don't know the meaning of this code.

**Comment by adam-wypych** [comment]
Ok, so basically it is not the problem with RED at all. If you setting NO_PROXY it means that all connection pointing to your machine will not hit proxy at all ( https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html ).
