### ISSUE TITLE
Agent connection server:  Port value out of range: -1

### ISSUE THREAD

**Issue by wywincl** [nokia/RED#236]
RED: 0.8.6
Windows 7

after 24 hours, when i rerun test case, then it through a exception error:
An internal error occurred during: "Agent connection server".
Port value out of range: -1

**Comment by michalanglart** [comment]
@wywincl Are you still experiencing this issue?

**Comment by wywincl** [comment]
@michalanglart  There is no such issue with RED version(0.8.8) , Thank you very much.

**Comment by michalanglart** [comment]
Ok, closing
