### ISSUE TITLE
When I import my customerized library, the RED editor encountered an error 

### ISSUE THREAD

**Issue by z00314736** [nokia/RED#238]
Validating error  .....cannot connect to XML-RPC server...etc

and you must restart red to solve this problem.  I want to know why   ,  please help me ,Thanks very much

**Comment by KrzysztofJozefowicz** [comment]
Hi We need to know the details, which version of RED you use, what is the python version.
In Workspace directory, under .metadata, there is .log file which may reveal useful info, if you can shere it here it would be nice.
There may be something in your Workspace/Project which breaks internals of RED, if you could provide sample project to reproduce it, we would be grateful.
