### ISSUE TITLE
FATAL: Python instalation C:\User\danielm\progs\TestAutomationGX\PortablePython\App has no Robot installed. Fix this problem to build project	red.xml

### ISSUE THREAD

**Issue by danielvanmil** [nokia/RED#24]
Hello,

We're trying to evaluate the IDE, looks promising!
One problem is that the IDE cannot find the installed robot package in our (portable) python installation and an error is logged:

> `FATAL: Python instalation C:\User\danielm\progs\TestAutomationGX\PortablePython\App has no Robot installed. Fix this problem to build project	red.xml`

App\Lib\site-packages contains a _"robot"_ and _"robotframework-2.9.2-py2.7.egg-info"_ package etc., so it looks like its installed correctly (and Ride etc. works as expected)

Also the pip install robotframework says:

> Requirement already satisfied (use --upgrade to upgrade): robotframework in c:\user\danielm\progs\testautomationgx\portablepython\app\lib\site-packages

How is the package resolving done to find the robot package? By a python env variable or else?
Is the source code available somewhere?

Thanks,

Daniel.

**Comment by adam-wypych** [comment]
Hello,

Can you check if You are able to execute command `pybot --version` and put here output?

Best Regards,
-Adam.

**Comment by danielvanmil** [comment]
Robot Framework 2.9.2 (Python 2.7.6 on win32)

**Comment by danielvanmil** [comment]
solved. re-installation of pip solved the issue (is pip used to check for the robot framework package?)

Thanks and keep up the good work!

**Comment by KrzysztofJozefowicz** [comment]
Hi, RED checks python path by running which/where command (OS specific), there is also option in Preferences (Eclipse scope) and in red.xml (just for project scope) to specify custom python&RF installation path.

**Comment by danielvanmil** [comment]
solved. pybot needed administrator rights to run. thanks.

**Comment by k0enf0rNL** [comment]
Please update this on the first steps page.

**Comment by KrzysztofJozefowicz** [comment]
@k0enf0rNL - do you mean following info: 
"RED checks python path by running which/where command (OS specific), there is also option in Preferences (Eclipse scope) and in red.xml (just for project scope) to specify custom python&RF installation path. "
or
"solved. pybot needed administrator rights to run"

Former one is already included in first steps: https://github.com/nokia/RED/blob/master/doc/preferences_misc.md

**Comment by k0enf0rNL** [comment]
there should be note on that page which says something like this: "Be sure to open eclipse as administrator because pybot needs administrator rights"

**Comment by KrzysztofJozefowicz** [comment]
ok, noted :)
