### ISSUE TITLE
import pymssql to red.xml with errors

### ISSUE THREAD

**Issue by rumensoft** [nokia/RED#246]
Hi,
I have pymssql version 2.1.2, installed with command `pip install pymssql==2.1.2`.

When I try import library - I can't find pymssql.py. Then I try with QUICK Fix, but there is error:
![pymssql](https://user-images.githubusercontent.com/39481469/46133303-d6ae9680-c248-11e8-8365-e76676c44a49.png)

How I can fix this issue? RED editor is latest version.

**Comment by joanna-may** [comment]
Hi,
Can you provide some simple script how to use this library? Does it work when you run this script on your computer?

**Comment by rumensoft** [comment]
The script is very simple `Connect To Database  pymssql  ${DBName}  ${DBUser}  ${DBPass}  ${DBHost}  ${DBPort}` 

After run, there is error:
Importing test library 'pymssql' failed: ImportError: DLL load failed: The specified module could not be found.
Traceback (most recent call last):

**Comment by modrz** [comment]
you can try with version 2.1.3 `pip install pymssql==2.1.3`

**Comment by KrzysztofJozefowicz** [comment]
error message: 
```
Importing test library 'pymssql' failed: ImportError: DLL load failed: The specified module could not be found.
Traceback (most recent call last):
```
indicates that DLL file which is used by pymssql is missing therefore you need to reinstall you library.

**Comment by joanna-may** [comment]
For older version you need to add some dll files described here:
http://dhinakaran-msbi.blogspot.com/2016/05/solution-pymssql-import-mssql.html
or here:
http://pymssql.org/en/v2.1.2/freetds.html#windows
and probably you don't need to import this library (Library    pymssql).
I don't have any data base but I have the same error for Connect to database with or without this import.
FAIL : ImportError: DLL load failed: %1 is not a valid Win32 application

 We don't support libraries that are dll file, we have to check this case.

**Comment by rumensoft** [comment]
Alright, I updated to 2.1.3 and removed pymssql from red.xml and declaration in the file and now works.
Thanks you
