### ISSUE TITLE
'Format source' column positioning could be placed under user preference control

### ISSUE THREAD

**Issue by wright-david** [nokia/RED#247]
The Robot Table Editor has a useful autoformat feature when editing within Source view (in the Eclipse style). 

However currently the editor makes all decisions about 'column' positioning on it's own. For example, it seems to expand each column to fit the longest corresponding item in that column.
e.g. I currently have an RF script which calls Python library functions (passing and returning parameters) where the maximum auto-formatted line length is 399 characters!

It would be useful if at least some of the positioning was placed under user preference control.

Examples of problems / suggestions:

#### 1)  Left margin / gutter of N characters

Currently if one Keyword in a file is renamed and becomes longer, the positioning of all text in the file changes when 'format source' is used, shifting later columns further to the right (which upsets some of the simpler file diff tools)

This can result in extremely long lines of text (which might also break RfLint's configurable maximum line length rule).

Current:
```
Really Long Keyword
                       AnotherKeyword but not aligned to 'left margin'
```
Suggestion - left margin:
```
Really Long Keyword
    AnotherKeyword this time aligned to 'left margin'
```
#### 2) Exception for 'comment' type lines 
Currently the columns of lines below a [Documentation] line are indented according to the length of the [Documentation] description. Obviously this can be quite long and cause the Keyword /Test Case columns to be shifted further to the right than they would otherwise need to be.
A similar effect happens with # comments
	
#### 3) A 'desired maximum' column width
Although some columns may be very wide, probably the majority will be significantly less wide. 
So it might be useful to have a 'desired maximum' column width, which would be applied to most lines - but could be exceeded for those few lines where some of the columns are unusually wide.
This would reduce the number of lines where text gets shifted to the left or right due to column positions moving.

Users might appreciate two alternate options:
3a) a 'universal' width applied to all columns
3b) a sequence of different widths for different columns

#### 4) Spacing between columns
Currently this seems to be set at 4 space characters, but it could be reduced to 2 and still be valid RF syntax. Again a user selection would be helpful for individual preferences.

#### 5) robot.tidy
Robot Framework's  'code beautifier' should probably be considered at some level
e.g. it has a prefered order of lines (as well as it's own take on 'column' spacing)

Note - the above only considers space/tab separated files, the pipe '|' style has not been considered.

RED plug-in version 0.8.8.201809281115

**Comment by michalanglart** [comment]
This `Format source` feature was never properly implemented. It was provided in very basic version sometime when we were starting RED development and it was basically untouched from that moment. It seem to be useful so maybe it's the highest time to work on it a little bit.

**Comment by wright-david** [comment]
Thanks for your consideration. I've made some updates to my first comment, partly due to my late discovery of robot.tidy

**Comment by michalanglart** [comment]
RED formatter was enhanced in 0.8.13 so it seems all the requirements from here are fulfilled. Additionally it is also possible to format source using `robot.tidy` tool - this is configurable in preferences.
