### ISSUE TITLE
How to use relative path for user libraries

### ISSUE THREAD

**Issue by stonerzju** [nokia/RED#252]
From release note, I can saw that relative path is supported by RED, but after try out and googling for a while, I still did not find the right way to do it.
If I right click on my user libraries and choose "Add library to Red.xml", I can saw that the library is added in red.xml, but the path is still absolute path.
Since our test case need to run on both Linux and Windows, using absolute path make it impossible to run on both platform using RED.

**Comment by michalanglart** [comment]
The path to library in RED.xml is written as:
- relative if the library file is chosen from project
- absolute otherwise

We've discussed the possibility to make it relative against some path from PYTHONPATH but it wasn't implemented yet.

**Comment by stonerzju** [comment]
Hi -:
   Thanks for your reply.
   I want to confirm that when I do the following, will RED use relative path or absolute path?

   "right click on my user libraries and choose "Add library to Red.xml""
   Here the user libraries are located in a subfolder in the current project.
   
   From my test, I check the red.xml file and it is still show as absolute path.

**Comment by michalanglart** [comment]
Yes - I've just checked following scenario:

1. create project `project`
2. create directory `libs` inside it
3. create `lib.py` library file inside `libs`
4. `RMB` on library file: `Robot Framework -> Add library to red.xml`

The file is added to red.xml with relative path `project/libs` as expected.

Is your project located inside you workspace directory? Does it use linked folders?

**Comment by stonerzju** [comment]
I finally make it work, the root cause is my workspace is created somewhere else. Thanks very much for you help. 
I have another question, right now, if I want to use the project on both windows and linux, the location of robotframework is still using absolute path in red.xml. Is it possible to overcome this issue in RED?

**Comment by michalanglart** [comment]
Recently we've only made it possible to store relative paths to interpreter when it is contained inside the project - see #73 for more.

**Comment by michalanglart** [comment]
Overall red.xml is not very portable and it requires a little bit of work on that matter. If there are relative paths then they are relative to workspace. As to the location of robotframework - it of course doesn't have to be specified in red.xml at all and can be taken from preferences. Usually this is enough for users are they rarely have more than one python (maybe two) installed.

**Comment by stonerzju** [comment]
Thanks very much, It works fine for me now.
