### ISSUE TITLE
Dialogs library non-accesible

### ISSUE THREAD

**Issue by alanqng** [nokia/RED#254]
Hello,

I'm reveiving this problem related to the dialogs library:
"Library specification file was not generated for 'Dialogs' library"

Any ideas how to fix this?

**Comment by KrzysztofJozefowicz** [comment]
As far as I remember, Dialogs needs to have tkinter lib installed to Python
interpreter.
You can verify this by running libdoc from command line to see if you get
the same error as in RED:
python -m robot.libdoc Dialogs show

wt., 23 paź 2018, 19:45 użytkownik alanqng <notifications@github.com>
napisał:
