### ISSUE TITLE
Rerun Test and Rerun Failed Test actions not using the default launch config values

### ISSUE THREAD

**Issue by AndrewNewell2** [nokia/RED#257]
We have set an output folder in "Default Launch Configurations" but when we rerun a test or rerun a failed test from the Execution View tab, the output files, including screenshots all go to the project root rather than using the default output folder set.

![red default launch config](https://user-images.githubusercontent.com/13424767/47815826-4d91fe80-ddb6-11e8-9541-1b9b3fe3b530.PNG)

**Comment by modrz** [comment]
Hi,
It looks like default launch configuration preferences for failed test rerun are not used.
We will have to implement this.

**Comment by michalanglart** [comment]
Released in 0.8.9
