### ISSUE TITLE
run on multiple browsers

### ISSUE THREAD

**Issue by manjugb** [nokia/RED#258]
Hi 
I tried use this editor for writing robot scripts
I tried to run my scripts on multiple browsers , this was not working
Please let me know is this functionality is there or still implemented

**Comment by michalanglart** [comment]
Hi,

To be honest I don't understand the issue when it is stated as above. Do you have Robot scripts which are running fine when executed from command line but fails when running from RED or...?

Could you define what is this functionality you're asking about? You're making some mental shortcuts here which are very unclear to me. What does it mean that you're running script on browsers? RED is running scripts using Robot Framework and it doesn't know anything about browsers being involved (although the scripts may open browser and perform tests of some website, but this is a logic of the test which RED is unaware of).

**Comment by manjugb** [comment]
Steps I followed
I created robot tests which should run multiple browsers here is the script
***** Settings ***
Documentation     A resource file with reusable keywords and variables.
...
...               The system specific keywords created here form our own
...               domain specific language. They utilize keywords provided
...               by the imported Selenium2Library.
Library           Selenium2Library

*** Variables ***
${BROWSER}        chrome      #So default browser is firefox. you can leave it blank
@{BROWSERS}       firefox    chrome
${URL}            http://www.youtube.com
${DELAY}          0
${WELCOME URL}    http://${URL}/

*** Test Cases ***
TestBrowser
    test with several browser
  
*** Keywords ***
test with several browser
    :FOR  ${BROWSER}  IN   @{BROWSERS}
    \  log to console  call keyword that does your test with ${BROWSER}
    Open Browser   ${URL}   ${BROWSER}   
    Maximize Browser Window
    Set Selenium Speed    ${DELAY}
    YouTube Page Should Be Open 
    [Teardown]    Close Browser 
  
  
YouTube Page Should Be Open
    Title Should Be  YouTube
*******************************************************************************
  When i ran from RED   its taking only Firefox and not taking other value Chrome as browser
when I ran same on command line it runs on both browsers
[](url)

**Comment by manjugb** [comment]
Here is my last ran on RED
-----------------------------------
Command: /usr/bin/python -m robot.run --listener /tmp/RobotTempDir2536993915866363968/TestRunnerAgent.py:38984 --argumentfile /tmp/RobotTempDir2536993915866363968/args_9e02826e.arg /home/manjunath/workspace-robotFramework/YouTube
Suite Executor: Robot Framework 3.0.4 (Python 3.5.2 on linux)
==============================================================================
YouTube                                                                       
==============================================================================
YouTube.youTubeTestSuite                                                      
==============================================================================
YouTube.youTubeTestSuite.Valid Search :: A test suite with a single test fo...
==============================================================================
Valid Search_one                                                      call keyword that does your test with firefox
call keyword that does your test with chrome
| PASS |
------------------------------------------------------------------------------
Valid Search_two                                                      call keyword that does your test with firefox
call keyword that does your test with chrome
| PASS |
------------------------------------------------------------------------------
YouTube.youTubeTestSuite.Valid Search :: A test suite with a singl... | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
YouTube.youTubeTestSuite                                              | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
YouTube                                                               | PASS |
2 critical tests, 2 passed, 0 failed
2 tests total, 2 passed, 0 failed
==============================================================================
Output:  /home/manjunath/workspace-robotFramework/YouTube/output.xml
Log:     /home/manjunath/workspace-robotFramework/YouTube/log.html
Report:  /home/manjunath/workspace-robotFramework/YouTube/report.html

**Comment by joanna-may** [comment]
Hi,

due to problems with reading your script after pasting (spaces where removed) I created my own script:
```robotframework
*** Keywords ***
test with several browser
	:FOR  ${BROWSER}   IN   @{BROWSERS}
	\   log   to console call keyword that does your test with ${BROWSER}
	\    Open Browser  ${URL}  ${BROWSER}
	\   Maximize Browser Window
	\   Set Selenium Speed  ${DELAY}
	\   Close Browser
```
Did "\" was missing in lines after LOG in FOR ? With this I had both browser opened. 
Sometimes after running selenium tests by RED geckodriver is still in running processes (especially when test failed and browser was not closed).

In this version
```robotframework
*** Keywords ***
test with several browser
	:FOR  ${BROWSER}   IN   @{BROWSERS}
	\  log   to console call keyword that does your test with ${BROWSER}
	Open Browser  ${URL}  ${BROWSER}
	Maximize Browser Window
	Set Selenium Speed  ${DELAY}
	[Teardown]   Close Browser
```
only last browser will be open and last is closed by Teradown

**Comment by manjugb** [comment]
Now it works, thank you for help
