### ISSUE TITLE
Program slows down when editing a big file

### ISSUE THREAD

**Issue by Teddy12090** [nokia/RED#259]
Here is the sample file of a big file. You can open it and type some characters in *Source mode*. You will significantly sense that the editor is slow.

[test.robot.txt](https://github.com/nokia/RED/files/2588076/test.robot.txt)

**Comment by michalanglart** [comment]
Hi,

We've investigated editing bigger files a year or two ago and then we've improved the performance so that the editor was usable with exemplary files having ~2-4k lines which seem to be enough for files containing code. I'm not excluding that the performance could dropped from that time so we'll have a look with the profiler. 

However please take into account that your sample file has length of ~933 000 which would give almost 8 000 lines when having 120 characters per line. As far as I remember this is around twice as much as the biggest robot file we've found in hundreds of files that our internal clients gave us for analysis at the time we were checking the performance. By the way - just recently I've created a .java file with some JUnit tests which grow up to 2800 lines with a total length of ~222 000 and working with it was getting slower in eclipse Java editor as the file was getting longer.

**Comment by RamaraoAllamraju** [comment]
Hi,

Even I am also facing the same issue.
My file size is 12KB and the length is nearly 10K, which is small, but still I am facing lagging while performing any actions.

Please find the attached sample file.

[login.txt](https://github.com/nokia/RED/files/3071981/login.txt)

**Comment by RamaraoAllamraju** [comment]
> Hi,
> 
> We've investigated editing bigger files a year or two ago and then we've improved the performance so that the editor was usable with exemplary files having ~2-4k lines which seem to be enough for files containing code. I'm not excluding that the performance could dropped from that time so we'll have a look with the profiler.
> 
> However please take into account that your sample file has length of ~933 000 which would give almost 8 000 lines when having 120 characters per line. As far as I remember this is around twice as much as the biggest robot file we've found in hundreds of files that our internal clients gave us for analysis at the time we were checking the performance. By the way - just recently I've created a .java file with some JUnit tests which grow up to 2800 lines with a total length of ~222 000 and working with it was getting slower in eclipse Java editor as the file was getting longer.



> Hi,
> 
> We've investigated editing bigger files a year or two ago and then we've improved the performance so that the editor was usable with exemplary files having ~2-4k lines which seem to be enough for files containing code. I'm not excluding that the performance could dropped from that time so we'll have a look with the profiler.
> 
> However please take into account that your sample file has length of ~933 000 which would give almost 8 000 lines when having 120 characters per line. As far as I remember this is around twice as much as the biggest robot file we've found in hundreds of files that our internal clients gave us for analysis at the time we were checking the performance. By the way - just recently I've created a .java file with some JUnit tests which grow up to 2800 lines with a total length of ~222 000 and working with it was getting slower in eclipse Java editor as the file was getting longer.

Hi,

Even I am also facing the same issue.
My file size is 12KB and the length is nearly 10K, which is small, but still I am facing lagging while performing any actions.

Please find the attached sample file.

**Comment by michalanglart** [comment]
Hi,

what kind of lagging do you experience? What actions are slow? Colouring, showing assistance, typing?

**Comment by RamaraoAllamraju** [comment]
> d of lagging do you experience? What actions are slow? Colouring, showing assistance, typing?

Hi,

The Typing is slow, If I write some 1liner code in that file it takes nearly 2-3mins enter into the file.

**Comment by michalanglart** [comment]
I've just played for a while with your `login.txt` file and haven't notice any lagging. We're talking about typing in source editor not tables, right? 

What is your RED version, OS and the machine?

**Comment by michalanglart** [comment]
We haven't found obvious place to get real speed-up with profiler attached. The file attached by reporter is - as I alread pointed out - rather big to be practical example of a maintanable and readable tests suite. I'm closing this one for now. Reopen or open new issue if bottleneck is found.
