### ISSUE TITLE
Open declaration (F3) does not work for keywords outside current file

### ISSUE THREAD

**Issue by TimoLinden** [nokia/RED#26]
Hi,
When I select a keyword and press F3 to see its declaration it only works if the keyword is defined in the same file. I'm using pre-released RED 0.6.5.
Cheers,
Timo

**Comment by KrzysztofJozefowicz** [comment]
in 0.7.2 F3 opens following scenarios:
- KW declaration from current testcase file
- KW declaration from resource file in project
- KW declaration from resource file from other projects in workspace

Keep in mind that Eclipse and RED cannot open files outside of workspace.
