### ISSUE TITLE
"Problem occurred during generating libdoc" error with "Unable to communicate with XML-RPC server"

### ISSUE THREAD

**Issue by rumensoft** [nokia/RED#261]
Hi,
I want to add java library (executable jar) in RED.
On my local machine I'm using RED and I don't have any problems with java library (RED version: 0.8.8, Win7 64bit)

On different machine (Win10 64bit, RED version 0.8.9, based on Eclipse Version: 2018-09 (4.9.0) Eclipse IDE for java), I can't use java library. There is error:

> Library specification generation problem
> Problem occurred during generating libdoc for 'com.test.Keywords' library located at 'C:\lib\Lib.jar'.
> Unable to communicate with XML-RPC server

When is imported in red.xml file, the library is red and there is message ` library specification file was not generated for` and in the Project Explorer the error is: `non-accessible`

Why is this happen? I'm confused.

**Comment by michalanglart** [comment]
Hi,,
are there more details in you worksapce `metadata/.log` file? 

If not then you can also try to see what is the output of the server: http://nokia.github.io/RED/help/user_guide/diagnostics.html (paragraph 1. Displaying server console)

**Comment by rumensoft** [comment]
Hi,

Thank you for the answer. Well, there is no lines in .log file.
Here is what I have from Server Console:

When I import the library:

> 
# RED session server started @60548
# python version: 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]
# robot version: Robot Framework 3.0.4 (Jython 2.7.0 on java1.8.0_144)
# script path: C:\Users\ADMINI~1\AppData\Local\Temp\1\RobotTempDir4739324011755744503\robot_session_server.py


[02:58:56.193] calling 'check_server_availability' function, no arguments
[02:58:56.194] call ended with result:
127.0.0.1 - - [21/Nov/2018 02:58:56] "POST / HTTP/1.1" 200 -
    > None
[02:58:56.223] calling 'get_standard_libraries_names' function, no arguments
[02:58:56.244] call ended with result:
    > ['OperatingSystem', 'Easter', 'Remote', 'Process', 'String', 'DateTime', 'Dialogs', 'XML', 'Screenshot', 'Telnet', 'Collections', 'BuiltIn', 'Reserved']
127.0.0.1 - - [21/Nov/2018 02:58:56] "POST / HTTP/1.1" 200 -


When I refresh the library and getting error, from the previous post:

> # RED session server started @60706
# python version: 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]
# robot version: Robot Framework 3.0.4 (Jython 2.7.0 on java1.8.0_144)
# script path: C:\Users\ADMINI~1\AppData\Local\Temp\1\RobotTempDir4739324011755744503\robot_session_server.py


[02:59:41.561] calling 'check_server_availability' function, no arguments
[02:59:41.562] call ended with result:
    > None
127.0.0.1 - - [21/Nov/2018 02:59:41] "POST / HTTP/1.1" 200 -
[02:59:41.671] calling 'create_libdoc' function, supplied arguments:
    > com.test.Keywords
    > xml
    > ['C:\\Tools\\Python']
    > ['C:\\lib\\Lib.jar']

**Comment by michalanglart** [comment]
Is there something missing? There is only log added prior to calling libdoc generation function (the `[02:59:41.671]` line) but there should be also next one logged after this method ends (`call ended with result:`)

**Comment by rumensoft** [comment]
Alright, I tried another simple jar and works.
So the problem is .jar file. But why?

Here is the difference of the jar, that I can't use:
`import org.sikuli.script.*;`
`import org.sikuli.basics.Settings;`

And this library is external sikulix.jar, that is included in Java project.
Then I extract the jar file from Eclipse and try to use it.

**Comment by michalanglart** [comment]
Do you have this error thrown after some timeout (around 30 seconds) or just after trying reloading? How does the constructor of your library look like? Does it execute some other code apart from simple fields assignments?

**Comment by michalanglart** [comment]
I'm asking because from logs you've provided it seems that RED is trying to generate libdoc but it hangs and then after timeout have passed RED throws an exception due to not having response from libdoc generation request.

**Comment by rumensoft** [comment]
[Lib.zip](https://github.com/nokia/RED/files/2604382/Lib.zip)
Could you please check with your RED Editor. I'm attaching you, the library. If you need the source code (java project), tell me.
Thanks

**Comment by michalanglart** [comment]
There is an error which causes libdoc generation to crash. It is not visible since the libdoc tool caputures the output but once I switched it off when debugging I was able to see that:

```
[error] RunTimeINIT:  *** terminating: libs to export not found on above classpath: /sikulixlibs/windows/libs64
```

This suggest that somehow this jar is wrongly built. The issue can be found via google in several places e.g.:
https://answers.launchpad.net/sikuli/+question/272405
https://stackoverflow.com/questions/49127729/terminating-libs-to-export-not-found-on-above-classpath-sikulixlibs-windows-l

**Comment by rumensoft** [comment]
Wow... Thank you very much. I will try to find solution on that now.
I will post solution later, if I can fix this.

Again, Thank you

**Comment by rumensoft** [comment]
It was stupid mistake.

I re-install Sikuli, the the jar from Sikuli I pointed to SIKULI_HOME Sys/User variable and Path "%SIKULI_HOME%" Sys/User variable and the error disappeared. 

Big Thank you!

**Comment by humbienri** [comment]
How was this fixed?  Are you talking about the machine's/computer's Environment variables?
