### ISSUE TITLE
"Unable to find output console" in latest Eclipse version

### ISSUE THREAD

**Issue by martin-fleck-at** [nokia/RED#263]
We updated to the latest version of Eclipse and are facing an issue where on the first Robot launch the console is not available, resulting in the 'Unable to find output console' error. Specifically, we programmatically create a Robot launch config and launch it in a workspace job.

However, the console creation in the latest Eclipse version seems to have changed from a synchronous console creation mechanism to an asynchronous console creation to avoid deadlocks, cf. [1]. Now I believe we run into the case where a console is requested from RobotConsoleFacade during launch but the console creation job has not been executed/finished yet.

[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=355011

**Comment by martin-fleck-at** [comment]
Hi,

Thank you for the very fast response! We are using 2018-12 (4.10 Milestone 1, from 2018-10-10).  Yeah, I saw that the RCPTT migration is still in progress [1] and I also hope that it will be done soon ;-)

[1] https://git.eclipse.org/r/#/c/130963/

**Comment by michalanglart** [comment]
Fixed in 0.8.11
