### ISSUE TITLE
Revalidating model has encountered a problem (0.8.10)

### ISSUE THREAD

**Issue by KikitheKing** [nokia/RED#266]
Hello,

I have found an issue when i have updated a variable in my keyword with a wrong syntaxe (my mistake) but the revalidation model doesn't like it.

The error:
An internal error occurred during: "Revalidating model".
An exception occurs during variable extraction in file null at position FilePosition [line=306, column=105, offset=13498] for text ${lastname${a}=${TRUE}

My current example:
Set Add User
    [Arguments]    ${username}    ${password}    ${password_confirmation}    ${email}    ${firstname}    ${lastname${a}=${TRUE}

It doesn't like "${lastname${a}=${TRUE}".

Of course, update it with the right syntaxe ( ${lastname}=${TRUE} ) fix the issue.

**Comment by michalanglart** [comment]
Fixed in 0.8.11
