### ISSUE TITLE
linux 32bit version

### ISSUE THREAD

**Issue by humbienri** [nokia/RED#267]
Hello all!

Does the linux flavor of RED only come in 64bit version?  No 32b version?  I'm thinking that may be the reason why I can't get RED to launch on my Devuan laptop system.

I can see it under Applications > Development but when I click on it nothing happens. No errors, no launch. Absolutely nada!

Advice?

**Comment by humbienri** [comment]
Hello,

Thanks!  Now that you mention it it does seem obvious to do that.  I went ahead and did and it works so so.  Not great.  RED/Eclipse will occasionally freeze up because of a gObjectClass_finalize error.  Nothing specific that I can think of that I am doing to trigger that error.  Even just when switching from one editor to another one and I'll get that error.

Some internet searching led to me this:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=527536

where I think they've just given up on trying to fix it b/c it is 32bit architecture.  Sucks 'cause I really do like this laptop!

Thanks anyway.

**Comment by modrz** [comment]
Hi,
If it is GTK3 related bug, you can try to use GTK2 by adding following to your eclipse.ini
```
--launcher.GTK_version
2
```
