### ISSUE TITLE
Header in table testcases when using a testtemplate

### ISSUE THREAD

**Issue by p74** [nokia/RED#270]
When using a test template in Ride it is possible to add a header to the data table like

```
*** Test Cases ***    foo1                                                                 foo2                                             foo3
test                [Tags]                                                        tag discription
                       1                                                                            20                     D1420
```
but in red this option is not available .... when clicking on tab Test cases foo1. foo2 and foo3 is missing in the table It would be nice if this is added to red as well.

Greetings Ruud

**Comment by adam-wypych** [comment]
It is similar to #100.

**Comment by p74** [comment]
indeed oeps pls close this one

Op ma 14 jan. 2019 om 11:41 schreef adam-wypych <notifications@github.com>:

**Comment by michalanglart** [comment]
Recently we were talking about changing the tables in a way which would make them look more similar to how it looks in source. Currently we for example display elements in single row despite the fact that they are written in multiple lines etc. This causes us at least couple problems with both displaying and editing via tables.

If that would change then this issue should be also fixed.

Closing as a duplicate anyway.
