### ISSUE TITLE
"Eclipse Marketplace" doesn't start

### ISSUE THREAD

**Issue by alsido** [nokia/RED#274]
Clicking on _Help_ - _Eclipse Marketplace_ has no effect. Marketplace doesn't start. 

Windows 7, RED 0.8.11, included Marketplace client v.1.7.0

**Comment by michalanglart** [comment]
Do you have any errors shown? Is there an error logged in your `workspace/.metadata/.log` file?

Clicking there should open a new window - does it appear at least for short period of time?

**Comment by alsido** [comment]
No, no errors or any visible activity.

I just figured out that it happens if I add proxy information. After removing proxy data, Marketplace starts (but has no connection of course). It's on new "clean" 0.8.11 installation. If I update 0.8.8 to 0.8.11 using update mechanism, Marketplace works as expected, also with proxy.

There is a lot of text in `.log`, I'll try to provide the relevant data next week.

**Comment by michalanglart** [comment]
After marketplace dialog is open it tries to connect to the actual marketplace so the proxies may be relevant here. However so far it does not seem to be an issue of RED & Marketplace Client (MPC) integration so I doubt we will be able to help.

The MPC is a feature provided and maintained by Eclipse Foundation - the only code line related to MPC in our codebase is the one in some xml configuration file which ensures that when RED product is being build the MPC will be installed in it.

**Comment by alsido** [comment]
Here is the error message:

> !ENTRY org.eclipse.ui 4 0 2019-02-18 08:32:19.152
> !MESSAGE Unhandled event loop exception
> !STACK 0
> org.eclipse.e4.core.di.InjectionException: java.lang.IllegalArgumentException: Illegal character in path at index 16: file:/C:/Program Files/RED_0.8.11/configuration/
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)

many lines

> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
> 

That illegal character is the space in "Program Files". After moving the RED folder to another location, MPC starts correctly. 

I downloaded the latest Eclipse release - exactly the same behavior.

**Comment by michalanglart** [comment]
As I suggested in previous comment - this is an eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=536385

**Comment by alsido** [comment]
Oh, thank you for the link. My attempts to find anything similar on their bug tracker weren't successful.
