### ISSUE TITLE
RED reports unknown keyword error on lib keywords

### ISSUE THREAD

**Issue by maxrossello** [nokia/RED#275]
A light bulb with error icon appears on lines where a keyword defined in library is used. Error displayed is 'Unknown keyword'.
The test script can run fine, but the error display is annoying because it completely hides other icons, for example the debug breakpoints, that are consequently hard to toggle blindly.

Is there a way to make RED recognize the lib keywords properly?

Note that the library is only explicitly referenced in an included resource file, and I would prefer to keep this separation of concerns as such.
Thanks

**Comment by michalanglart** [comment]
RED recognizes keywords from only those libraries which are explicitely defined in red.xml project configuration file. Do you have your library added there?

In most cases it is sufficient to run automatic libraries discovery process: select your project in Project Explorer and from context menu choose `Robot Framework` -> `Automatically discover and add libraries to red.xml`

**Comment by maxrossello** [comment]
Hi,
thanks for prompt response.

That would be great, but it does not seem to work. See e.g. "Set Cmd"

![image](https://user-images.githubusercontent.com/4066651/52849809-392e0380-3112-11e9-86fc-e4d4ea2dbac3.png)

**Comment by michalanglart** [comment]
And how is this library imported? What are the dependencies between this library and the file(s) in which the keyword are used?

**Comment by maxrossello** [comment]
e.g. S1_row_management.robot has a line

    Resource          ../resources/SnmpResources.robot

and SnmpResources.robot has

    Library           ../../../libs/SnmpTester.py

which is out of the project folder because it is shared with other projects

**Comment by michalanglart** [comment]
Is it out of the workspace folder too? I'll try to reproduce that with some simple case

**Comment by maxrossello** [comment]
I mean, my environment folders come with ./robot/libs and ./robot/test which is where the .project is

**Comment by michalanglart** [comment]
I tried following scenario with RED 0.8.11:

1. Download attached zip containing simple project with similar structure to your (from what I can see at screenshot)
[example.zip](https://github.com/nokia/RED/files/2869155/example.zip)
2. Open RED
3. Import project `GH-275` from `example` directory: `File` -> `Import` -> `Existing Projects into Workspace` -> `Select root directory`. Choose `GH-275` directory and make sure to check `Copy projects into workspace`
4. Copy `libs` directory from `example` to your workspace directory where now `GH-275` is placed
5. Run libraries discovery: in my case `lib` is added to red.xml properly

After that RED sees the keyword although a warning is placed there telling that the keyword is coming from library imported by some other file. This can be disabled in preferences (`Keyword from nested library` problem).

Can you check if that works for you too? What is different than your full project? If you can spot the difference - can you prepare some similar minimal project which would reproduce the issue?

**Comment by maxrossello** [comment]
ok sure, give me just some time!
thanks a lot

**Comment by maxrossello** [comment]
ok, I think I figured out at least part of the problem.
First of all, I have to say that I often copy my environment to have copies of it and work on different branches. I do not usually copy the projects into workspace but it seemed not to be the root cause. 
The problem probably arose becausethe lib path was absolute and pointing to another workspace (not copied, so absolute external lib yet existing). By deleting former reference and re-discovering it solved the problem.

Now, my question is whether the fact that rediscovery again produced an absolute path is correct (RED displays a warning for this). If this was generated as relative, the problem probably did not show.
Is this absolute path due to the fact that I am not copying the project in workspace? I tend to avoid it because the disk space occupation gets doubled with no particular advantage.

Thanks!

**Comment by michalanglart** [comment]
RED should write relative path in red.xml to the library always when the library is inside the workspace. Otherwise absolute path is written.

**Comment by maxrossello** [comment]
ok understood.
However, the absolute path was nevertheless a valid one. Shouldn't the keyword be properly found anyways?

**Comment by michalanglart** [comment]
Yes - the form of the path in red.xml does not matter in this case. If the specification file was generated properly for given library (and here it was - otherwise it would be marked red in project explorer) then the keywords are visible for RED

**Comment by maxrossello** [comment]
ok. Also because the lib, external to the project, does not get copied automatically, nor it gets deleted with project files automatically, so it would need extra manual work within the workspace, which is a bit uneasy

**Comment by michalanglart** [comment]
Hi,

is there something we can do for this issue? Have you run into it again?

**Comment by maxrossello** [comment]
I think the issue is still open as per your conclusions at above comment https://github.com/nokia/RED/issues/275#issuecomment-464061413 . The absolute path for the lib was correct and yet not recognized.
Personally I have not copied any workspaces anymore, so I didn't run into the problem again.

**Comment by michalanglart** [comment]
Ok we'll try to reproduce it

**Comment by modrz** [comment]
The only way I managed to reproduce such relative/absolute path discovering is:

1. Discovering libraries when libraries project is not imported into workspace.
![image](https://user-images.githubusercontent.com/22540835/67938553-02c8e380-fbd0-11e9-9b3f-85b7768313c1.png)

2. Discovering libraries when libraries project is imported into workspace.
![image](https://user-images.githubusercontent.com/22540835/67938567-09eff180-fbd0-11e9-9e3c-a35b65bd5c8f.png)

But it is normal behavior, RED will relativize only paths to files that are inside the workspace (in Eclipse virtual file system). In your case you probably used project with red.xml like in first example.

In future, instead of making copies of whole project, you can use branching feature from one of version control systems.

I am closing this issue.

**Comment by modrz** [comment]
No, libspec files can be ignored. I suggest using version control branching on your project files to avoid copying whole environment. It probably caused problems with paths in red.xml.
