### ISSUE TITLE
Editor gets into error and shows corrupt text on screen.

### ISSUE THREAD

**Issue by hwithaar** [nokia/RED#277]
I am using latest version, but get very often that the editor shows corrupt text and something get an error dialog box.
I have to close Eclipse and start again to solve the issue.
Anyone experiencing same issue?

**Comment by michalanglart** [comment]
Can you provide us with the content of the error dialog box? Also are there any errors logged in `./metadata/.log` file in your workspace?

**Comment by michalanglart** [comment]
Closing. Please reopen if it repeats and provide us with the details I've mentioned
