### ISSUE TITLE
Move the text so that the clicked item is on top of the screen

### ISSUE THREAD

**Issue by alsido** [nokia/RED#279]
When I click in the right "Outline" pane on an item (test case or keyword), the main windows jumps to that item. But if before clicking this item is below the visible screen, it appears at the bottom and only its title is shown after jumping so it is necessary to scroll down to see the body of the item (Test 7 was clicked):

![red1](https://user-images.githubusercontent.com/42670823/53414415-023bd580-39cf-11e9-9b2b-83c0de89f6bf.PNG)

If the item is above the visible screen, then the item is on the top of the screen after jumping and there is no need to scroll (Test 2 was clicked):

![red2](https://user-images.githubusercontent.com/42670823/53414519-4038f980-39cf-11e9-97f7-c6d110763eb6.PNG)

Is it possible to move the screen so that the clicked item is always placed on the top?

**Comment by michalanglart** [comment]
Hi,

sure - this looks doable and should be rather easy to implement

**Comment by michalanglart** [comment]
Done in 0.8.12
