### ISSUE TITLE
Keywords after a Run Keyword If condition are not validated. 

### ISSUE THREAD

**Issue by AccessRichardB** [nokia/RED#28]
Hi 

In the example below, the Log keyword should be flagged as an error because the Log keyword requires a message argument to be passed to it. However the syntax validator is not highlighting this, would it be possible to add validation of keywords that appear after the Built-In conditional keywords?  

**\* Keywords ***
Conditional Test
    Run Keyword If    'x'>'y'    Log

**Comment by adam-wypych** [comment]
Hi,

I think is quite complex since keywords like `Run Keyword If*\Set Variables If*` are open gate for syntax like `ELSE IF\ELSE` ( see: http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Run%20Keyword%20If ). I have been checked it and even RIDE do not support such fully validation. But I think in some point we will need to put some effort to introduce such validation.

Best Regards,
-Adam.

**Comment by adam-wypych** [comment]
Copy of some discussion with Michal from ( https://github.com/nokia/RED/issues/224#issuecomment-396854456 ):

>> However it seem to be quite hard to make it customizable for users because those keywords are basically free to interpret provided arguments and sometimes there may be non trivial logic implemented there.

>To be honest I was thinking that you do not need to treat whole line of execution as one. If you will use old technic divide and conquer, you can achieve customise ability. In my opinion if you will just check each keyword separately (nested keyword) is not to hard to achieve possibility to have some kind of the table, which will say that argument on position 2 of keyword X is keyword name and start from the next position (3) could be his arguments.

>Anyway I think the most critical for both hardcoded and customizable is to decide if ELSE is part of keyword put as argument or is part of Run Keyword If syntax. This I think require to take a look how Robot Framework is parsing such syntax.

So regarding `Run Keyword If` as nested keyword in other `Run Keyword If`, some clarification is needed from Robot Framework contributors. I figurated that the syntax is not fully supported, as it could be expected (https://github.com/robotframework/robotframework/issues/2871). Shortly describing the issue, `ELSE` from the latest nested `Run Keyword If` is used for any `Run Keyword If` condition in the path.

Anyway, I reviewed the Robot Framework source code related to handling `Run * If` keywords. Base what was written in comment for `Run Keyword If` method ( https://github.com/robotframework/robotframework/blob/master/src/robot/libraries/BuiltIn.py#L1680 ) :
> Notice that ``ELSE`` and ``ELSE IF`` control words must be used
explicitly and thus cannot come from variables. If you need to use
literal ``ELSE`` and ``ELSE IF`` strings as arguments, you can escape
them with a backslash like ``\\ELSE`` and ``\\ELSE IF``.
Base on this I think it shouldn't be hard to introduce support for _customizable keyword variants_.
 
I am not aware if logic related to discovery from where keyword comes still stays in plugin, but I think is possible to create filter/wrapper output of https://github.com/nokia/RED/blob/master/src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/main/java/org/rf/ide/core/testdata/model/table/exec/descs/ExecutableRowDescriptorBuilder.java, which will get an information about keywords (basically if keyword with name is `variant keyword`) from plugin and will include information about treatment of `ELSE`, `ELSE IF`, `END`, `or`, `and` (case sensitive) in condition as special words. 
It should return splitted variant keywords to execution lines understandable by validation logic. As the advantages of this solution the `BuiltIn.Run Keywords` can be handle in such approach as well.

**Comment by adam-wypych** [comment]
As per Pekka response (https://github.com/robotframework/robotframework/issues/2871#issuecomment-398687242) 
>We could easily document that nested used is not supported in `Run Keyword If` documentation.

So such nested ELSE usage should be mark as an error.

**Comment by KrzysztofJozefowicz** [comment]
released in 0.8.7
