### ISSUE TITLE
Need to validate the metadata according to our needs in RED

### ISSUE THREAD

**Issue by sudarsesh** [nokia/RED#282]
```RobotFramework
***Settings***

Metadata       script_author      some_author_email
```

Here, I would like to validate the author name and mark it invalid (highlight as red) if the value is invalid.
Are there any hooks to develop custom validation scripts and integrate with RED?

**Comment by michalanglart** [comment]
Hi,

no there are no such hooks in RED.

However you might write a custom rule for rflint (https://github.com/boakley/robotframework-lint) and RED is able to run rflint within IDE (although it has to be started manually and is not automatically re-run when something changes) - see http://nokia.github.io/RED/help/user_guide/tools_integration/rflint.html

**Comment by michalanglart** [comment]
Hi,

is there anything we could do now with this issue? Have you tried using rflint and integrating it with RED?

**Comment by michalanglart** [comment]
Closing for now. Please use rflint or raise an issue to open some API in which one could hook with own code.
