### ISSUE TITLE
RED does not find chromedriver

### ISSUE THREAD

**Issue by CristianaVieira** [nokia/RED#285]
Hi all,
I am struggling with an issue using RED.
I was trying to run some tests and the fact is that I'm always receiving the same error:
'WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home'.
I've already added the chromedriver to the PATH.
The problem is that through command line I'm able to run the tests when using 'sudo' before.
Am I struggling with some permissions issue?
Thank you for your help!

**Comment by joanna-may** [comment]
Hi,
what system do you use? Where RED is installed? 
If you use MAC there was issue already reported:
https://github.com/nokia/RED/issues/89
Maybe this will help too:
https://apple.stackexchange.com/questions/261695/new-mbp-with-sierra-usr-local-bin-no-longer-accessible-unless-root
https://discussions.apple.com/thread/2400512

**Comment by CristianaVieira** [comment]
Hi @joanna-may 
Thank you for your reply!
Yes I'm using a Mac.
