### ISSUE TITLE
An internal error occurred during: "Building". Input byte array has incorrect ending byte at 20100

### ISSUE THREAD

**Issue by zhangmx** [nokia/RED#286]
Hi RED Team,

I use RED with SeleniumLibrary and everything works fine, but when i try to run demo with SikuliLibrary got a building error.  The error is just building error, that means run the code in demo have no problem.

win10：Python 3.7.2 32bit；java version "1.8.0_201" 64bit

Robot Framework 3.1.1 (Python 3.7.2 on win32)

robotframework-seleniumlibrary      3.3.1
robotframework-SikuliLibrary        1.0.4

red:0.8.11
eclipse 4.8

robotframework-SikuliLibrary demo link:
https://github.com/rainmanwy/robotframework-SikuliLibrary/tree/master/demo/hello_world

**step:**

1."File"-"New"-"Robot Project" with project name 'sikuli'.
2.copy files in hello_world to sikuli project's folder.
3.rename "testsuite_sikuli_demo.txt" to "testsuite_sikuli_demo.robot"
4.click text "SikuliLibrary" in file "testsuite_sikuli_demo.robot" and press 'ctrl+1'
5.click tip "Discover 'SikuliLibrary' and add to configuration"
6.open 'red.xml' file and press 'ctrl+s'

![red-bug](https://user-images.githubusercontent.com/1308646/55220263-d4ea7d80-5241-11e9-8b33-496964d2e79d.png)

Any assistance would be very appreciated.
Thanks!

**Comment by modrz** [comment]
Hi,

This looks like a problem we've already found, see #281.

Workaround for now is disabling preference in:
`Robot Framework -> Libraries -> Generate Python libraries libdocs in separate process`

**Comment by zhangmx** [comment]
@modrz thx very much! it's worked by disable 'Generate Python libraries libdocs in separate process'.

**Comment by michalanglart** [comment]
This will be fixed in upcoming release
