### ISSUE TITLE
Unable to communicate with XML-RPC server when importing custom python library

### ISSUE THREAD

**Issue by alex473x** [nokia/RED#288]
Hi RED team,
When trying to import a python custom library, if this library imports some packages (i.e. import cv2), it leads to a "Unable to communicate with XML-RPC server" message.
A workaround is to move this imports inside the method which use them.

Complete description is provided here (I have the same issue): 
https://stackoverflow.com/questions/53468583/eclipse-and-red-unable-to-communicate-with-xml-rpc-server

**Comment by modrz** [comment]
Hi,

It was fixed in version 0.8.11, please check https://github.com/nokia/RED/releases/tag/0.8.11

**Comment by alex473x** [comment]
Hi,
You're right, it's work well in 0.8.11. I missed it due to "Illegal base64 character 20" pb  ....

Thanks for your answer.
