### ISSUE TITLE
Accuracy of build instructions in building.md

### ISSUE THREAD

**Issue by humbienri** [nokia/RED#290]
Hello,

Am trying to build RED from source on Devuan linux.  I'm trying to figure out what dependencies RED has and in reading the building.md file I notice that the instructions are referencing files that I simply do not see in the downloaded files.

How accurate (or not) are those instructions?

Thank you!

**Comment by michalanglart** [comment]
Hi,

this file wasn't revised for quite a long. We'll have a look for next release

**Comment by smalhotra21** [comment]
Looking for the same info. When can we expect updated instructions

**Comment by michalanglart** [comment]
With next release - hopefully within one week.

**Comment by michalanglart** [comment]
It took slighlty longer but now we've updated and double-checked building instructions
