### ISSUE TITLE
WM_Class is empty on ubuntu 16.04

### ISSUE THREAD

**Issue by zhanddkk** [nokia/RED#291]
I enter `xprop WM_CLASS` in terminal and click on the RED window, it returns `WM_CLASS(STRING) = "", ""`.
I think RED should be set as a special name, then we can create a `xxx.desktop` file easily for it.

**Comment by modrz** [comment]
Hi,
It will be set in next version

**Comment by michalanglart** [comment]
Fixed in 0.8.12
