### ISSUE TITLE
Debugger does not stop on local library breakpoints

### ISSUE THREAD

**Issue by manosnoam** [nokia/RED#294]
Using RED 3.1.1 on Eclipse with Python 3.6, I can use the Debugger for Test Cases breakpoints, but it skips all breakpoints inside local library. 

In the RED launcher everything is set to default, and shows no missing/error of configuration.
In the Testcase I tried to define the local library both as "Libraries/MyLib.py" and "Libraries.MyLib" - but it did not resolve the issue.

Interesting to note that if switching to PyDev debugger (calling /usr/local/lib/python3.6/site-packages/robot/run.py with relevant robot params) - it does stop on library breakpoints, but not on breakpoints inside Robot testcase.

**Comment by michalanglart** [comment]
RED provides debugger which is able to work on Robot code level while PyDev provides debugger which is able to work on Python code level.

There is a way to combine both tools (RED & PyDev) and be able to debug on both levels in two sessions and it is described in RED User Guide also available online: http://nokia.github.io/RED/help/user_guide/launching/debug/robot_python_debug.html. Please note however that as stated in #255 configuration of this is a bit messy now - this will change in next RED release and there will be small wizard which will allow to setup such session easier.

I think this is quite natural - similarly Java debugger provided by JDT (Java plugin for eclipse) will not be able to suspend on breakpoints in native C++ code called through JNI, however it should be possible to configure a session in which both JDT and CDT (C/C++ plugin for eclipse) can be used to debug on both levels.

**Comment by michalanglart** [comment]
Please have a look at version 0.8.12 as it provides easier way to create launch configuration capable of starting RED & PyDev debugging sessions: see #255 and updated topic in user guide

**Comment by manosnoam** [comment]
Thank you, it works well with the new red-pydevd package.
I've submitted a new issue, while getting permission denied if installing red-pydevd with eclipse UI: #305
