### ISSUE TITLE
Null Pointer Exception when revalidating model

### ISSUE THREAD

**Issue by yann-mk** [nokia/RED#296]
In RED 0.8.11, parsing fails with:

    An internal error occurred during: "Revalidating model".
    java.lang.NullPointerException

with the following code

```robotframework
*** Keywords ***
My KW
    [Arguments]    ${my_arg}
    \   ...     Some Keyword
```
* I've found the error when deleting the loop inside the keyword definition line by line...

**Comment by michalanglart** [comment]
Fixed in 0.8.12
