### ISSUE TITLE
Customizing code assist 

### ISSUE THREAD

**Issue by smalhotra21** [nokia/RED#298]
Hello,

Starting to use RED for our automation in Robot - great tool, and is very helpful - specifically with debugging and execution.

However, I have the following requirement for the code assist feature in RED.

Our keywords have the following syntax:

      <genericKeyword>  <featureName> <subFeatureName> <args>

Example:

      open browser about: firefox remote_url=…..

       open connection telnet <ip> <port>

       open connection ssh <ip> <port>

Now when the user types "open" and hits CTRL-SPACE,  we want to show up only "browser" and "connection" only,  not "open browser" and "open connection telnet" and "open connection ssh".

Is there a way to extend / customize / intercept the code-complete logic that is being used for keywords in RED.

Thanks

**Comment by michalanglart** [comment]
Hi,

this requirement is not very clear to me.

Regarding your example: what is `<featureName>` and `<subFeatureName>`? Are they first arguments to `<genericKeyword>` or are they part of keyword name? You showed couple of examples but I don't know how do they relate to your syntax in the definition. Is `about:` the `featureName` or a `subFeatureName` or maybe `browser` is a `featureName`?

> Now when the user types "open" and hits CTRL-SPACE, we want to show up only "browser" and "connection" only, not "open browser" and "open connection telnet" and "open connection ssh".

I don't understand the logic here. Currently the assistant presents the list of entities (e.g. keywords) witch matches to what is currently being written by the user. This is common logic in probably every single editor providing such feature. What's the logic behind: "show `Browser` because you typed `Open`"?

Last but not least: how does it improve the way of work? If you want `Open Browser` to be shown then why not write `OB` or `Browser` instead of `Open` then show assistant (or have it automatically shown depending on RED preferences) and choose `Open Browser`?

> Is there a way to extend / customize / intercept the code-complete logic that is being used for keywords in RED.

Currently not. It is doable however when agreed how does the API should look like.

**Comment by smalhotra21** [comment]
Hello,

> Regarding your example: what is \<featureName> and \<subFeatureName>? Are they first arguments to \<genericKeyword> or are they part of keyword name? You showed couple of examples but I don't know how do they relate to your syntax in the definition. Is about: the featureName or a subFeatureName or maybe browser is a featureName?`

featureName and subFeatureName are not arguements, but part of the keyword. So, our keyword has the following syntax:

	<genericKeyword> <featureName> <subFeatureName> args
    
We are using robot for telecommunications. So, as an example, a \<genericKeyword> would be "Create:, a \<featureName> could be "vlan", "ipInterface", "ospfInterface' and within each \<featureName> there would be more keywords. 

>>Now when the user types "open" and hits CTRL-SPACE, we want to show up only "browser" and "connection" only, not "open browser" and "open connection telnet" and "open connection ssh".

> I don't understand the logic here. Currently the assistant presents the list of entities (e.g. keywords) witch matches to what is currently being written by the user. This is common logic in probably every single editor providing such feature. What's the logic behind: "show Browser because you typed Open"?

> Last but not least: how does it improve the way of work? If you want Open Browser to be shown then why not write OB or Browser instead of Open then show assistant (or have it automatically shown depending on RED preferences) and choose Open Browser?

What we are trying to solve the issue where we have 1000's of keywords. Based on the keyword format above, each \<genericKeyword> \<featureName> combo, could have 100's of keywords. From the example above, if the user types "Create" and CTRL-space, it would show all the "vlan" (100's) keywords first, and then all the "ipInterface" (100's) keywords, and so on. So, what we are trying to see if there is a way to that if the user enters "Create" + CTRL-SPACE, then we only show "vlan", "ipInterface", "ospfInterface" as the options, and then depending on what they select (lets say "vlan") and hit CTRL-SPACE, we show only the 100's of keywords starting with "Create vlan".

We could change our keywords to have the format:

	<featureName> <genericKeyword> <subFeatureName> args

But, the same issue hold where typing "vlan" + CTRL-SPACE would show 100's of options, and the requirement defined above would still help.

Thanks.

**Comment by michalanglart** [comment]
Hi,

thank for clarifying. We'll talk trough this issue and investigate what could be done

**Comment by michalanglart** [comment]
Hi,

sorry for the delay but we eventually digged your issue from our backlog. Do you still consider it valid and need it?

Would you be able to provide for example a resource file with some sample of your keywords which would give us an overview?

**Comment by michalanglart** [comment]
Seems that this is no longer needed, please reopen if still interested in it
