### ISSUE TITLE
Very slow performance of RED addon for many TestCases

### ISSUE THREAD

**Issue by ifar** [nokia/RED#30]
**Summary**
An Eclipse is frozen, for a few seconds, after navigating through .robot file which contains a lot of TestCases inside. So the RED plugin for the real project is unusable.

**Description**
I used RobotFramework in PyCharm. By PyCharm Robot's addon is not so satisfying. 
So I'd like to switch to eclipse and use RED addon as well.
After install Eclipse Mars and RED addon, and after move my existing test project, the Eclipse is frozen, after navigating through the .robot file with my TestCases.
I already have around 400 TestCases.
There is around 3700 lines of code in this .robot file.

**Root Cause**
The problem described below is reachable only when I reduced number of TestCases of a half (from 400 TCses to 200 TCses, from around 3700 lines of code to 1850). 
Perhaps after open the .robot file in Eclipse (using ROBOT RED addon), and after slide a few lines down, and click on the current line, Eclipse is frozen, and _Remote System Explorer Operation_ information is displayed with progress bar in the right down corner. I takes around 10 seconds...

But when I have my whole project (3700 lines of code), navigation through the .robot file is not possible due to fact that Eclipse doesn't respond.

Additionaly, I increased the available memory for the Eclipse in Eclipse's config file.

Only after I decreased number of lines in .robot file to around 300 (from 3700), the navigation was usable. 

**Environment Settings**
ECLIPSE:
Eclipse Java EE IDE for Web Developers.
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

JAVA:
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

Python 2.7.7

Installed plugins in Eclipse:
PyDev - Python IDE for Eclipse 5.1.2
RED - Robot Editor (no idea which version, the information about which version is installed in Eclipse is not displayed anywhere, but the most possible this is 0.6.5 (from 8th of June))

Windows 8
Intel Core i5-4590 CPU 3.3GHz 
20GB RAM
System type: 64-bit

**Comment by adam-wypych** [comment]
Hi,

As I understand You are using Remote System Explorer (RSE) plugin. If yes, then did You tried edit Your test suite file on Your local machine?

Can You check if You updated Your eclipse.ini file as described in https://github.com/nokia/RED/blob/master/release.md#notes

Anyway thanks for really good description. About RED version You can find it in menu Help->About when You click on RED button/icon.

Best Regards,
-Adam.

**Comment by ifar** [comment]
Hi Adam,
Thank you for your fast response!
Previously, I didn't update the eclipse.ini file, according to the link (pasted by you).
So I made this changes, and results are the same as previously.
Eclipse still freezes during navigating through the .robot file (with TestCases).
Additionally, I turned off the RSE plugin, and results are still the same.
More than that, I set an enormous number of memory space for eclipse (in eclipse.ini file) just for test if maybe results could be better, but it didn't...

So the reason should be different.

Pozdrawiam:
Rafał

**Comment by KrzysztofJozefowicz** [comment]
Hi
Just to be clear, the file with big amount of testcases is stored locally (on your HDD),not on network(shared drive,rse,etc.)?

**Comment by ifar** [comment]
Yes, I'm working on files stored locally.
It's indeed strange, because, when I increased number of lines to 150 in .robot file (this is good number, when Eclipse doesn't freeze), and when I tried to type some Robot's KeyWord, after type every letter of this KeyWord, Remote System Explorer Operation event is turned on. So After type perhaps: Compare CPU usage, the RSEO is started 17 times!
I'm completely newbe in Eclipse. Previously I used PyCharm to create/maintain RobotFramework tests.

**Comment by KrzysztofJozefowicz** [comment]
Thanks, we will look into it, for last verification - can you download RED Product (which is clean Eclipse with RED) to be sure that RED and not any other Eclipse plugins is the problem here?

**Comment by ifar** [comment]
I'm able to install only one eclipse version on my station, Eclipse Mars, which version I described above.
My RED plugin details:
![red details](https://cloud.githubusercontent.com/assets/6534592/17203277/c9048306-549e-11e6-9b6e-e2e24a23f010.png)

**Comment by adam-wypych** [comment]
@ifar You can download product - means the application with preinstalled RED feature. Here You have link for version 0.6.5 - https://github.com/nokia/RED/releases/download/0.6.5/RED_0.6.5.20160707110148-win32.win32.x86_64.zip .

**Comment by ifar** [comment]
Dear ada-wypych and KrzysztofJozefowicz,
I downloaded RED product with pre-installed RED feature.
The problem has been tested so carefully and the exact root cause has been found!
Numer of TestCases is not a problem for RED. Problems occur for very long lines, where KeyWord contains a lot of arguments!
Two TestSuites have been created with 100 TestCases for each Suite.

In TestSuite1.robot, these arguments have been concatenated using multiple lines with "..." separator.
For this TestSuite, navigation is very, very slow, but this navigation is possible. 
Try to type some code, it is possible, but takes a lot of time.

In TestSuite2.robot arguments have been typed into one line. Results are worse, because navigation is not possible, RED doesn't respond after any update.

Please test these TestSuites and verify it on yours side.

Regards!

[TestSuite.zip](https://github.com/nokia/RED/files/388188/TestSuite.zip)

**Comment by adam-wypych** [comment]
@ifar Well done job, thanks. We will check it.

**Comment by KrzysztofJozefowicz** [comment]
Hi
from initial debug,it looks like code coloring is the issue here (on custom build without coloring,performance was ok). This part of functionality will need to be refactored but will simplify internal code and logic although not a simple and short task.

**Comment by ifar** [comment]
OK,
Thank you for the answer.
There is anything what can I do now? Perhaps, test it on my side, without the coloring feature?

**Comment by KrzysztofJozefowicz** [comment]
Hi
We need few days to test changes,there should be fix for 0.6.5 somewhere at the end this week.
If you can't wait,the only way is to refactor testsute (at least split to 2 separate files).

**Comment by ifar** [comment]
OK, So I'm waiting for the results of the newest fix ;)

**Comment by KrzysztofJozefowicz** [comment]
released in 0.7.0
