### ISSUE TITLE
How to upgrade Robot Frame Work 

### ISSUE THREAD

**Issue by acdbrn69** [nokia/RED#300]
So I have a question, first off love RED, but noticed I am using Robot Framework 3.0.4 and I want to use 3.1.1 (which I just upgraded) how do I configure that?

**Comment by michalanglart** [comment]
I don't  know exactly what you mean: RED is using Robot Framework in version installed in your python. If you happen to upgrade RF while RED was running and it still shows that it is using 3.0.4 then just please restart RED.

**Comment by acdbrn69** [comment]
Thanks that didn't work so what did was I went to preferences -> robot framework -> installed framework clicked on `Discover` it found it and I selected and `apply and close`
