### ISSUE TITLE
Variable mappings for Remote Library imports

### ISSUE THREAD

**Issue by efgruber** [nokia/RED#303]
While the import of resource files and libraries with variables from red.xml works fine
(for details see http://nokia.github.io/RED/help/user_guide/working_with_RED/variable_mapping.html)

I've encountered a problem with variables within the URI of a remote library

`Remote URI is invalid: Illegal character in authority at index 7: http://${remote_library}/efxts/`

![error](https://user-images.githubusercontent.com/40423510/58103391-2c262200-7be3-11e9-9721-647fae311e0d.jpg)

RED.xml validation only variables
![red xml settings](https://user-images.githubusercontent.com/40423510/58102748-18c68700-7be2-11e9-926a-72ea9923d51b.jpg)

the execution within robotframework itself works in both ways - is there a way to avoid this problem for validation also?

**Comment by modrz** [comment]
Hi,
In current version variable mapping works for import paths only. 
We have to extend it to Remote imports to make validation work like you described.

**Comment by michalanglart** [comment]
Released in 0.8.13

**Comment by efgruber** [comment]
Hi,
I've just tested this feature with 0.8.13.
Works as expected with variables defined in red.xml like
`<projectConfiguration>
    <configVersion>2</configVersion>
    <relativeTo>PROJECT</relativeTo>
    <variable name="${REMOTE_ASTERISK}" value="http://192.168.6.21:8270/"/>
    ...
`

**Additional Question**
I'm not sure if this behaviour is intended, but variables from files like
 ` <variableFiles path="robot-tests/variables/validationOnly.py"/>`
are not considerd for remote library validation?

**Comment by michalanglart** [comment]
> I'm not sure if this behaviour is intended, but variables from files like <variableFiles path="robot-tests/variables/validationOnly.py"/> are not considerd for remote library validation?

No, only variables defined in red.xml are used when resolving paramterized imports. This also applies to your `Remote` case.
