### ISSUE TITLE
"Imported library 'NNN' contains no keywords." after updating to 0.8.12

### ISSUE THREAD

**Issue by alsido** [nokia/RED#304]
After updating to 0.8.12 I have the following issue: the keywords in my custom Python libraries are not recognized any more and a warning message "_[ WARN ] Imported library '....' contains no keywords._" is displayed after testrun start.

My Python libraries look like this:

```
import this
import that

from robot.api.deco import keyword

class Library():
    def __init__(self):
        # do init

    @keyword('Get Text')
    def get_text(self):
        # do get text
```
It seems that the problem is caused by XML-RPC server. I had an issue similar to #244. Now i observe the following:

- starting RED without starting `robot_session_server.py` and without the `-Dred.connectToServerAt=127.0.0.1:15000` line in RED.ini leads to the issue described above.
- starting RED after starting `rebot_session_server.py` and the configuration line in RED.ini leads to the following error:
```
An internal error occurred during: "Reading available frameworks".
RED python session problem. Following exception has been thrown by python service:
Traceback (most recent call last):
    File "C:\Program Files\RED\robot_session_server.py", line 40, in inner
        result['result'] = func(*args, **kwargs)
    File "C:\Program Files\RED\robot_session_server.py", line 62, in inner
        return func(*args, **kwargs)
    TypeError: check_server_availability() takes 0 positional arguments but 1 was given
```

RED.ini has the following content:
```
-startup
plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.551.v20171108-1834
--launcher.appendVmargs
-vmargs
-Xms512m
-Xmx2g
```

**Comment by modrz** [comment]
Hi,

`rebot_session_server.py` and other python files were updated in **0.8.12**, so you have to copy current versions to your directory `C:\Program Files\RED` to use `-Dred.connectToServerAt=127.0.0.1:15000`

Can you provide exact error you get when you don't use `-Dred.connectToServerA`t switch?

What is your Python version?

Does you temporary directory contain any non-asci characters? You can check it with:
`echo %TMP%`
`echo %TEMP%`

**Comment by alsido** [comment]
There are error messages at all. But when I start a test, there are warnings for every custom python library I use, the test starts and then fails because of "_No keyword with name xxx found_." If I realod my libraries in _Robot Referenced libraries_ there are no error messages either, RED just shows zero keywords (in brackets after library name).

I have Python 3.6.
Temporary directory has no non-asci acharacters, it's "standard" `c:\Users\username\AppData\Local\Temp`

I have updated python files to the new versions, but the issue persists.

**Comment by alsido** [comment]
If I re-add a library to red.xml and reload it in Robot Referenced libraries then I get the following error:
```
Library specification generation problem

Problem occurred during generating libdoc for 'Library' library located at 'C:\Workspace\Tests\Project\Library\Library.py'.
Unable to communicate with XML-RPC server
```

**Comment by modrz** [comment]
Messages like `No keyword with name 'xxx' found.` come from Robot.
Do you also get console errors like `Importing test library 'SomeLib' failed: ModuleNotFoundError: No module named 'SomeLib'`?

What is you command line printed in first line in console? 
Does it work the same when your run the test not from RED but from terminal?
Is library path correct when you re-add it to red.xml?

**Comment by modrz** [comment]
You can also try to enable server console as described in http://nokia.github.io/RED/help/user_guide/diagnostics.html
Try to reload your library then.

**Comment by alsido** [comment]
Yes, there is a module not found error, when I start from the command line. 

The pathes are (were) correct (and 0.8.11 worked fine with them). I tried to re-add them again (which didn't work several times last day) and it worked out! I don't know what was different this time.

However, the path for libraries in project folder is now saved as f.e. `Project/Library/Library.py` and with 0.8.11 it was just `Project/Library`. And for Selenium it's the full path like `C:/Program Files/Python36/Lib/site-packages/SeleniumLibrary/__init__.py`.

**Comment by michalanglart** [comment]
The paths are stored differently in red.xml starting with 0.8.12. However RED should automatically detect that you have red.xml in the older format and ask you to update it.

**Comment by alsido** [comment]
Yes, a message that "workspace was written with an older verision of the product and will be updated" 
is displayed whenever I start 0.8.11 after 0.8.12 or 0.8.12 after 0.8.11

But probably red.xml is not updated.

**Comment by michalanglart** [comment]
This is not a message about red.xml but about workspace. It does not come from RED but from eclipse and you're seeing it because RED product has updated platform in 0.8.12 (Eclipse Photon was used, now Eclipse 2018-09 is used by product).

I was talking about older red.xml detection. Once you open project with older version of red.xml (it has `configVersion=1` tag inside the file) you should be presented with following popup:

![auto_update](https://user-images.githubusercontent.com/14932410/58314390-b2bf4700-7e0f-11e9-9aab-51c0eea5c2a5.png)

Once you click OK all paths stored in red.xml will be updated to new form.

**Comment by alsido** [comment]
Ach, okay. Such popup wasn't displayed.

**Comment by michalanglart** [comment]
Hi, does it 0.8.12 works for you? Did you had your red.xml converted regarding library paths?

**Comment by alsido** [comment]
Yes, it finally works after some tinkering.

**Comment by michalanglart** [comment]
Ok, closing
