### ISSUE TITLE
Installing redpydevd Permission denied: run with --user to resolve

### ISSUE THREAD

**Issue by manosnoam** [nokia/RED#305]
[nmanos@nmanos red_pydevd_package]$ python3 -m pip install --upgrade --no-index dist/red-pydevd-1.0.0.tar.gz
Processing ./dist/red-pydevd-1.0.0.tar.gz
Building wheels for collected packages: red-pydevd
  Building wheel for red-pydevd (setup.py) ... done
  Stored in directory: /home/nmanos/.cache/pip/wheels/21/2b/39/a77a040438db5e2d918c2ee50b7a3a1263f9b016dbba609b3f
Successfully built red-pydevd
Installing collected packages: red-pydevd
  Found existing installation: red-pydevd 1.0.0
    Can't uninstall 'red-pydevd'. No files were found to uninstall.
  Can't roll back red-pydevd; was not uninstalled
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/redpydevd'
Consider using the `--user` option or check the permissions.

[nmanos@nmanos red_pydevd_package]$ python3 -m pip install --upgrade --no-index dist/red-pydevd-1.0.0.tar.gz --user
Processing ./dist/red-pydevd-1.0.0.tar.gz
Building wheels for collected packages: red-pydevd
  Building wheel for red-pydevd (setup.py) ... done
  Stored in directory: /home/nmanos/.cache/pip/wheels/21/2b/39/a77a040438db5e2d918c2ee50b7a3a1263f9b016dbba609b3f
Successfully built red-pydevd
Installing collected packages: red-pydevd
Successfully installed red-pydevd-1.0.0

**Comment by michalanglart** [comment]
Thanks for reporting: we havent found that one. Indeed installing into system packages under linux requires root access rights.

**Comment by michalanglart** [comment]
As a workaround the package redpydevd can be installed manually into python:

1. copy `red_pydevd_package` folder from https://github.com/nokia/RED/tree/master/src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/main/python/scripts
2. `cd red_pydevd_package`
3. `python setup.py sdist --formats=gztar`
4. `python -m pip install --upgrade --no-index dist\red-pydevd-x.y.z.tar.gz --user`

Once it is installed in python distribution the wizard will not try to do it again

**Comment by manosnoam** [comment]
Eventually I used sudo, since even when using --user manually in linux console (not in eclipse), red-pydevd was installed, but in eclipse UI it still returned permission denied.

**Comment by michalanglart** [comment]
`sudo` for installing the package or for RED?

**Comment by manosnoam** [comment]
sudo for the package (eclipse is already installed, probably with sudo too).

**Comment by michalanglart** [comment]
Corrected in 0.9.1
