### ISSUE TITLE
Which Eclipse should install

### ISSUE THREAD

**Issue by maheshbabubokkisam** [nokia/RED#306]
Latest Eclipse down-loader asking/showing to install different IDE's like Java, PHP, web, etc....

[https://wiki.eclipse.org/images/7/7d/OomphSimpleInstaller2.png](https://wiki.eclipse.org/images/7/7d/OomphSimpleInstaller2.png)

So which one should install

**Comment by michalanglart** [comment]
Hi,

Those are not "different IDE's" actually. All of them are eclipse platform + set of preinstalled features for different kind of requirements. You may also download clean platform and install needed features by yourself.

From RED perspective it doesn't matter. You can install RED in any of these. Just ask yourself if you need for example a support for Java, C++ or PHP in your installation. If you want to use RED only for writing and launching Robot tests then you may simply download RED as a product (eclipse platform + preinstalled RED feature) from here: https://github.com/nokia/RED/releases/tag/0.8.12 (choose one of RED_0.8.12.20190521072503-xxx.zip depending on your system)
