### ISSUE TITLE
Make Error field in Execution view visible only when needed

### ISSUE THREAD

**Issue by alsido** [nokia/RED#307]
Is it possible to make/implement that the error field (with "AssertionError") in Execution view is only visible when a failed keyword is clicked?

<img src="https://cloud.githubusercontent.com/assets/12131969/22585176/6154a3d6-e9ee-11e6-9879-7b3d3588669b.png">
(image taken from #76).

PS. Nice to have is also text wrapping in this field. Now it's always one line but there is enought height for three lines.

**Comment by michalanglart** [comment]
Sure, looks doable and rather easy.

**Comment by michalanglart** [comment]
Provided in 0.8.13
