### ISSUE TITLE
Red Documentation links are broken

### ISSUE THREAD

**Issue by Agentnibs** [nokia/RED#318]
It seems something has broken the links for the Red documentation. I checked yesterday and I was able to access them (2019-7-17) but now all I'm getting is 404 errors.

**Comment by michalanglart** [comment]
Hi,

yes, we've noticed that. We started release today however we've run into some troubles. It's going to be fixed tomorrow.

This online documentation is generated from RED help system. You can always have the same content right inside your eclipse/RED installation: choose `Help` menu from main toolbar then `Help Contents` and `RED Robot Editor User Guide`

**Comment by michalanglart** [comment]
Online help is working again as the release was done
