### ISSUE TITLE
Handle environment variables in red.xml for referencedLibrary

### ISSUE THREAD

**Issue by stephanieleclerc** [nokia/RED#321]
Hi,
I would like to use a system environment variable to specify libraries path inside the referencedLibrary section of the red.xml file.
Something like this...

```
<referencedLibrary type="PYTHON" name="AngularJSLibrary" path="%LOCALAPPDATA%/Programs/Python/Python37/Lib/site-packages"/>
<referencedLibrary type="PYTHON" name="SeleniumLibrary" path="%LOCALAPPDATA%/Programs/Python/Python37/Lib/site-packages"/>
```

My team and I want to use version control on this project and right now, we have to edit the path in the red.xml for each user. Is there a way to do this ? 

Thanks in advance for your help!

**Comment by michalanglart** [comment]
Hi,

using system env variables is not possible there. However I think it should be achievable with other means. Let me check my idea and I'll get back here with the description if the idea would turn out to work properly.

**Comment by michalanglart** [comment]
It seems that my idea is working so here it is:

When library is added to red.xml RED will check if it is located in workspace or not. Depending on the outcome it will be written with workspace-relative path or absolute one. The problem with the latter is that it is not portable between different users. Now the idea is to use eclipse `path variables` mechanism together with linking.

Follow this example to see how it works:
1. We're creating some location external to workspace. For example:
```
d:
mkdir external
cd external
mkdir my_external_library
```
2. Under `D:\external\my_external_library` we're putting some library e.g. `external_lib.py`
3. You can download `external` directory with content from here: 
[external.zip](https://github.com/nokia/RED/files/3434551/external.zip)
4. Go to RED and go to preferences: `General -> Workspace -> Linked Resources`
5. Create new `path variable`: name it `EXTERNAL` and make it point to `D:\external`

![external_var](https://user-images.githubusercontent.com/14932410/61932483-cf990780-af83-11e9-8907-e0fc3f584dab.png)

6. Create `example` Robot project
7. Create `libs` directory inside `example` project
8. Select `libs` and open context menu
9. Click`New -> Folder`
10. Expand `Advanced >>` button
11. Choose `Link to alternate location (Linked Folder)`
12. Click `Variables..` button and choose `EXTERNAL` variable
13. Type `\my_external_library` after the variable to have something like this:

![external_link](https://user-images.githubusercontent.com/14932410/61932833-9e6d0700-af84-11e9-899a-1f3d7bc70376.png)

14. Click `Finish` - the linked folder will be created. You can think of it like it is a `symlink` but on the level of `Eclipse File System`. It does not change any structure of your project. It will just add an entry (presented below) into `.project` file (thus the file should be shared across the users and needs to be under version control system in case you're using it):
```
	<linkedResources>
		<link>
			<name>libs/my_external_library</name>
			<type>2</type>
			<locationURI>EXTERNAL/my_external_library</locationURI>
		</link>
	</linkedResources>
```
15. Expand `libs/my_external_library` folder in `Project Explorer`
16. Open context menu on `external_lib.py` and click `Robot Framework -> Add library to red.xml`
17. The library will be added but with absolute path (maybe this should be changed by us)
18. Open source of `red.xml` file and change `path` attribute into relative path `example/libs/my_external_library/external_lib.py`

This way we have a relative path written in `red.xml` plus additional path in `.project` file which uses path variables which can be specified differently for each user in hers/his environment. This however does not pollute the files under version control with absolute paths entries.

All should now work - at least in my case of `example` project it does work.

Here you can download the project already configured the way described above:
[example.zip](https://github.com/nokia/RED/files/3434653/example.zip)

If you would import the project without having `EXTERNAL` path variable defined in preferences then you will see yellow exclamation mark on `my_external_library` folder.

**Comment by michalanglart** [comment]
Hi,

does the solution with linking and eclipse variables work for you? Have you tried it?

**Comment by michalanglart** [comment]
We'll document the solution above in user guide with next release

**Comment by michalanglart** [comment]
The solution described above is now incorporated into user guide from 0.9.0:  http://nokia.github.io/RED/help/user_guide/project_config/libraries_abs_paths.html
