### ISSUE TITLE
Problem importing varibale files (TypeError in robot_session_server.py)

### ISSUE THREAD

**Issue by alsido** [nokia/RED#323]
Has anything been changed regarding `robot_session_server.py` in 0.8.13? I got the following error message after update:

> Problem importing variable file 'Config/Variables/global_variables.py'. Following exception has been thrown: Traceback (most recent call last): File "C:\Program Files\RED\robot_session_server.py", line 42, in inner result['result'] = func(*args, **kwargs) File "C:\Program Files\RED\robot_session_server.py", line 91, in inner return to_call(*args, **kwargs) File "C:\Program Files\RED\robot_session_server.py", line 64, in inner return func(*args, **kwargs) TypeError: get_variables() takes 2 positional arguments but 3 were given

**Comment by michalanglart** [comment]
Yes, the file has changed in numerous ways between 0.8.12 and 0.8.13 as visible here in history of a file:

https://github.com/nokia/RED/commits/master/src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/main/python/scripts/robot_session_server.py

If you're starting `robot_session_server.py` on your own and connect RED to it then you have to pay attention for that file when updating RED as it could be updated too.

**Comment by alsido** [comment]
Oh right, sorry, I looked [here](https://github.com/nokia/RED/tree/master/src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/main/python/scripts) and saw "last month" but expected something like "3 days ago" and "last month" was long ago for me so I didn't regard it at all.
