### ISSUE TITLE
CoreException with Eclipse 2019-06 

### ISSUE THREAD

**Issue by puraner** [nokia/RED#325]
Using Eclipse 2019-06 and RED causes org.eclipse.core.runtime.CoreException: 

- No property tester contributes a property org.robotframework.red.view.execution.node.kind to type class org.eclipse.jface.text.TextSelection
- No property tester contributes a property org.robotframework.redxml.validation.isInternalFolder to type class org.eclipse.jface.text.TextSelection
- No property tester contributes a property org.robotframework.selection.allElementsHaveSameType to type class org.eclipse.jface.text.TextSelection
- .... 

I thinkt the logged messages refer to the changes due to this bug report: https://bugs.eclipse.org/bugs/show_bug.cgi?id=545270

**Comment by michalanglart** [comment]
Hi,

we are aware of this issue. I've recently wrote about it: https://github.com/nokia/RED/issues/322#issuecomment-517146876

**Comment by michalanglart** [comment]
Fixed in 0.9.0
