### ISSUE TITLE
RED : macOS : Preferences : Installed framework path - Not working 

### ISSUE THREAD

**Issue by vaibhavp2** [nokia/RED#327]
Hi,
It would be really helpful if someone can provide details for resolving the issue on Eclipse 2019-06 (4.12.0). I am always getting error saying that "does not seem to be a valid python directory" even if it has robot framework installed.
I have python 3.7 installed along with default 2.7 on mac. 
Please refer to all possible images about this and let me know the steps on how to resolve this.
**Note**:  I am very much new to mac and Robot framework, I have just started a month ago. So please bare with me and if possible just don't link/refer to any other issue unless it has all detailed steps with exact problem resolved.
Thank you very much !

<img width="1437" alt="Screen Shot 2019-08-21 at 11 54 44 AM" src="https://user-images.githubusercontent.com/43592317/63454044-a303ce80-c40f-11e9-80a9-bcfa289048c5.png">
<img width="775" alt="Screen Shot 2019-08-21 at 11 57 33 AM" src="https://user-images.githubusercontent.com/43592317/63454045-a303ce80-c40f-11e9-9968-0006fa151660.png">
<img width="694" alt="Screen Shot 2019-08-21 at 11 58 36 AM" src="https://user-images.githubusercontent.com/43592317/63454046-a303ce80-c40f-11e9-8612-3f6c41fbf938.png">
<img width="1435" alt="Screen Shot 2019-08-21 at 11 52 10 AM" src="https://user-images.githubusercontent.com/43592317/63454047-a303ce80-c40f-11e9-93b6-dc81b72c93b9.png">

**Comment by michalanglart** [comment]
Hi,

At `Installed Frameworks` preference page you are defining paths to places where python interpreter is installed - the executable file of this interpreter to be precise. In your case I can see that there is one valid path `/usr/bin` - in this directory there is a `python` executable file (a symlink I guess) probably (or `python2`/`python3`). Either you've added it manually or it was detected by RED because `/usr/bin` is contained in your `PATH` environment variable.

I'm not sure what exactly you're trying to achieve: do you want to add your Python3 installation? In such case you need to locate where is the executable file of this installation and simply add the directory in which it is contained.

The orange color on your `/usr/bin` python interpreter means that there is no RobotFramework installed in it (so the version is `<unknown>`.

**Comment by vaibhavp2** [comment]
Hi @michalanglart : Thank you very much for your response.
I have just created a new Robot project and it had that red.xml file which was showing this error.  So I clicked the preference section and clicked hyperlink from there and tried to add path. I dont know how and why it is unknown when you have robot framework installed under Python3.7 ->site packages - robotframwork 3.1.2. 

So I am looking for any helpful steps that would resolve this issue. It is like, I am not originating this requirement but red.xml wants this path to be configured and that is what I am trying to do. 

When you say "add Python3" does that mean I have to add Python3.7 executable path > instead of Robot framework path under site packages of python 3.7? I thought what message is suggesting is to give the path of python where Robot framework is installed and that what I was giving. In fact if you see images, I tried 3 different path for 3.7 hierarchy.  All of them shows  "does not seem to be a valid python directory".

Let me know if this helps or I can have more details, just let me know what you need from my eclipse.

Thanks again for your feedback !

**Comment by michalanglart** [comment]
> When you say "add Python3" does that mean I have to add Python3.7 executable path > instead of Robot framework path under site packages of python 3.7? I thought what message is suggesting is to give the path of python where Robot framework is installed and that what I was giving.

Yes, this mean that you need to add a path to directory where python executable is contained. Maybe message could be more clear but it tells about invalid Python directory - nothing about Robot. The message above the table also tell to "add/remove (...) location of **Python interpreter** with Robot installed".

Once there is a path installed RED will:
- mark it red when there is no python executable installed
- mark it orange when there is a python executable installed but there is no Robot found for it

**Comment by vaibhavp2** [comment]
Thank you @michalanglart. That helps I tried with same location as above but just pointed to (bin) :  .../verisons/3.7/bin/python3 and it picked up correct RF version 3.1.2 and now doesn't show up any error message.
