### ISSUE TITLE
First column resizes on window/dialog resize up to no longer visible

### ISSUE THREAD

**Issue by MAPJe71** [nokia/RED#328]
Open `Window` > `Preferences` > `Robot Framework` > `Launching` > `Default Launch Configurations`.
First column (i.e. `Variable`) of `Environment variables to set:`-table of `Environment tab`-group resizes (narrows only) when the `Preferences`-window/dialog is resized up till no longer being accessible.

![REDPluginBug](https://user-images.githubusercontent.com/6494038/63686314-de344200-c801-11e9-907f-b2f4d84721f6.gif)

**Comment by michalanglart** [comment]
Hi,

What's your OS and Eclipse version?

**Comment by michalanglart** [comment]
For now we can cofirm this behaviour under GTK 3.18 and 3.22. This is not reproducing under GTK 2.x nor under Windows platform.

**Comment by MAPJe71** [comment]
Ubuntu 18.04.3 LTS
Eclipse 2019-06

**Comment by michalanglart** [comment]
This is fixed in 0.9.0
