### ISSUE TITLE
Cannot add new row from test cases view

### ISSUE THREAD

**Issue by xyngfei** [nokia/RED#33]
When i tried to create a new test suite from new project, add a new row from test cases view, it show the Java.Lang.NullPointerException issue when i save the file. 
 
Tested environment
OS: Win2012
Eclipse : 4.5

**Comment by adam-wypych** [comment]
Hello,

Can You add `.log` file from workspace where project exists to https://gist.github.com/?

BR,
-Adam.

**Comment by KrzysztofJozefowicz** [comment]
Hi
Take note that latest version (0.6.5) does not support persistency in keywords and testcases table editors (**any changes in those tables editors will not be visible in source nor saved to file**), only Settings and Variables Table Editors are proper synced with Source. 
I advise you to use Source view for editing TC&KW.
TC&KW sync will be available in upcoming release (there still some minor issues to be polished but main functionalities of KW&TC table editors are ready).

**Comment by xyngfei** [comment]
@adam-wypych 
How to i add .log from workspace? I just create a new robot project and insert robot test suite only.
Can you guide me? 

@KrzysztofJozefowicz 
Glad to hear that, I am waiting the release to be available :)

**Comment by adam-wypych** [comment]
You can add `.log` to something name gist (raw file container) to do this just:
1) Go https://gist.github.com/xyngfei
2) Click button `New gist` on the top right corner of web page
3) Drag & drop `.log` file to web browser - some watermark should appear that You are adding file just like below:
![image](https://cloud.githubusercontent.com/assets/12131969/17920144/de6793f2-69d2-11e6-903e-0e095b26d962.png)
4) When everything will be ok You will see content of the file and it name in text area of the browser.
5) Click button `Create public gist`
6) If everything will be ok when You will put to web browser address https://gist.github.com/xyngfei You will see `.log` file inside Your gist container.

**Comment by KrzysztofJozefowicz** [comment]
released in 0.7.0
