### ISSUE TITLE
Unable to find Node/NPM when running AppiumService. Works in command line/pycharm

### ISSUE THREAD

**Issue by QAthulhu** [nokia/RED#332]
OS: Mac OS X 10.14.6
Python: 3.7.4
Node: 12.11.0
NPM: 6.11.3
Virtualenv: 16.7.5
Robot Framework: 3.1.2
Robot Framework Appium Library: 1.5.0.4
Appium: 1.15.0
Eclipse: Oxygen.3a Release (4.7.3a) (All later versions  as of 10/8/19 are unable to properly display red.xml)
Red: 0.8.13

I'm trying to create a python utility to start and stop the appium server programmatically. I created a python library AppiumUtil.py that imports AppiumService and use start() to start the server.

`from appium.webdriver.appium_service import AppiumService

class AppiumUtil:

    def __init__(self):

        self.appium_service = AppiumService()

    def connect(self):

        self.appium_service.start()`
I then include AppiumUtil as a Library in the Settings section and call the Connect keyword.
When I run a test I get this error:
`AppiumServiceError: NodeJS main executable cannot be found. Make sure it is installed and present in PATH`

Node is already included in my $PATH as /usr/local/bin/

The start() function allows an argument to specify the Node directory, I tried this, and upon running the test again, I get a new error stating the NPM cannot be found, even if it is in the same directory.

Running the test through command line or in pycharm works fine and no issues involved. So this must be an issue with Red.

Also, I configured my red.xml to use Python installed in a virtual environment in Users/[name]/.virtualenvs/myvenv/bin which does not contain Node since that was installed globally. However, I installed Python3 globally and tried updated the xml to use /use/local/bin/ but I get the same error, no Node/NPM found.

**Comment by michalanglart** [comment]
Hi,

can you run this test from RED to see the content of `PATH` variable:

```
*** Test Cases ***
test
    Log    %{PATH}
```

If it's not there have a look here: https://stackoverflow.com/questions/55648312/mac-os-x-mojave-set-environment-variable-permanently

Additionally: 

> Eclipse: Oxygen.3a Release (4.7.3a) (All later versions as of 10/8/19 are unable to properly display red.xml)

This is interesting. Can you tell us what is wrong with red.xml on newer platforms?

**Comment by QAthulhu** [comment]
%{PATH} returns `/usr/bin:/bin:/usr/sbin:/sbin`
Using terminal to echo my $PATH, I get
`/Users/[name]/.nvm/versions/node/v12.11.0/bin:/usr/local/Cellar/maven/3.6.2/bin:/usr/local/Cellar/gradle/5.6.2/bin:/Users/[name]/Library/Android/sdk/bundle-tool:/Users/[name]/Library/Android/sdk/tools/bin:/Users/[name]/Library/Android/sdk/tools:/Users/[name]/Library/Android/sdk/platform-tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`


is there a way to use my system's PATH?

Just checked again, not just red.xml but any Robot file (test suite, resource, etc.)

4.13.0: red.xml using Red editor displays red octagon with error: "Failed to create the part's console" with More Details button that shows [full error message](https://gist.github.com/QAthulhu/1fd1ea40960e77a7f0509dea64733196). 

4.9.0 to 4.11.0:  Displays red.xml using the XML Editor. There is no option in right click > open with menu to use the normal Red editor. Opening any robot file shows a red octagon with an exclamation point and the error: "No editor descriptor for id org.robotframework.ide.tableditor"

4.8.0: Same as 4.9.0

4.3.13: Same red.xml as 4.9.0. Robot files show the red octagon with error "Failed to create the part's console" and a More Details button.

Seems like any version from Photon onwards doesn't work properly.

**Comment by michalanglart** [comment]
Ok, then what value of `PATH` is visible in `Help -> About RED/Eclipse -> Installation Details -> Configuration` in section `*** System environment variables` under `PATH=` entry? Is it also `/usr/bin:/bin:/usr/sbin:/sbin` or your real value visible under terminal?

How do you launch your RED/Eclipse installation?

**Comment by QAthulhu** [comment]
Ok this is strange. No System environment variables section. Only Date, Platform Details, System Properties, Features, Plugin Registry, User Preferences, Current Install Configuration, Security Configuration.

I installed Eclipse by downloading from the site, then dragging to Applications folder. Red was installed via Eclipse Marketplace

**Comment by michalanglart** [comment]
As to the problems with newer eclipse version - we've just resolved some problems occuring in newest eclipse (4.13, 4.12) so it's worth to take a look at it once we release next version. Anyway we'll have a look into those problems you've described.

And back to `PATH` problem: where are your environment variables defined? In `~/.bash_profile` file or in `/etc/paths`? Can you try running eclipse from terminal rather than by double clicking it in GUI?

**Comment by QAthulhu** [comment]
> As to the problems with newer eclipse version - we've just resolved some problems occuring in newest eclipse (4.13, 4.12) so it's worth to take a look at it once we release next version. Anyway we'll have a look into those problems you've described.

Thanks!
> And back to `PATH` problem: where are your environment variables defined? In `~/.bash_profile` file or in `/etc/paths`? Can you try running eclipse from terminal rather than by double clicking it in GUI?
My PATH is defined in ~/.profile. I just tried running eclipse from terminal and the PATH returned is the same one in terminal.

I'm still getting an error running Appium, but not sure if it's still related to Red (though as stated before, it works fine from pycharm and terminal). I got `AppiumServiceError: b''` from running the AppiumService start() function

**Comment by michalanglart** [comment]
Ok, but what about:

```
*** Test Cases ***
test
    Log    %{PATH}
```
?

If your environment variables are set using `.bash_profile` file then this is a file which is read when `bash` starts. So all the env variables you are able to see in `bash` would be available in processes started via `bash`. Once you double click the executable then you will only have environment variables as visible in MacOS `init` process (`launchd`).

I have no clue about this error: `AppiumServiceError: b''`

**Comment by QAthulhu** [comment]
lol sorry messed up the quotes. The PATH that RF sees is the right one since running eclipse from terminal. 

Looked into the error more, it's "Error: Cannot find module 'appium/build/lib/main.js'"
I tried adding the appium installation path to my PATH, closed the terminal, reopened, and opened eclipse again, but still getting the same error

**Comment by michalanglart** [comment]
The error `Error: Cannot find module 'appium/build/lib/main.js` is thrown from `appium_service.start()` method, right? This path is relative so maybe this is something related to the working directory of the process. You've said that it works from command line - does it work regardless in which directory you're starting it or do you need to `cd` to some directory in order to make it work?

RED starts the python process with the tests using path to the project in your workspace as working directory. As of now it is hardcoded and you cannot change it.

If that's the problem then you need to pass proper `main_script` path to `start()` method call.

**Comment by QAthulhu** [comment]
I use cd to go into the directory where the test suite file is. I haven't tried running the test from a different directory. I think I may need to set the `main_script` variable. I just got home, so I won't be able to test it, so I'll get back to you tomorrow. Thanks!

**Comment by QAthulhu** [comment]
Just tried it and it's working now. Providing a `main_script` argument in the `start()` function got it working. Thanks for all the help!

Just curious, why do I need to run Eclipse from the terminal for it to work? My PATH settings are in `~/.profile` so not sure why Eclipse can't find it. Is there a way to fix it?

**Comment by michalanglart** [comment]
BTW I will leave this open for couple of days and will ask you if you can try next RED in newer eclipse and see if the problems you've mentioned with opening the files are gone, ok? :)

**Comment by QAthulhu** [comment]
Alright, thanks for the explanation and all the help!

Sure, I'll test it out again with new RED version :D

**Comment by michalanglart** [comment]
RED 0.9.0 has been released. Can you please check if you still have problems opening files on newer platforms?

The RED as product is build using newest 2019-09 eclipse so I expect there should be no problems with that - at least there are no under Windows/Linux systems

**Comment by QAthulhu** [comment]
Sorry for the delay. Just tried it out with eclipse 2019-09 and Red is working now. I'm able to display the Red.xml and .robot files on Mac OSX

Thanks! I'm closing this issue now

**Comment by michalanglart** [comment]
Great! Good to hear that. Happy testing!
