### ISSUE TITLE
Library keywords imported through use of Plugin not detected.

### ISSUE THREAD

**Issue by friendlyfreedom** [nokia/RED#335]
SeleniumLibrary has the option of extention through Plugins. 

Keywords the SL library is extend with are not detected by RED, thus marking these with a red :bulb:. 

Expected: _Given_ a library is imported like `Library  SeleniumLibrary  plugins=Library;with;arguments`
_Then_ RED should detect the keywords the library is extended with.

A good library to reproduce this issue with is: [SeleniumTestability](https://github.com/rasjani/robotframework-seleniumtestability)

**Comment by michalanglart** [comment]
Hi,

what version of RED are you using? RED is generating library specification files basing on entries in red.xml files not on `Library` imports in suites/resource files. You need to provide arguments for library in red.xml. This was not possible for long time, but with RED 0.9.0 the issue #47 was implemented and it can be done. See: http://nokia.github.io/RED/help/user_guide/project_config/libraries.html - `Dynamic vs static library and library arguments` user guide chapter for more

**Comment by friendlyfreedom** [comment]
Just updated to the latest version and saw the possibility of adding arguments in RED.xml. Added plugins=SeleniumTestability as an argument and works like a charm. Well done everyone!
