### ISSUE TITLE
Debugging and error reporting,An internal error occurred during: "Agent connection server".

### ISSUE THREAD

**Issue by 1348641743** [nokia/RED#336]
Hello, when I debug, I always report the following error。
The following error is reported during debugging
An internal error occurred during: "Agent connection server".
Server error: problem handling agent event
![image](https://user-images.githubusercontent.com/36215871/67257724-e0dcac00-f4bf-11e9-8b6d-988fe996154e.png)

**Comment by michalanglart** [comment]
Hi,

can you please attach the content of the `Console` view? Additionally it would be good to have `.metadata/.log` file inside your workspace.

**Comment by michalanglart** [comment]
No response, closing. Please reopen if logs/errors can be provided
