### ISSUE TITLE
Modify existing syntax in the source file. 

### ISSUE THREAD

**Issue by xyngfei** [nokia/RED#34]
When i create a new test suite, provide the following syntax either in TC/KW as below
${pwd}=     Generate Random String    8    qwer[NUMBERS] 

Something, it will automatically modify the exisitng syntax.
${pwd}=    ${pwd}     Generate Random String    8    qwer[NUMBERS] 

 It is quite irritating whenever i want to commit my code into git. Any suggestion?

**Comment by adam-wypych** [comment]
You get this double text issue from table editor or source?

**Comment by xyngfei** [comment]
@adam-wypych,
Yes, i did it from source menu and i only view it from table menu. 
When is the estimate roll up timeline for next upcoming release?

**Comment by adam-wypych** [comment]
@KrzysztofJozefowicz: Could You response about time?

**Comment by KrzysztofJozefowicz** [comment]
New release should be ready in first weeks of October.

**Comment by KrzysztofJozefowicz** [comment]
released 0.7.0
