### ISSUE TITLE
Report issue

### ISSUE THREAD

**Issue by sivan06** [nokia/RED#341]
When i use robot framework in pycharm, program run successfully but not generate the log and report. please help me

**Comment by michalanglart** [comment]
Hi,

this is the issue tracker of RED Robot Editor which is a plugin to eclipse IDE not to PyCharm, so we cannot help. I don't know if Robot support for PyCharm have some issue tracker but you may look for help on robotframework-users group: https://groups.google.com/forum/#!forum/robotframework-users or you can ask on RobotFramework Slack channel.
