### ISSUE TITLE
RED mac Code gets blurry 

### ISSUE THREAD

**Issue by vaibhavp2** [nokia/RED#342]
I am using RED in mac version 10.15.1 (19B88) Catalina with eclipse Version: 2019-06 (4.12.0) Build id: 20190614-1200.
Whenever I scroll scroll source code file horizontally, I see that whole code gets blurry ( see attached image as sample ). Then I have to click on each sections inside the source file to get to original look and feel. I am not able to read code if I scroll it horizontally. So each time I scroll I have keep on clicking everywhere in same source to get it normal. This is really time consuming for me.

Can you please suggest how to resolve this or provide a fix for it. 

<img width="179" alt="Screen Shot 2019-11-10 at 11 29 27 PM" src="https://user-images.githubusercontent.com/43592317/68563777-4c0d0480-0414-11ea-9690-d92e43d3928e.png">

**Comment by michalanglart** [comment]
Hi,

This looks like a bug in eclipse and this one matches to your description: https://bugs.eclipse.org/bugs/show_bug.cgi?id=548491

Please update eclipse to 2019-06 (4.13) and see if the issue persists.

**Comment by michalanglart** [comment]
Hi, have you updated? Does it work on 4.13?

**Comment by vaibhavp2** [comment]
Hi ,
Thank you for suggestion, it is after the update.
