### ISSUE TITLE
Error in the argsfile listener

### ISSUE THREAD

**Issue by FaustPipeDream** [nokia/RED#343]
I'm running a testcase :
```
*** Test Cases ***
case1
 Log    abc
*** Settings ***
Resource	${R_PATH_PROJECT}/resource/robot/resource.robot
```

And has a error message below:

> Command: "C:\Program Files\Python36\python.exe" -m robot.run --listener C:\Users\itc\AppData\Local\Temp\RobotTempDir1222446095753531741\TestRunnerAgent.py:63060 --argumentfile C:\Users\itc\AppData\Local\Temp\RobotTempDir1222446095753531741\args_98141a4c.arg "C:\Documents and Setting\robot\robot1"
> Suite Executor: Robot Framework 3.0.3rc1 (Python 3.6.5 on win32)
> [ ERROR ] Parsing 'Files\Python36\lib\site-packages\AtfLibrary\atf\runneragent.py;C:\Users\itc\AppData\Local\Temp\MMS_3857395286901672696.mm' failed: Data source does not exist.

I found there has a mistake in the argsfile:

> --listener                                                                                                                
> C:\Program
> Files\Python36\lib\sitepackages\AtfLibrary\atf\runneragent.py;C:\Users\itc\AppData\Local\Temp\MMS_3857395286901672696.mm

If Python has been istalled in C:/Program Files/Pyhton36, in the listener,the space will be replaced by enter and cause this error。
If Python has been istalled in C:/Pyhton36，there will have no mistake.

Red version:0.8.11
eclipse version:4.8.0

**Comment by modrz** [comment]
Hi,

Arguments containing spaces has to be wrapped in quotes in run configurations like this:
![image](https://user-images.githubusercontent.com/22540835/68652587-15c1a900-052a-11ea-9a75-94cbe5d3ad22.png)

Same thing has to be done in command line:
![image](https://user-images.githubusercontent.com/22540835/68652678-499cce80-052a-11ea-917c-470257de87ae.png)

**Comment by FaustPipeDream** [comment]
Thank you,It works! :+1:
