### ISSUE TITLE
Library specification generation problem

### ISSUE THREAD

**Issue by sasasa42** [nokia/RED#344]
When trying to configure the FakerLibrary in the red.xml, the system throws an error. PFA the error logs in the file linked.
https://gist.github.com/sasasa42/cc3eaba1cf6f30858dd943c8c5b82dd1

**Comment by michalanglart** [comment]
Hi,

what are the versions of RED, Python, Robot and FakerLibrary?

**Comment by michalanglart** [comment]
We are able to reproduce it with RED 0.8.10, not in newest version however. This is very similar (the error) to this one: #245 and it was resolved in 0.8.11.

**Comment by sasasa42** [comment]
@michalanglart .Thank you..I updated to the latest RED 0.9.0 and I don't see the issue now. Good!

**Comment by michalanglart** [comment]
Glad to hear! Closing
