### ISSUE TITLE
RobotFramework menu item is not displayed for Robot project in Eclipse with RED plugin

### ISSUE THREAD

**Issue by mpasha** [nokia/RED#347]
I installed the RED plugin in eclipse and created a new robot project. Right click on the project doesn't show the Robot Framework menu.

My friend is able to view the menu item like below.

<img width="253" alt="Screenshot 2019-11-14 at 3 42 14 PM" src="https://user-images.githubusercontent.com/46208064/68845318-30507980-0706-11ea-89a6-fe1a4c45e94f.png">

**Comment by michalanglart** [comment]
Hi, please have a look into #299

**Comment by mpasha** [comment]
> Hi, please have a look into #299

oh yeah, thanks for quick response. Closing the issue
