### ISSUE TITLE
Debugging: Configuring "Maximum characters to display" not working

### ISSUE THREAD

**Issue by ahojuk** [nokia/RED#348]
System:
Ubuntu 18.04.3 LTS
Eclipse IDE for Enterprise Java Developers. Version: 2018-12 (4.10.0)
Python 3.6.8
robotframework==3.1.2
RED - Robot Editor Version: 0.9.0
PyDev - Python Development environment. Version: 7.2.0

In my test cases I have string variables over 10000 characters. 
I would like to edit them in debug view. 
Currently it's not possible because string variables over 10000 characters are truncated .
Changing characters to display max length in Configure Details Pane doesn't have any effect (see screenshot).

![TruncatedStringInDebugging](https://user-images.githubusercontent.com/7523736/68849475-d25a6c80-06da-11ea-9c60-afc9fb3e4e3a.PNG)

**Comment by michalanglart** [comment]
Hi,

this limit has a value of `2048` and it was introduced a little over 3 years ago in order to mitigate OutOfMemoryErrors we've encountered when working with long values.

The bad news is that this value is hardcoded and changing the length you've shown has no effect on it.

**Comment by ahojuk** [comment]
Editing variable values would be handy not only in debugging but also in actual system testing. I could run test case to the breakpoint. Change some testing parameters and continue running to see how system works.
In that way the changes are made in debugging view and I don't need to touch the test script.
Those string variables are holding soap messages that I would like to edit in debug view before posting.

**Comment by michalanglart** [comment]
We are planning to take this setting into account when launching the tests however if you have already executing debugging session stopped then changing the value won't affect anything. You would have to change the value and start the tests again to see this working.

Do you have something against it? It would be technically possible but would complicate the fix and RED vs Agent communication in this rare case when you would need to change the value on-the-fly.

**Comment by ahojuk** [comment]
Nothing against it. Thank You for fixing it! :)

**Comment by michalanglart** [comment]
Released in 0.9.2
