### ISSUE TITLE
Suggestion: convert Help to Wiki pages

### ISSUE THREAD

**Issue by kootstra** [nokia/RED#35]
Part of my standard project evaluation is to have a look at the support tickets and the wiki to understand the maturity of the project. To my surprise this project had no wiki pages. Although it didn't deter me, it was surprising to see that the information one would typically find there is part of the code/release as seperate help files. 

Even though I think the help files are a good addition to the code, I'd think most developers are connected and the wiki makes for a more dynamic and up-to-date help system. So, perhaps the current help pages can be converted to Wiki pages.

**Comment by KrzysztofJozefowicz** [comment]
Help pages mirrors the same content from RED help. If there is a simple way to use already generated md/html files from RED help to be used in wiki, I don't see any objections.

**Comment by kootstra** [comment]
Had a quick look and it seems to me that the contact can quite easily be reused, virtually copy-and-paste from the current MD files. It should be possible to include the images via the raw URL of the image in GitHub repository. 

Will add a few pages in the next couple of days.
