### ISSUE TITLE
Updating RED

### ISSUE THREAD

**Issue by shywitch** [nokia/RED#351]
I was wondering if there was a way to auto update RED when a new update becomes available?

**Comment by michalanglart** [comment]
There is a automatic update mechanism in eclipse: https://help.eclipse.org/2019-09/topic/org.eclipse.platform.doc.user/reference/ref-p2-autoupdate.htm?cp=0_4_1_9 (in short: `Window -> Preferences -> Install/Update -> Automatic Updates`).

**Comment by shywitch** [comment]
Can the update be automatically installed?

**Comment by michalanglart** [comment]
Uhmm... I'm not sure what are you asking about? Your second question looks pretty much the same as the first one but re-phrased. What are you exactly looking for? Update system that will perform installation without your knowledge, a possibillity to update RED via cron-like task, or something different?

**Comment by shywitch** [comment]
From looking at the settings it will download the update but not install it, this is still user driven. I'm hoping there's a way to update and install the new update automatically without the users knowledge as well as any plugins the user has.

**Comment by michalanglart** [comment]
To the best of my knowledge there is no possibility to check, download and install the update without user assistance at some point.

**Comment by shywitch** [comment]
Ok thank you for the help, was hoping for a way to install it then just leave it to update when needed
