### ISSUE TITLE
Incompatibility with RobotFramework 3.2a1

### ISSUE THREAD

**Issue by Snooz82** [nokia/RED#353]
Hi,

Whey testing Red with actual pre Release of RF (3.2a1) i found RED not beeing able to debug these executions anymore.
In 3.2 the parser has been completely reimplemented. 

Regards

**Comment by michalanglart** [comment]
Yes, thanks for reporting. We've started looking into changes for 3.2 but so far nothing has been done on our side. We're planning to have one release before Christmas but it won't be 100% ready for 3.2 - maybe some most important stuff will be fixed.

**Comment by michalanglart** [comment]
The run/debug would be fixed for 0.9.2 with RF 3.2

**Comment by michalanglart** [comment]
This is fixed in 0.9.2. Most new features of RF 3.2 should work, there are still some minor issues to be done to fully support 3.2
