### ISSUE TITLE
Library import error

### ISSUE THREAD

**Issue by ombre42** [nokia/RED#36]
Env - Eclipse Neon, RED 0.6.5, OS X 10.11.5 (El Capitan)
Steps to reproduce:
In the system installation of Python, install SudsLibrary via pip.
Then in a settings table of a test suite file, add an import of SudsLibrary.
Then save or try to do a quick fix of the Unknown 'SudsLibrary' library error.
Select Discover 'SudsLibrary and add to configuration

Expected Result:
Library reference is added to red.xml and error is removed

Actual Result:
Library import problem dialog appears with text: "The path '/library/Python/2.7/site-packages/SudsLibrary' should point to either .py file or python module directory."

There is another choice for the quick fix - Change to 'SudsLibrary'. This gets the expected result. However, the suggested text is the same as was used.

I originally ran into the error when trying to use libraries installed into a virtualenv.

**Comment by adam-wypych** [comment]
Hi,

Did You try to use `Autodiscover` option over the problematic file (see: https://github.com/nokia/RED/blob/master/red_help/user_guide/libs.html.md) ? 
Please note that after library will be add to `red.xml` You need to save it and close\open file on which You use `Automatically discover and add libraries to red.xml` option.

This should help with Your issue.

**Comment by michalanglart** [comment]
See https://groups.google.com/forum/#!topic/robotframework-users/7RPzHW10t_w for more context about this issue.

**Comment by adam-wypych** [comment]
@ombre42 From robotframework-users topic I see all answers for my questions, You do not need to answer it.

**Comment by adam-wypych** [comment]
Can You check with RED 0.7.1? It should works prefectly now.
