### ISSUE TITLE
RED.xml, Variable files,  YAML support missing

### ISSUE THREAD

**Issue by loomanw** [nokia/RED#360]
In red.xml we are able to specify global variabele files.
Currently only *.py files are recognized

Request: enable RED to accept *.yaml as global variable file in red.xml 

https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-file-as-yaml

**Comment by modrz** [comment]
It looks like *.yaml files are already accepted also in red.xml.

You have to select \*.\* extension filter in file selection dialog:
![image](https://user-images.githubusercontent.com/22540835/72706240-cc12c180-3b5d-11ea-8fee-210c26c80545.png)

We can add new extensions to dialog filters as a new entry:
![image](https://user-images.githubusercontent.com/22540835/72706410-42afbf00-3b5e-11ea-9845-d25c5eb2c1be.png)
or combined with \*.py entry:
![image](https://user-images.githubusercontent.com/22540835/72706455-5b1fd980-3b5e-11ea-8171-cc5281fdb1e7.png)

**Comment by loomanw** [comment]
Hi, 

After creating a brand new test case i am unable to reproduce my problem, and sadly must conclude it was a false positive ;) .

Your proposal of adding the extension(s) in any form to the dialog filter would be much appreciated.

Some notes:
Robot Framework 3.1.x only supports *.yaml
Support for *.yml is  only available after release of 3.2 https://github.com/robotframework/robotframework/issues/3195

Is it possible to limit the list of supported extension(s) based on the Framework version in use?
example: 
3.1.x = *.py, *.yaml
3.2.x = *.py, *.yaml, *.yml

Thx for the fast response.

**Comment by michalanglart** [comment]
Implemented in 0.9.3
