### ISSUE TITLE
Keywords in resource file not showing in the Keywords tab

### ISSUE THREAD

**Issue by cpk011** [nokia/RED#362]
I placed Settings, Variables, and Keywords sections to a resource file, which used to be in a robot file.
Now when I open the robot file in RED, Settings, Variables, and Keywords tabs are mostly empty. 
The Source tab shows:

*** Variables ***
${RESOURCES}    ./Resources
*** Settings ***
Resource    ${RESOURCES}/myproject.resource
*** Test Cases ***
...

How can I have other tabs show the content of the resource file?
Thanks.

Peter

**Comment by michalanglart** [comment]
Hi,

I'm not sure if I understand correctly:

You've had file `A.robot` with some variables, keywords etc. and then you moved them to file `B.robot` and added an import of `B` from `A`. Is that correct? 

RED follows the usual convention used in different IDEs that single file = single editor. You cannot edit multiple different files using single editor. Your keywords, settings and variables are there in `B.robot` so you need to open it for editing.

**Comment by cpk011** [comment]
Thank you for the explanation.
