### ISSUE TITLE
Format source doesn't work anymore

### ISSUE THREAD

**Issue by pbbos** [nokia/RED#363]
Hi!

Formatting the source of a .robot file doensn't work anymore in Eclipse.

I'm using Eclipse Oxygen.3a Release (4.7.3.a) and Red - Robot Editor 0.9.3.

Best regards,

**Comment by modrz** [comment]
Hi,

Have you updated RED or is it fresh install?
Do you have formatting enabled in RED preferences?

You can find related preferences in:
**Robot Framework -> Editor -> Code Formatter
Robot Framework -> Editor -> Save Actions**

**Comment by pbbos** [comment]
I've updated RED.
Here are two sceenshots of my settings.

![image](https://user-images.githubusercontent.com/19855997/74922172-21492980-53cf-11ea-8b86-63b12145bd55.png)
![image](https://user-images.githubusercontent.com/19855997/74922237-345bf980-53cf-11ea-99be-0664e8d5de21.png)

**Comment by modrz** [comment]
Please send us more information about your setup.

From which version you have updated to 0.9.3? 
What is your project configured?
Does it have Robot nature etc.?
Do you open *.robot file in Robot Table Editor or in Text Editor?
Can you provide sample test code it is not formatted or screenshots with source editor?
Have you tried the same in newer Eclipse version?

**Comment by michalanglart** [comment]
Hi,

does it work for you or not?

**Comment by michalanglart** [comment]
Closing as no tips for reproduction are provided
