### ISSUE TITLE
Request about set up of latest RED with Python

### ISSUE THREAD

**Issue by donmartin483** [nokia/RED#364]
I wanted to know what software is compatible with RED 0.9.3 with respect to Eclipse and Python.
In the past, I appeared to have difficult with RED and Python (version 3).

Will Python (version 3.7.3) work correctly with RED 0.9.3 ? What version of Eclipse is best for it?

**Comment by joanna-may** [comment]
Hi,
RED supports both Python 2 and 3 (but after dropping support for Python 2 everything is tested on Python 3 now).
Eclipse should be newer then Oxygen. Product is build on Eclipse 2019-12 so this Eclipse should works with plugin too.
See sections "Requirements" and "Notable updates" for release:
https://github.com/nokia/RED/releases/tag/0.9.3

Can you say what problems did you have with python 3 and RED?

**Comment by donmartin483** [comment]
Hello,

In the past, I believe an earlier version of RED was not responsive with
Python (version 3).

Thanks,

Don

**Comment by michalanglart** [comment]
If you will find any problems regarding python 3 please open the ticket.
