### ISSUE TITLE
Adding selenium library with seleniumtestability plugin is not working

### ISSUE THREAD

**Issue by FransPeterson** [nokia/RED#370]
Hi all,

I'm trying to add the SeleniumTestability plugin on top of the Selenium Library into Eclipse RED but somehow it's not recognizing it. 

I'm using the below syntax as described [here](https://github.com/rasjani/robotframework-seleniumtestability):

`Library         SeleniumLibrary     plugins=SeleniumTestability;True;30 Seconds;True`

Also adding it via the option below will not work:

![image](https://user-images.githubusercontent.com/58031612/83847387-6db13e80-a70c-11ea-8005-5bd86f41095b.png)

Does anyone know how to properly add selenium plugins to a robot test suite?

**Comment by modrz** [comment]
Hi, 
Have you installed SeleniumLibrary and SeleniumTestability plugin correctly?
https://pypi.org/project/robotframework-selenium2library/
https://pypi.org/project/robotframework-seleniumtestability/

After installation I can use Selenium in RED with or without the plugin:
![image](https://user-images.githubusercontent.com/22540835/83854151-94747280-a716-11ea-80cb-2e29bafdf5b1.png)

![image](https://user-images.githubusercontent.com/22540835/83854069-773fa400-a716-11ea-85ba-66ea182bf103.png)

**Comment by modrz** [comment]
Of course if you want to use argument for library you have to add them manually in red.xml like in your screenshot.

**Comment by FransPeterson** [comment]
Yes it is installed according to PIP: 

![image](https://user-images.githubusercontent.com/58031612/83857812-d05e0680-a71b-11ea-93f9-6fa0e7bc751d.png)

But when adding it as an argument the library gets red: 

![image](https://user-images.githubusercontent.com/58031612/83857889-f1265c00-a71b-11ea-8db1-81b889d7bfe2.png)

When I remove it works fine again.

**Comment by modrz** [comment]
Please try reloading it, maybe some errors occur.
![image](https://user-images.githubusercontent.com/22540835/83858257-832e6480-a71c-11ea-9b04-8dad29ae25e5.png)

**Comment by FransPeterson** [comment]
Found the issue, needed to run Eclipse as administrator. Got an access denied on reloading.

**Comment by FransPeterson** [comment]
Found the issue, needed to run Eclipse as administrator. Got an access denied on reloading.
