### ISSUE TITLE
01-****.robot': Unsupported file format 'resource'.

### ISSUE THREAD

**Issue by fengnex** [nokia/RED#371]
I have a robot test suite which use a resouce file and Robot RIDE can successfully execute the whole test suite, but RED always complains the following error, leading to all tests get failed:
[ ERROR ] Error in file '************\01-gogogo.robot': Unsupported file format 'resource'.

I wonder what the matter is and what I should do to address it. Thanks in advance.

Environment information:
Robot Framework 3.0.3
Red v0.9.4
Python 3.7.4 on win32

**Comment by fengnex** [comment]
The problem has disappeared after I upgraded robotframework with the following command:
pip install robotframework==3.2.1

I did not expect that this could happen to the robotframework.

**Comment by michalanglart** [comment]
This is not a problem of RED but of Robot version. The ".resource" file extension was introduced in RF 3.1 if I recall correctly, so it cannot work in RF 3.0.3
