### ISSUE TITLE
ExtendedRequestsLibrary library not added to red.xml successfully in robot framework. 

### ISSUE THREAD

**Issue by Divya1711** [nokia/RED#375]
![image](https://user-images.githubusercontent.com/67328229/85418189-19bcab80-b58e-11ea-8c1c-d6ad70f7436c.png)

installed ExtendedRequestsLibrary through pip. but  library not added successfully in red.xml.

Tried removing auto added library and added it manually still facing same issue.

*** Settings ***
Library    ExtendedRequestsLibrary

*** Variables ***
${base_url}    https://api.fusionfabric.cloud/corporate/channels
${token_url}    https://api.fusionfabric.cloud/login/v1/sandbox/oidc/token
${client_id}    37c50a05-340f-431e-87e1-9d369b87cf6b
${client_secret}    3a787b0e-fd6f-49a4-bad2-4f2011d5a2f6
${auth_url}    https://api.fusionfabric.cloud/login/v1/sandbox/oidc/authorize
${Callback_URL}    https://getpostman.com/oauth2/callback
     
        

# *** Test Cases ***
# Get User Information

**Comment by Divya1711** [comment]
Help me resolving this issue.

**Comment by joanna-may** [comment]
Hi, 
please right click on Project Explorer - >SuperAppRobotProject -> Robot Referenced libraries -> Extendedrequestslibrary and select option "Reload" the you will see the error. 

If it is like in my project:
...AppData\Local\Programs\Python\Python37-32\Lib\site-packages\ExtendedRequestsLibrary' failed: AttributeError: 'to_json' is deprecated.

then please check this post:
https://stackoverflow.com/questions/62219332/extendedrequestslibrary-from-robot-framework-has-depreciation-to-json-error

**Comment by Divya1711** [comment]
> Robot Referenced libraries

First of all Thank you for helping.

I dont find Robot Referenced Libraries under my project.
![Uploading image.png…]()

**Comment by Divya1711** [comment]
Does it work on downgrading robotframework from 3.2.1 to 3.1.2 ?

**Comment by Divya1711** [comment]
downgraded robotframework to 3.1.2 . problem solved thank you.

**Comment by Divya1711** [comment]
Closing the issue as problem solved
