### ISSUE TITLE
Does RED have auto-suggest capability

### ISSUE THREAD

**Issue by mmclwd** [nokia/RED#376]
Auto-suggest capability means when you input part of keywords, IDE will show us all possible keywords that have the words you input.
For example in VS code, when we input "Run" in keyboard, it will give us all related keywords like "Run keywords if ", so I don't know whether RED had such function.

**Comment by michalanglart** [comment]
Hi, yes of course. Please have a look here: http://nokia.github.io/RED/help/user_guide/working_with_RED/content_assist.html
