### ISSUE TITLE
Test Runner Agent can't connect to RED server when running with default listener connection type setting.

### ISSUE THREAD

**Issue by rechardr** [nokia/RED#377]
Hi,

I've traced a problem I have only recently started having when debugging with robot and pydev.  I have been getting the following types of error msg:
TestRunnerAgent: connection trial #1 failed
Unable to open socket to "localhost:55753"
error: [WinError 10061] No connection could be made because the target machine actively refused it

I have been trying to resolve this for a number of days now as initially I got sidetracked with thinking it was going to be firewall issues or win10 update issues which recently has run or possible issues with vscode having also been installed during this time.  I have looked at the win sys possibilities but did not find anything unexpected there.  I was not using the latest eclipse/robot framework/pydev/RED updates, so I have also now reinstalled it all but I am still having issues.  The above connection refused msg still occurs and there's possibly another issue with dir names.

Looking at the connection refused issue first I think I have found my problem but I'm not sure if I can fix it via the config settings so I need some help.  It looks like the default 30s connection timeout in the RED server is too short for me and therefore by the time the Test Runner Agent is started the server is not there and we get that connection error msg.  (BTW, might be an idea to have some output msg logged when the server disconnects due to timeout )

On my build I checked with some timing and the RF is taking 35s, in this case, to complete its build.  I don't know why this has changed for me and is unexpected but can only put that down to that I must have been close to that edge and updates probably have introduced some delays that's pushed it over the edge now...

So what I'd like to know is, for this connection timeout issue, can a higher timeout value be set?  Or is there a way I can get around this?

Any help would be appreciated, many thanks,
Rechard

I'm now running with the following versions:
Eclipse 2019-12 (4.14.0)
RED 0.9.4
pydev: 7.6.0
Python 3.8 and 2.7

**Comment by michalanglart** [comment]
Hi,

the timeout used by `TestRunnerAgent` is described here: http://nokia.github.io/RED/help/user_guide/launching/red_agent.html

When starting from RED this timeout can be configured in launch configuration:

![timeout](https://user-images.githubusercontent.com/14932410/86169343-c1e7ec80-bb19-11ea-89e9-262ebfa7b946.png)

This setting can be also changed in Preferences for default values, so that each newly created launch configuration will have it changed.

**Comment by rechardr** [comment]
Hi,

Many thanks for the info.  I did try that out initially which is why I ended up asking the question ... but I must have made errors when trying it out as trying it again now it works as one would expect!  Yes, I saw the default and I did have my default value in preferences set up for 60s instead ... but I must have made noddy errors in running it all and looked at the wrong thing when I noticed the socket timeout was still at 30s.

BTW, does the IDE run in the latest version of Eclipse?  I tried that initially but had issues with my setup.  I didn't time to look into it so just downgraded for now.  But if it should work I may try upgrading it all now.

Anyway, thanks for the help , much appreciated.
Rechard

**Comment by rechardr** [comment]
Hi,

Is it possible to set things up so that by default tests are run, when running via the menu option (Debug As -> Robot Test), with the Test Runner Agent set to 'Use Remote Agent Connection' setting enabled?

**Comment by michalanglart** [comment]
> BTW, does the IDE run in the latest version of Eclipse? I tried that initially but had issues with my setup. I didn't time to look into it so just downgraded for now. But if it should work I may try upgrading it all now.

You're asking about 2020-06? We're now looking into that but so far haven't found major issues when running our tests on 2020-06.

> Is it possible to set things up so that by default tests are run, when running via the menu option (Debug As -> Robot Test), with the Test Runner Agent set to 'Use Remote Agent Connection' setting enabled?

Well, no. It seems to be easy to change however, so we can do that in next release.

**Comment by michalanglart** [comment]
> Is it possible to set things up so that by default tests are run, when running via the menu option (Debug As -> Robot Test), with the Test Runner Agent set to 'Use Remote Agent Connection' setting enabled?

This is now fixed in 0.9.5
