### ISSUE TITLE
Issues with building

### ISSUE THREAD

**Issue by rechardr** [nokia/RED#378]
Hi,

I've been trying to follow the build instructions but I have been having some problems.  I have not built eclipse plugins before so I can't be 100% sure that I'm following the instructions as required.  I get as far as trying to build the org.robotframework.ide.eclipse.main.feature.build component.  At this point it seems to fail because it can't find an artifact, the error msg I get is:

```
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.robotframework.ide.eclipse:org.robotframework.ide.eclipse.feature.build:1.0.0-SNAPSHOT: Could not find artifact org.robotframework.ide.eclipse:org.robotframework.ide.eclipse.feature.buildParent:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 8, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.robotframework.ide.eclipse:org.robotframework.ide.eclipse.feature.build:1.0.0-SNAPSHOT (D:\EclipsePluginDev\git\RED\src\Eclipse-IDE\org.robotframework.ide.eclipse.main.feature.build\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.robotframework.ide.eclipse:org.robotframework.ide.eclipse.feature.build:1.0.0-SNAPSHOT: Could not find artifact org.robotframework.ide.eclipse:org.robotframework.ide.eclipse.feature.buildParent:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 8, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

```

Does anyone know what I have done wrong here, or is this an issue with the building instructions?

Many thanks,
Rechard

**Comment by michalanglart** [comment]
Hi,

the building instructions (https://github.com/nokia/RED/blob/master/building.md) states that you should `clean install` following projects (in this order):

1. `org.robotframework.ide.eclipse.parent`
2. `org.robotframework.ide.eclipse.product.feature.buildParent`
3. `org.robotframework.ide.eclipse.product.feature.build`
4. `org.robotframework.ide.eclipse.main.feature.buildParent`
5. `org.robotframework.ide.eclipse.main.feature.build`
6. `org.robotframework.ide.eclipse.product.product`
7. `org.robotframework.ide.eclipse.main.feature.update-site`

It seems that you're building `3` but message error is telling that the `2` cannot be found. Are you sure you've built it?

Once maven performs `install` it will put the build artifact into your local maven repository. The error tells that there are no such artifact (`org.robotframework.ide.eclipse.product.feature.buildParent`) but it is required to build `3`

**Comment by rechardr** [comment]
Hi,

I did run through each item step by step and tried the whole thing from the start more than once... When I get to this section I run the clean and then install from the Run as menu options of each item, going through them in sequence.  I can clean + install 1-4 but when I run 5 it fails.  I'm going to clear my workspace completely and start again and see what happens ... 

For this one I'm running with eclipse 2020-03 (4.15.0)

I'll delete it all again and try again ... When I get the the

**Comment by michalanglart** [comment]
Ok, please try again and let us know. Those building instructions were checked and reviewed around a year ago and we haven't changed anything in the meantime regarding building, so it should work.

If you fail again I will try to go through all of this on my side and see if it works.

**Comment by rechardr** [comment]
Hi,

I've retried this and I've got issues when attempting with both Python 3.8.3 and Python 2.7.  When running with Python 3.8.3 and targeting eclipse 2020-03 I can run though the various components but have issues with org.robotframework.ide.eclipse.main.feature.buildParent where tests fail, seems utf-8 encoding issues and also it needed pyyaml module installed.

I'm attaching some of console output logs … this first is with py3 going through to org.robotframework.ide.eclipse.main.feature.buildParent

[build_err1_py3.txt](https://github.com/nokia/RED/files/4861448/build_err1_py3.txt)

It has utf8 and the pyyaml missing errors … I then added pyyaml and ran it again and carried on and tried the next component as well... org.robotframework.ide.eclipse.main.feature.build . This one failed as well... the console log was too large and I was unable to save it to file but I copy/pasted a chunk of the log from the console into the next file...

[build_err2_py3.txt](https://github.com/nokia/RED/files/4861461/build_err2_py3.txt)

That one also had a number of issues related to utf-8 and also I spotted the following.. "Unable to load JDK7 types"  … Is this related to the Java version I have installed.  At the moment I have installed JDK v11.

These utf-8 issues may have been due to the setup on my pc... I've enable utf-8 by adding PYTHONUTF8=1 to my env and have rerun org.robotframework.ide.eclipse.main.feature.buildParent … there are still issues, see next file:

[build_err3_py3.txt](https://github.com/nokia/RED/files/4861544/build_err3_py3.txt)


Originally, I had run with Python2.7.  I've tried that again and go that same error about missing artifact…
[build_err_py27.txt](https://github.com/nokia/RED/files/4861549/build_err_py27.txt)

Anyway, as I've got things running well again on my pc I have no urgent need to build it.
Many thanks,
Rechard

**Comment by michalanglart** [comment]
Those errors are coming from pyUnit tests contained in `org.robotframework.ide.core-functions` project. By default they are run using `python` interpreter as defined in `PATH` environment variable. Actually just for the sake of building the project you can safely ignore them. In order to do it just pass `skip.py.unit.tests` property set to `false` (or change it in pom.xml).

**Comment by rechardr** [comment]
Hi,
I've managed to skip the tests and I seem to get almost to the end.  I get as far as the step ... Run org.robotframework.ide.eclipse.product.plugin as Eclipse Application selecting org.robotframework.red as product to run

I'm not sure I did this correctly as I'm not sure if it actually did anything .. what is that step supposed to do?
Anyway, looks like I just need to and go over it again when I have enough spare time to check each of the steps that I'm running...
Many thanks for your help.
Rechard

**Comment by michalanglart** [comment]
Hi,

to be honest - I don't know why this step is there. Once you run all the maven builds you should have binaries generated as stated in next step. It doesn't however depend on this step. It looks like some leftover after the building.md was reviewed.
