### ISSUE TITLE
Cannot install from marketplace

### ISSUE THREAD

**Issue by srinivasskc** [nokia/RED#379]
Install from Marketplace/Update Site
Marketplace: Click Help -> Eclipse Marketplace -> and type into Find field "RED" Update Site: Click Help -> Install New Software -> Add and set address in Location to:

http://master.dl.sourceforge.net/project/red-robot-editor/repository

It is redirecting to:  503 Service Unavailable
No server is available to handle this request.

**Comment by michalanglart** [comment]
I was able to successfully install RED via marketplace 5 minutes ago. Please just try again, check your connectivity (proxies) or install it some other way described in user guide.

**Comment by srinivasskc** [comment]
yes, there is a problem with sourceforge. closing this.

![image](https://user-images.githubusercontent.com/26836928/87390349-5183a580-c5c6-11ea-84ce-7e607028f54f.png)
