### ISSUE TITLE
The RED formatter doesn't support the new-style "For Loop"

### ISSUE THREAD

**Issue by apallier** [nokia/RED#386]
Since Robot Framework 3.2, "For loop" can be written as below:
```robotframework
FOR    ${key}    ${value}    IN    &{values}
    Check Equal    ${key}    ${value}
END
```

When I try the RED formater the result is:
```robotframework
FOR    ${key}    ${value}    IN    &{values}
Check Equal    ${key}    ${value}
END
```
Result: The indentation is bad.

Does the formater support the new-style  "For Loop"?

**Comment by michalanglart** [comment]
Hi,

1. What is the version of RED you're using?
2. How is your formatter configured?
3. How do you run the formatter (manually on whole file or on selection or automatically on save for whole file or for changed lines only)?

I've checked and in 0.9.5 with formatter configured as follows:
![cfg_formatter](https://user-images.githubusercontent.com/14932410/92019720-5d365180-ed57-11ea-9abc-feb217e821e0.png)

I have following behavior for whole file selection with manually triggered formatter:
![for_formatting](https://user-images.githubusercontent.com/14932410/92019786-70e1b800-ed57-11ea-894e-72d7e64891f2.gif)

**Comment by apallier** [comment]
Sorry for the lack of precision.
RED 0.9.5 with the same formatter config than you + "Right Trim lines"

I cannot reproduce the problem with a brand new file.
So I try to copy, clear then paste all the content of my initial file and now the formatting works.
Don't understand why, but now it works.

I had just upgraded from 0.9.3 to 0.9.5. It may be the root cause.

Thank you for your help.
