### ISSUE TITLE
Run Configurations "Only run tests with these tags" does not work

### ISSUE THREAD

**Issue by pbbos** [nokia/RED#39]
Running a testsuite with the option "Only run tests with these tags:" doesn't work.
All testcases will run, not only the ones with the given tag(s).

Eclipse Java EE IDE for Web Developers.
Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600

Java 1.7.0_80-b15
Python 2.7.11
RED - Robot Editor version 0.6.5 
Win 7 pro 64 bit

**Comment by adam-wypych** [comment]
Base on You description (and compare with other bug created by You: #40 ) it seems that You didn't click on `Add new tag` button ( 
![image](https://cloud.githubusercontent.com/assets/12131969/18302628/26e0aa54-74d9-11e6-8916-c53d063fa449.png)
) when You added new tag. This is why the tag is not save in the configuration and didn't use, when run was performed.

We think that is quite unclear so we will think how to handle this better.

**Comment by pbbos** [comment]
You are right. I didn't click the add new tag button. I thought that it
should only be used when adding multiple tags.

You can close the issue.  Thanks

Op 7 sep. 2016 09:00 schreef "adam-wypych" <notifications@github.com>:
