### ISSUE TITLE
How to execute test cases for multiple times with RED

### ISSUE THREAD

**Issue by DanielTian90** [nokia/RED#392]
Does RED support to execute target test cases or suite for defined mutiple times?

**Comment by michalanglart** [comment]
Hi,

of course you can execute certain test cases or suites multiple times in RED - manually ;)

Jokes aside - no, there is no such feature in RED. I think that this would be achievable with `pabot` library and moreover with Robot API for pre-run modifiers (https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#pre-run-modifier). For example you can have something like this:

```python
from robot.api import SuiteVisitor

class MultiplyTests(SuiteVisitor):

    def __init__(self, copies=10):
        self.copies = int(copies)

    def start_suite(self, suite):
    	no_of_tests = len(suite.tests)
    	for i in range(self.copies):
    		for j in range(no_of_tests):
    			original_test = suite.tests[j]
    			test_copy = original_test.deepcopy(name=original_test.name + '_' + str(i))
    			suite.tests.append(test_copy)

    def visit_test(self, test):
        pass
```

Which would create given number (default=10) of tests copies in each suite. This can be then added to your every launch in RED via https://nokia.github.io/RED/help/user_guide/launching/launch_prefs.html (Default launch configurations) as: 

```
--prerunmodifier MultiplyTests.py:5
```

Of course this logic here is a bit naive, but you can imagine that e.g. only tests with certain tags are copied, number of copies can be parameterized differently and so on. You may also use listener APIv3 which should enable you to copy tests depending on their result (after they were executed). I think overal listener APIv3 and pre-run modifier API could be easiest way to achieve your goal without need for external tools (like `pabot` I've mentioned above).

**Comment by DanielTian90** [comment]
It works fine, many thanks!
