### ISSUE TITLE
Resource \Library files outside project directory not supported

### ISSUE THREAD

**Issue by NehaDua** [nokia/RED#395]
Hi Team ,
Thanks much for this amazing plugin "RED", we have started using RF and found this plugin really helpful.
My requirement is to use same Resource file across all the RF projects in eclipse ,s o kept common resource file outside project directory and getting warning message ,can you please assist if RED supports it or not?
Tried using absolute and relative path but getting below warning :

•Path '../../CommonFiles/CommonUpointKeywords.resource' points to location outside your workspace
•RED does not support importing resources located outside of workspace. Keywords from this resource will not be recognized. Try to use Quick Fix (Ctrl+1) to link folder into the project.

**Comment by michalanglart** [comment]
Hi,

if you're unable to use quick fix to create a link you can link the file manually. In order to do it:

- open context menu on your project,
- choose `New -> File`,
- give a name to a file (probably the same as the actual name of your file),
- click `Advanced` button and check `Link to file in the file system`,
- browse for a file and then proceed with `Finish` button.

After that revalidate the project and RED should be able to recognize the resource file and import it correctly.

**Comment by NehaDua** [comment]
It worked like a charm. Thanks Much !

**Comment by NehaDua** [comment]
HI  @michalanglart,

I followed the steps mentioned above, I was able to import the library in the Settings part as shown below. There were no syntax errors and no errors while trying to use the keywords.

![CommonResourceFileError](https://user-images.githubusercontent.com/13778367/95094946-1964ac80-0748-11eb-9822-5a73c2585d6d.PNG)


*** Settings ***
Resource    ../../../../../../../RobotCommon/CommonUpointKeywords.resource

But while executing the same, we are getting the below error.
[ ERROR ] Parsing 'C:\SampleRobotProject\TestSuites\TestSuite3.robot' failed: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 244: invalid start byte

Try --help for usage information.

Is there anything which we are missing out in the usage of these common files available outside the robot project directory.

Thanks!

**Comment by michalanglart** [comment]
Please make sure that your files are encoded in UTF-8 . Please also make sure that eclipse will encode the files when saving using UTF-8: Window -> Preferences -> General -> Workspace -> Text file encoding -> Other -> UTF-8

**Comment by NehaDua** [comment]
[ ERROR ] Error in file 'C:\Users\A1003106\OneDrive - Alight Solutions\Documents\2019-workspace\SampleRobotProject\TestSuites\TestSuite3.robot' on line 2: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 937: invalid start byte
[ WARN ] Imported library 'C:\RobotCommon\ObjectLocator.py' contains no keywords.
SampleRobotProject.TestSuites.TestSuite3                                      
==============================================================================
Resource File Usage                                                   | FAIL |
No keyword with name 'CommonUpointKeywords.Login_To_Upoint' found.
------------------------------------------------------------------------------
Object Locator Usage                                                  | FAIL |
Variable '${Login_PAGE}' not found.
------------------------------------------------------------------------------
SampleRobotProject.TestSuites.TestSuite3                              | FAIL |
2 critical tests, 0 passed, 2 failed
2 tests total, 0 passed, 2 failed
==============================================================================
SampleRobotProject.TestSuites                                         | FAIL |
2 critical tests, 0 passed, 2 failed
2 tests total, 0 passed, 2 failed
==============================================================================
SampleRobotProject                                                    | FAIL |
2 critical tests, 0 passed, 2 failed
2 tests total, 0 passed, 2 failed

**Comment by NehaDua** [comment]
Tried out the settings change as mentioned in the comment. Changed the “Text File Encoding” to utf – 8. But still, the same issue occurs while trying to use the custom keyword resource file and object locator file.

Below is the error message of console while trying to execute the test suite.

[ ERROR ] Error in file 'C:\Users\workspace\SampleRobotProject\TestSuites\TestSuite3.robot' on line 2: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 937: invalid start byte
[ WARN ] Imported library 'C:\RobotCommon\ObjectLocator.py' contains no keywords.
SampleRobotProject.TestSuites.TestSuite3                                      
==============================================================================
Resource File Usage                                                   | FAIL |
No keyword with name 'CommonUpointKeywords.Login_To_Upoint' found.
------------------------------------------------------------------------------
Object Locator Usage                                                  | FAIL |
Variable '${Login_PAGE}' not found.
------------------------------------------------------------------------------
SampleRobotProject.TestSuites.TestSuite3                              | FAIL |
2 critical tests, 0 passed, 2 failed
2 tests total, 0 passed, 2 failed

**Comment by michalanglart** [comment]
But have you saved the file again? This setting is taken into account when saving the file. Thus if it had different encoding and you've changed the setting then it would still have non-UTF-8 encoding. Open the problematic file, make some simple change and save it again.
