### ISSUE TITLE
Run button (Run Configurations) is disabled when editting Tags textfield(s)

### ISSUE THREAD

**Issue by pbbos** [nokia/RED#40]
When i add or edit a tag in one of the textfields of "Tags", the Run button gets disabled.
When i uncheck and check the checkbox of "Only run tests with these tags" or "Skip tests with these tags" afterwards, then the Run button is enabled again.

Eclipse Java EE IDE for Web Developers.
Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600

Java 1.7.0_80-b15
Python 2.7.11
RED - Robot Editor version 0.6.5 
Win 7 pro 64 bit

**Comment by adam-wypych** [comment]
See my comment: https://github.com/nokia/RED/issues/39#issuecomment-245192747
