### ISSUE TITLE
How to build RED？

### ISSUE THREAD

**Issue by yedan2010** [nokia/RED#403]
I followed building.md to build RED，but still can‘t build it！ There had some problem：
1)Is Eclipse for RCP and RAP Developers needed special version？
2)some errors:
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: org.robotframework.ide.eclipse:org.robotframework.ide.eclipse.product.feature:1.0.0-SNAPSHOT @ F:\RED-0.9.5\RED-0.9.5\src\Eclipse-IDE\org.robotframework.ide.eclipse.product.feature\pom.xml
[INFO] Fetching p2.index from http://download.eclipse.org/eclipse/updates/4.15/ (128B)
[INFO] Adding repository http://download.eclipse.org/eclipse/updates/4.15
[INFO] Fetching p2.index from http://download.eclipse.org/eclipse/updates/4.15/R-4.15-202003050155/ (142B)
[INFO] Fetching p2.index from http://download.eclipse.org/releases/2020-03/ (122B)
[INFO] Adding repository http://download.eclipse.org/releases/2020-03
[INFO] Fetching p2.index from http://download.eclipse.org/technology/epp/packages/2020-03/ (142B)
[INFO] Fetching p2.index from http://download.eclipse.org/releases/2020-03/202003181000/ (142B)
 org.apache.http.impl.execchain.RetryExec execute
 I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://download.eclipse.org:80: The target server failed to respond
org.apache.http.impl.execchain.RetryExec execute
: Retrying request to {}->http://download.eclipse.org:80
[INFO] Fetching p2.index from http://download.eclipse.org/nattable/releases/1.6.0/repository/ (172B)
[INFO] Adding repository http://download.eclipse.org/nattable/releases/1.6.0/repository
[INFO] Adding repository http://fappel.github.io/xiliary
[ERROR] Failed to resolve target definition D:\.m2\repository\org\robotframework\ide\eclipse\org.robotframework.ide.eclipse.target-platform\1.0.0-SNAPSHOT\org.robotframework.ide.eclipse.target-platform-1.0.0-SNAPSHOT-photon.target: Failed to load p2 metadata repository from location http://fappel.github.io/xiliary: Unable to connect to repository http://fappel.github.io/xiliary/content.xml: Connect to fappel.github.io:80 [fappel.github.io/127.0.0.1] failed: Connection refused: connect -> [Help 1]
[ERROR]

**Comment by michalanglart** [comment]
Hi,

1. You actually don't need eclipse at all to build RED, after all it is built on our CI machine which do not have eclipse. What you need is maven, although when building on your own you probably want to do it from eclipse (we're doing it on our local machines when developing) and for that you need m2e which is a maven integration for eclipse https://www.eclipse.org/m2e/ - but I'm assuming you're already have it.

2. Looks like a connectivity problem. I've just checked it and I'm able to run those without such issues, have you tried again, maybe it was somehow offline, although the update-site it was unable to connect was github.io which is fairly stable. Do you have any special network settings (firewalls, proxies)?

**Comment by yedan2010** [comment]
Thanks。There has a BUG with the repository http://fappel.github.io/xiliary/content.xml。I have open a bug to the author！

**Comment by michalanglart** [comment]
What bug? This is a p2 repository - you would get 404 when trying to connect using any browser. However try to connect to it from eclipse/RED: go to `Help->Install new software` and in `Work with` field enter http://fappel.github.io/xiliary and hit enter. If it works you should be able to see features available at this site. I was able to connect just now, see:

![image](https://user-images.githubusercontent.com/14932410/99360427-d9e5c000-28b0-11eb-8084-35d8bb3739bd.png)
