### ISSUE TITLE
The log.html has no toggle collaps all, open all

### ISSUE THREAD

**Issue by valentijnpeters** [nokia/RED#407]
It is only possible to toggle the visibility of the results one by one, it should be possible to open all or collaps all either with 1 shortcut or with 1 button.

**Comment by michalanglart** [comment]
The `log.html` is a file generated by Robot - it is a requirement for Robot, not RED

**Comment by valentijnpeters** [comment]
> The `log.html` is a file generated by Robot - it is a requirement for Robot, not RED

I see, I will take the effort to send that requirement to the Robot builders.

**Comment by humbienri** [comment]
@valentijnpeters how long have you been using Robot Framework? Or how long have you been using RED? Prior experience and exposure to using the Eclipse IDE?

**Comment by valentijnpeters** [comment]
I instantly started using Eclipse with RF  2 years ago.

Lost 4 months I learned tons.
All puzzle pieces that I didnt understand I get them now.
Lots of collega's working from home in the same company also using rf (and
thus Red module)

I'm not an expert. The things I mention are the things that cross my mind
in using it.


_-vanaf Samsung mobiel-_

Op wo 9 dec. 2020 16:41 schreef Eman <notifications@github.com>:

**Comment by valentijnpeters** [comment]
Last

_-vanaf Samsung mobiel-_

Op wo 9 dec. 2020 22:12 schreef V. Peters <valentijn.peters@gmail.com>:

**Comment by valentijnpeters** [comment]
But I like working with Eclipse and I like the RED module.
The scripts I automated served us well.
Lots of bug prevention from causing mega disasters in production!

So yeah very very content all in all...

With kind regards,

Valentijn

_-vanaf Samsung mobiel-_

Op wo 9 dec. 2020 22:12 schreef V. Peters <valentijn.peters@gmail.com>:

**Comment by michalanglart** [comment]
Not a RED issue

**Comment by valentijnpeters** [comment]
> [@valentijnpeters](https://github.com/valentijnpeters) how long have you been using Robot Framework? Or how long have you been using RED? Prior experience and exposure to using the Eclipse IDE?

>10 years
