### ISSUE TITLE
log.html could have an option to only watch all screenshots instantly

### ISSUE THREAD

**Issue by valentijnpeters** [nokia/RED#411]
log.html could have an option to instantly/only watch all the screenshots without the rest of the text.

screenshots openend.
rest closed.

**Comment by michalanglart** [comment]
Same as #407

**Comment by valentijnpeters** [comment]
> Same as #407

okay forwarded this one to Pekka https://twitter.com/pekkaklarck as well. Let's hope they pick these ones up.

**Comment by humbienri** [comment]
I think you would be better of creating a ticket or Github issue for this on RF's repo, https://github.com/robotframework/robotframework

**Comment by valentijnpeters** [comment]
I think so too

_-vanaf Samsung mobiel-_

Op wo 9 dec. 2020 16:47 schreef Eman <notifications@github.com>:

**Comment by michalanglart** [comment]
Not an RED issue
