### ISSUE TITLE
Question:  import custom library

### ISSUE THREAD

**Issue by NikitaOstr** [nokia/RED#417]
Hi there!
I created my custom keyword in python file and added this 'library' in red.xml. After that in robot file I did import of this custom library. No matter what and how I do import but robot does not see this import - it's underlined in red. Together with it a run is not failing, means that underline is cosmetic but very bothering and annoying. Is it an issue in 0.9.5? Or do I miss something in importing?
Will be very appreciated for any help)

**Comment by michalanglart** [comment]
Hi,

Try to reload the library (from context menu on the library in project explorer) and tell us what are the errors you get from this operation.

**Comment by NikitaOstr** [comment]
Hi,  there is no any issue in red.xml. The library is imported with the right path to it. And test that uses keyword from this library is working. The issue here is not functionality but GUI. Robot file in RED does not see it correctly. 
No matter how I declare in import, nothing works:
1. Library                     LoginSafe
2. Library                     LoginSafe.py
3. Library                     D:/Robot/keywords/machine-commands/LoginSafe
4. Library                     D:/Robot/keywords/machine-commands/LoginSafe.py
5. Library                     ${AUTO_IS}/machine-commands/LoginSafe
6. Library                     ${AUTO_IS}/machine-commands/LoginSafe.py

${AUTO_IS} is defined in Variable Mapping in red.xml
As result my keyword is marked as 'unknown' as well.
Any idea?

**Comment by michalanglart** [comment]
You've mentioned your import is underlined with RED. But what is the message? Can you see your library and the keywords inside it in Robot Referenced libraries node in Project Explorer view?

What is the version of python/robot?

**Comment by NikitaOstr** [comment]
It shoes yellow popup: Unknown <my library> library. Try to use Quick Fix or add library to red.xml. Pressing ctrl+1 shows window that this library is added with green triangle sign and shows the right path to it.
I do see my library in Project Explorer view but I don't see keyword and cascade option like I see it for robot files. But this happens for all python files in the project.
Should I enable some feature for this? Missed something?
Python 3.8 and Robot 3.2.2

**Comment by michalanglart** [comment]
> Pressing ctrl+1 shows window that this library is added with green triangle sign and shows the right path to it

This window does not show that something is added. It shows an action which can be triggered and which would add the library to red.xml file after triggering. The green triangle sign is just an icon for this action.

> But this happens for all python files in the project.

RED does not modify any user interface regarding `.py` files but it influences how you see `.robot` files. Those libraries under `Robot reference libraries` are also provided by RED.

Do you have library specification files generated for your project? Have a look into its location on disk - there should be `libspecs` folder in which there should be a file generated for each of the libraries (including standard ones).

Here you have very simple project with custom libraries:
[GH-417.zip](https://github.com/nokia/RED/files/6042853/GH-417.zip)

and this is how I see it when the library is added to `red.xml` and after the project is built:
![image](https://user-images.githubusercontent.com/14932410/109151958-202da380-776b-11eb-81cc-61c34419a6b9.png)

**Comment by NikitaOstr** [comment]
According to your guide I checked the pane:
![image](https://user-images.githubusercontent.com/45942078/109165546-59bed880-7784-11eb-8790-a3eca16baa86.png)

And my only keyword in library is:
![image](https://user-images.githubusercontent.com/45942078/109165770-9d194700-7784-11eb-9b69-c7abab60f208.png)

And I don't see in libspecs file generated for my library. Is this step automatic or should I perform it manually?

**Comment by NikitaOstr** [comment]
BTW, also followed after https://github.com/nokia/RED/issues/340 but without success

**Comment by michalanglart** [comment]
Libspec file is generated in building process. If you have building enabled then it is automatic, if not then not. But since there are other libspecs generated then your project was built.

In my first comment here I've asked what is the error if you try to reload the library (which is btw also first thing asked in #340). Can you please share it?

**Comment by NikitaOstr** [comment]
C:\WINDOWS\system32>python -m robot.libdoc D:/Robot/keywords/machine-commands/LoginSafe.py list
Safe Login

Also I don't see any error when adding this library into red.xml. Error pane stays empty

**Comment by michalanglart** [comment]
What I mean by Reload and the message from it, is this:

![reload_library](https://user-images.githubusercontent.com/14932410/109175546-3006b100-7786-11eb-9869-fa655ef257d3.gif)

**Comment by NikitaOstr** [comment]
Evrika! After reload library from context menu it started to work)))) 
What is the reason of that that RED need manually reload loaded library?
Thank you very much!!!!!!

**Comment by michalanglart** [comment]
I don't know why it wasn't automatically generated. It should. However I have too little information to see what went wrong in your case.

**Comment by NikitaOstr** [comment]
Thank you for your great help!)

**Comment by michalanglart** [comment]
No problem, happy testing!
