### ISSUE TITLE
Support for Robot Framework 4.x

### ISSUE THREAD

**Issue by Zeckie** [nokia/RED#424]
Robot Framework 4.0.3 has been released - [Release Notes](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-4.0.3.rst)

There are already some issues related to RF4, such as https://github.com/nokia/RED/issues/413 and [#421](https://github.com/nokia/RED/issues/421). However, both of those state that "... there are more changes in RF 4.0 which requires RED to change in order to properly run tests"

(edit: update version to 4.0.3)

**Comment by efgruber** [comment]
+1

**Comment by manelmendez** [comment]
+1

**Comment by shadeimi** [comment]
+1

**Comment by 9nehS** [comment]
+1

**Comment by valentijnpeters** [comment]
+1

**Comment by valentijnpeters** [comment]
How can we help to make this running again?

**Comment by michalanglart** [comment]
duplicates #413

**Comment by Daniwin82** [comment]
+1

**Comment by michalanglart** [comment]
See: https://github.com/nokia/RED/issues/413#issuecomment-953719889
