### ISSUE TITLE
An internal error occurred during: "Looking for Python installations".

### ISSUE THREAD

**Issue by nanduIyer** [nokia/RED#434]
I installed this in Windows 10 64 bit OS
I am yet to start the work. I was checking the Window --> Preferences --> Robot Framework --> Installed Framework -->

<img width="347" alt="robotframewokerror" src="https://user-images.githubusercontent.com/95294558/144070959-dbbe32fb-b5ad-4051-9aab-1ae04e971c26.PNG">
[.log](https://github.com/nokia/RED/files/7626677/default.log)

My eclipse version is Version: 2021-09 (4.21.0)
Build id: 20210910-1417 64 bit

My Java version is  
C:\Users\g_nan>java -d64 -version
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)

Python version is
C:\Users\g_nan>python --version
Python 3.10.0

Any help will be appreciataed.

**Comment by joanna-may** [comment]
Hi,
please check python path set in PATH variable. I see that you use python from path:
C:\Users\g_nan>python --version
but in log in RED python is in:
C:\Users\g_nan\Documents\Python\python

**Comment by nanduIyer** [comment]
@joanna-may Thanks. I fixed it by reinstalling everything
