### ISSUE TITLE
How can I configure the working directory for a test execution?

### ISSUE THREAD

**Issue by marcosanchotene** [nokia/RED#438]
I am working on a project that has many resources and libraries imported with the `${EXECDIR}` variable on their path. For them to work, test executions must start inside a particular directory within the project. I have searched a lot but could not find a way to configure the working directory for RED test executions. Is that possible?

**Comment by michalanglart** [comment]
Hi,

If I understand correctly you should try to use the preference: `Pass selected suite as data source` from here:
![image](https://user-images.githubusercontent.com/14932410/152228183-8e5045b4-3e8b-40f1-af68-edebf37bc89e.png)

When enabled RED will use the exact directory inside the project when trying to run it as a suite.

**Comment by marcosanchotene** [comment]
Thanks for your reply, but it's not that. 

The file structure I have is more or less this:

- project
  - directory1
     - resources
     - tests
  - directory2

I need to run the tests inside `directory1` so the imports will work with the `${EXECDIR}` variable because they are like `${EXECDIR}`/resources.

If I run them in `project`, the imports won't work. If I run them inside `tests`, they won't work also.

So what I need is a way to configure the working directory of the test execution, like there is for Java applications as explained [here](https://stackoverflow.com/questions/21028690/how-do-i-change-the-working-directory-for-an-eclipse-run-configuration).

**Comment by michalanglart** [comment]
Alright, then it was planned to make it configurable but it is not unfortunately as of now. The exact responsible line is this:

https://github.com/nokia/RED/blob/73de778620af027870d53039d0e326bb3f47cde0/src/Eclipse-IDE/org.robotframework.ide.eclipse.main.plugin/src/org/robotframework/ide/eclipse/main/plugin/launch/local/RobotLaunchConfigurationDelegate.java#L159

Which takes exactly the project location as working directory for launched process:
```
robotProject.getProject().getLocation().toFile()
```

**Comment by marcosanchotene** [comment]
Ok. Thanks for clarifying it. I guess my only option is to refactor the imports.
