### ISSUE TITLE
'Building' has encountered a problem. An internal error occurred during. "Building" 

### ISSUE THREAD

**Issue by MiladZarour** [nokia/RED#439]
![image](https://user-images.githubusercontent.com/50852900/159940529-a6849b49-8cbd-4a16-8803-3b595e26ffde.png)
Hi Everyone,
I tried to create a Robot project , but I am getting this error : An internal error occurred during: "Building".
Unable to communicate with XML-RPC server
I tried some solution , but didn't work , and now when I press OK , I can't access to the libraries and the files inside the projects...

**Comment by kenifanying** [comment]
Hi,

It may be help to increase Java Virtual Machine Xms and Xmx parameters.

> Memory allocation is controlled in eclipse.ini/RED.ini file in eclipse/RED folder with Java Virtual Machine Xms and Xmx parameters. By default Eclipse is configured to run on system with 2GB of memory, in case of stronger systems it is advised to increase those parameters to respectful levels. Change or add those parameters in .ini file after -vmargs parameter:
-vmargs
-Xms2048m
-Xmx4096m_


see http://nokia.github.io/RED/help/user_guide/known_issues.html

**Comment by mateusz-grzeskowiak** [comment]
I have the same issue, changing parameters did not help
Robot Framework 5.0 (Python 3.10.4 on darwin)

**Comment by SurajRaju06** [comment]
I am facing this error too. Below are my configurations

Python 3.10.4
Robot Framework 5.0 (Python 3.10.4 on win32)
Eclipse Version: 2022-03 (4.23.0)
RED Version: 0.9.5

**Comment by Zeckie** [comment]
Please note that the latest Robot Framework version supported by RED is 3.2.x. 

Support for RF 4+ (and whether there will be any future development) is being discussed in https://github.com/nokia/RED/issues/413 (eg. https://github.com/nokia/RED/issues/413#issuecomment-1017710081)

**Comment by MiladZarour** [comment]
Thx 
I am closing this issue
