### ISSUE TITLE
Resources importing

### ISSUE THREAD

**Issue by Mario-P** [nokia/RED#45]
Hi,

I have some issue with importing Resources in RED in Eclipse. I have following structure of my tests:

/robot_tests/Common/
/robot_tests/Site/

My RED project location points to /robot_tests.

Inside Site directory I have site_resource.robot where I keep default values of variables per site (there can be many sites with different values). site_resource.robot has to be imported in robot files that are inside Common directory. I have tried different settings in Referenced libraries -> Paths section: I added both Common and Site there with full paths, added Common and Site without paths and changed relativeness to PROJECT and WORKSPACE. Only solution that has been working was when I imported site_resource.robot with path (../Site/site_resource.robot) and this is not acceptable solution :(. 

In RIDE when you add both Common and Site to Pythonpath you can easily use keywords and variables from them in any other place. Is that possible in RED?

Thanks,
Mariusz

**Comment by Mario-P** [comment]
Update.
I see that proper settings of Referenced libraries -> Paths is Common and Site with path relativeness set to PROJECT. Then when I hover mouse over one of the entries in Path section I can see proper path.

Now I created new suite inside Sites (as a directory) and tried to import resource sire_resource.robot and it is also not possible. I'm guessing something is not ok with importing.

**Comment by KrzysztofJozefowicz** [comment]
Hi
Indeed RED does not fully support importing resources and var files when those files are imported using parameter in path either declared in the same file or in python file (loclal or global).
It only works using VariableMappings from red.xml in General Tab.
Following suite with res.robot and vars in "folder" subdirectory will PASS but RED shows errors for not known res_kw and ${var_1}.
```
*** Settings ***
Resource     ${resource}/res.robot
Variables    ${resource}/vars.py
*** Variables ***
${resource}  folder

*** Test Cases ***
t1
   log  ${var_1}
   res_kw
*** Keywords ***
```

I have created internal Jira as this is an enhancement to work the same as with parametrized path to libs

**Comment by Mario-P** [comment]
I'm not sure if we are talking about the same things, so once again with pictures :). 

1. I'm creating a RED project (location d:\red_tests). ![project_structure](https://cloud.githubusercontent.com/assets/22638505/19149906/7a10aef2-8bc4-11e6-8ad6-d9788db1de04.PNG)
2. I'm creating common_resource.robot inside with some keywords. 
3. I'm putting "./" to pythonpath with relativeness to project in red.xml. ![red_xml](https://cloud.githubusercontent.com/assets/22638505/19149902/7846cbec-8bc4-11e6-95dc-fd389ee195c4.PNG)
4. I'm creating folder Tests and inside a suite - RED_test_suite.![test_suite](https://cloud.githubusercontent.com/assets/22638505/19149903/784a7238-8bc4-11e6-831e-1730181c8794.PNG)

suite code:
```robotframework
*** Settings ***
Resource          common_resource.robot

*** Test Cases ***
TestCase
    RED test keyword
```
As you see I have not used any parameters while importing resource and still that resource is not recognized.

**Comment by KrzysztofJozefowicz** [comment]
ok, we talked about different thing, resource resolving from PythonPath should also be added although usage for us is controversial ;) .
I have created another issue in Jira for that.

**Comment by sumnanda** [comment]
Hello,
I am having similar issue as stated above. Can you please tell me how can this be resolved?

Thanks,
Sanam
