### ISSUE TITLE
Current master branch has conflicts committed

### ISSUE THREAD

**Issue by mbrzozowski** [nokia/RED#46]
Hi,

The current master branch has conflicts committed and cannot be built.
The commit 77333aa5d08c2b1646a7c3262e4d36b224dd8b19 has added "<<<<<<< HEAD", "=======" and ">>>>>>> svn/master" lines to lots of files.

**Comment by KrzysztofJozefowicz** [comment]
Thanks, I will look into it. Possibly src for 0.7.1 made a mess.

**Comment by KrzysztofJozefowicz** [comment]
I readded whole svn commit history to src once again, there should be no conflicts nor corrupted files. 
We need to improve svn to git sync to not get the same problems in the future as merging/rebasing commits from 0.7.1 to 0.7.0 made conflicts.
