### ISSUE TITLE
Debugger not working if :FOR in main suite __init__ file.

### ISSUE THREAD

**Issue by Mario-P** [nokia/RED#48]
I think it is related to issue https://github.com/nokia/RED/issues/29. 

When for loop is initiated in main suite __init__ file then the Robot Event Dispatcher Error is shown saying: Missing suite file for execution. This is only when running in debug mode.

![error](https://cloud.githubusercontent.com/assets/22638505/19392404/f07fda64-9230-11e6-8af6-16a208c03592.PNG)
![init_file](https://cloud.githubusercontent.com/assets/22638505/19392403/f071d022-9230-11e6-81cf-7e9407228fcd.PNG)
![project_structure](https://cloud.githubusercontent.com/assets/22638505/19392406/f08ec6b4-9230-11e6-8f2c-e2e14b4462e7.PNG)
![resource_file](https://cloud.githubusercontent.com/assets/22638505/19392405/f08cb450-9230-11e6-9193-6704af1da505.PNG)

**Comment by adam-wypych** [comment]
Can You check the issue with RED 0.7.2 release? It should works.

**Comment by Mario-P** [comment]
Now it works. Thanks.
