### ISSUE TITLE
Running sinlge test not possible if eclipse project named different than main test directory.

### ISSUE THREAD

**Issue by Mario-P** [nokia/RED#49]
Robot tests are in d:\red_tests. My eclipse project is named robot_tests. Eclipse structure:
![location](https://cloud.githubusercontent.com/assets/22638505/19393220/18d73e64-9234-11e6-8269-7c2a5547b45b.PNG)
![structure](https://cloud.githubusercontent.com/assets/22638505/19393222/1b326cec-9234-11e6-97e0-9306b791f4b4.PNG)

Running whole RED_tests_no_folder suite works without any issues. But when trying to run only Test1 there is an error:
![error](https://cloud.githubusercontent.com/assets/22638505/19393308/71e27bae-9234-11e6-9c1b-5d6ebd8a9f84.PNG)

Seems that you put wrong name for test option in run command. Suite argument is created correctly (from project location?): -s Red_tests.RED_tests_no_folder, but test is wrong (from project name?): -t Robot_Tests.RED_tests_no_folder.Test1

**Comment by adam-wypych** [comment]
Can You check the issue with RED 0.7.2 release? It should works.

**Comment by Mario-P** [comment]
Now it works. Thanks.
