### ISSUE TITLE
Error raised while converting datetime.datetime() to string

### ISSUE THREAD

**Issue by seantien** [nokia/RED#51]
When converting a datetime.datetime( ) to string, RED raises Error which says 

> [Error] Variables sending error: datetime.datetime(2013, 6, 11, 9, 0, 0, 300000) is not JSON serializable

However, this issue only occurs on RED, and could not be reproduced on both pure CMD and RIDE.

[Python]2.7.12
[Eclipse]Neon.1a Release (4.6.1)
[RED]0.7.0

**Comment by seantien** [comment]
The keyword in RF is 
Convert DateStr
    [Arguments]    ${dbDateStr}
    ${dbDateStr}    Convert Date    ${dbDateStr}    result_format=%d/%m/%Y %H:%M:%S.%f
    ${dbDateStr}    Get SubString    ${dbDateStr}    \    -3
    ${dbDateStr}=    Convert To String    ${dbDateStr}
    Return From Keyword    ${dbDateStr}

**Comment by KrzysztofJozefowicz** [comment]
Hi
With RED Product v 0.7.1, RF 3.0, Pyth 2,7 & 3.6 following passes in RED run and debug.
Can you check with latest RED and provide us RF&Python version? 

```python
*** Settings ***
Library    String
Library    DateTime
*** Variables ***
${dbDateStr}  2016/10/12 12:30:01.04
*** Keywords ***
Convert DateStr	
    [Arguments]  ${dbDateStr}
	${dbDateStr}  Convert Date   ${dbDateStr} result_format=%d/%m/%Y %H:%M:%S.%f
	${dbDateStr}=  Get Substring  ${dbDateStr}  -3
	${dbDateStr}=  Convert To String  ${dbDateStr}
	Return From Keyword  ${dbDateStr}

*** Test Cases ***
t1
    Convert DateStr  ${dbDateStr}
```

**Comment by seantien** [comment]
Hi,
Thanks a million for your reply.
The issue has gone after update RED to latest version.
