### ISSUE TITLE
Missing support for "generic" pybot configuration

### ISSUE THREAD

**Issue by ajadach** [nokia/RED#55]
Eclipse for Testers
Version: Neon.1a Release (4.6.1)
Build id: 20161007-1200
RED Robot Editor 0.7.2

User can't create "default" configuration for pybot like was in RIDE and run different suite/test case (example: --variablefile example_variable.py), at this moment for each folder/suite user need to create new pybot configuration.

**Comment by adam-wypych** [comment]
Thanks for report.

Could You confirm that You are refering to `Run` menu like in below screen:
![defaultride](https://cloud.githubusercontent.com/assets/12131969/19673962/cdccb3a0-9a84-11e6-9d9e-07bc2ae3d2b3.png)

?

**Comment by ajadach** [comment]
Exactly I thought about it. This solution from RIDE was very user friendly, that would be great to have similar solution in RED plugin.

**Comment by KrzysztofJozefowicz** [comment]
What kind of custom "things" would you like to set and where? Using RED Run Configuration example there are 2 fields : Additional interpreter arguments and Additional RobotFramework arguments. 
![image 1](https://cloud.githubusercontent.com/assets/3999733/19724778/72308e28-9b82-11e6-9352-96fe669e7f25.png)
 We are thinking to allow user to set those fields as default in Preferences for any new created run configurations (from Run,Debug ) which would not affect existing ones.

**Comment by mkswdev** [comment]
Hi, will you implement default preferences for run configurations?

**Comment by michalanglart** [comment]
Hi,

this is a question @KrzysztofJozefowicz has to answer, but last time we talked about it, we had no objections about this feature, so I think the question is when will we provide it.

**Comment by mkswdev** [comment]
Thank you for your answer. If it is a lot of work to do it completely with user interface, it would be enough just to configure it manually in project/workspace configuration file directly.

**Comment by KrzysztofJozefowicz** [comment]
released in 0.7.5
