### ISSUE TITLE
Unknow keyword when calling keyword and having '.'

### ISSUE THREAD

**Issue by korrawit** [nokia/RED#56]
Hello,

RED unable to calling keyword when having '.' in statement.

If remove '.', it's fine.

Keyword
![image](https://cloud.githubusercontent.com/assets/459124/19673685/3bcf5c32-9aac-11e6-8be9-ecd3d1a7a1aa.png)

When calling keyword
![image](https://cloud.githubusercontent.com/assets/459124/19673657/11d541c6-9aac-11e6-82d6-dbdf1ff8846f.png)

Thanks,

**Comment by korrawit** [comment]
:+1:

**Comment by adam-wypych** [comment]
the correction should be available in next release.
