### ISSUE TITLE
Environment Variable - Variable 'PATH' is used, but not defined

### ISSUE THREAD

**Issue by xyngfei** [nokia/RED#57]
How do I configure the robot file, so that it will not throw any exception?

*** Test Cases ***

Open the application 
    Log    %{PATH}

**Comment by adam-wypych** [comment]
What do You mean by any exception? Is application crash or You get just marker about error in Your file?

**Comment by xyngfei** [comment]
Basically, RED plug-in is working fine. It just throws the syntax exception.

**Comment by adam-wypych** [comment]
Thanks for report, I checked it and from my observation we should not validate if environment variable is present since it is mostly connected to environment on which test will be executed.

**Comment by xyngfei** [comment]
Appreciate your speedy response. Hope to hear good news from you again.
