### ISSUE TITLE
Debug Step Into for keyword from resource file with dot in name

### ISSUE THREAD

**Issue by adam-wypych** [nokia/RED#59]
I created resource file with name `res.data.robot` with example content like below:
```robotframework
*** Keywords ***
example
  Log  job_done
```
And I create test case which use keyword from above resource file. Test Suite file has content like below:
```robotframework
*** Settings ***
Resource  res.data.robot

*** Test Cases ***
test_example
  res.data.example
```
After setting breakpoint in line with call of keyword `res.data.example` in test case I tried in debug _Step Into_ option, but nothing happen.

**Comment by adam-wypych** [comment]
the correction should be available in next release.

**Comment by danielvanmil** [comment]
I have a project here with a breakpoint. The RF stops at the breakpoint, but when I step into the keyword RED does not show the file of the keyword that is stepped in, although the debug view shows the correct statements that are executed when stepping further into the keyword. So it seems all goes well, but only the view of the current file is not correctly updated. I cannot find the cause of the issue by creating a simple project with the same structure etc.

Any hints on how to debug the resolving of the files etc. or is debugging with the RED source code the only option. Any logging about the resolving?

Thanks in advance.

**Comment by KrzysztofJozefowicz** [comment]
Hi
to be clear, the keyword which you would like to enter is an Robot defined Keyword,not an keyword imported from Python library?
Can you provide more specific details (keyword name, where it is used in testcase,project structure etc.) so we could investigate it further?

**Comment by danielvanmil** [comment]
yes, the keyword is a Robot defined keyword. I'm trying to define the exact use case to reproduce the issue, but I cannot reproduce it yet with a clean example project with the same structure as mentioned. The project it appears is too big and complicated to hand over to you. 

Maybe attaching a debugger (to Eclipse) and quickly debug the code of this issue to find the cause and reproduce the issue? Does this look like the best plan for now maybe?

**Comment by KrzysztofJozefowicz** [comment]
I will get to your about how to reproduce the case on small project, also we have observed that there are problems when keyword is called in Suite Setup ,Teardown and __init__. Does your project files are located inside workspace on disk or linked inside Project/Workspace?
