### ISSUE TITLE
Debugging is stuck and doesn't reach breakpoint if list variable has element with None value

### ISSUE THREAD

**Issue by alhimic37** [nokia/RED#60]

**Comment by adam-wypych** [comment]
Could You share example script?

**Comment by adam-wypych** [comment]
I have created test suite like below:
```robotframework
*** Settings ***
Library	MyLib.py
*** Test Cases ***
T1
	${value} =	Get None
	Log	${NONE}
```

the content of `MyLib.py` python file is like below:
```python
class MyLib:
  def get_none(self):
    return None
```

And everything works as expected. I was able to go line-by-line via T1 test case (of course debug of `Get None` keyword was not possible because it come from Python library).

**Comment by alhimic37** [comment]
You're right.
Please have a look at this example:

```robotframework
*** Settings ***
Library	MyLib.py
*** Test Cases ***
T1
	${value} =	Get None
        ${list} =	Create List 	${value}
	Log	${NONE} #set this line as breakpoint
```

**Comment by adam-wypych** [comment]
Thanks for update. I confirm that this issue is the bug in `TestAgentRunner.py`

**Comment by adam-wypych** [comment]
the correction should be available in next release.
