### ISSUE TITLE
Add possibility to pause/resume a test

### ISSUE THREAD

**Issue by princeulrich2** [nokia/RED#64]
It would be nice to have a functionality to pause and resume the execution of a test

**Comment by adam-wypych** [comment]
As I understand You are refering to functionality available in RIDE?

**Comment by princeulrich2** [comment]
Yes indeed. In some situations it is handy to be able to pause the test execution ( for example to make some changes, while making a live demo to someone, etc) and resume. thanks for picking this up

**Comment by KrzysztofJozefowicz** [comment]
Alternative is to use Debug with breakpoints where test should be paused.

**Comment by princeulrich2** [comment]
That is correct. However this requires the tester to know beforehand where the test should be paused. It would be good to be able to pause a test at any time during the execution

**Comment by michalanglart** [comment]
It is possible with 0.8.0 however not very handy. New issue #141 was created to provide proper buttons somewhere in Robot perspective.

**Comment by princeulrich2** [comment]
okay, thanks for that
