### ISSUE TITLE
Cannot discover a library that contains a constructor with parameters

### ISSUE THREAD

**Issue by docian** [nokia/RED#65]
I've wrote a library with a class that contains a constructor with parameters. I cannot discover it anymore and I have no ideea.
import robot
from random import randint

class PaymentMessageUtilities():
    
    ROBOT_LIBRARY_VERSION = 1.0

    def __init__(self, merchantId, url, reference, amount = 0, currency="SEK",  email="test@test.net", phone ="+401324567", postal_code = "710000", country = "SE",  
                 event_name = "consumer.added", webhook_url="http://url.com"):
        self.set_order_id()
        self.empty_payment={
            "order":{
                "items":[],
                "amount":amount,
                "currency":currency,
                "reference":self.get_order_id()},
             "checkout":{
                 "url":url,
                 "consumer":{
                            "reference": reference,
                            "email": email,
                            "phone": phone,
                            "postalCode": postal_code,
                            "country": country
                     }
                 
                 },
                "merchantNumber": merchantId,
                "notifications": {
                    "webHooks": [
                        {
                            "eventName": event_name,
                            "url": webhook_url
                            }
                                 ]
                            }  
                    }  
        pass

**Comment by KrzysztofJozefowicz** [comment]
This can be the same case as #47, in this case RED does not support arguments in library imports yet.

**Comment by docian** [comment]
I should say that I'm using Eclipse Mars aon Windows OS and RED 0.7.3

**Comment by KrzysztofJozefowicz** [comment]
as in #47, RED does not support importing libraries with parameters. This is in the pipline although I cannot give you any specific release date.

**Comment by docian** [comment]
Weird... i've used such a library with only one parameter and it works

**Comment by adam-wypych** [comment]
I have been created test project for Your issue and I a little bit modified Your test library to be (file: `PaymentMessageUtilities.py`):

```python
class PaymentMessageUtilities():
    ROBOT_LIBRARY_VERSION = 1.0

    def __init__(self, merchantId, url, reference, amount = 0, currency="SEK",  email="test@test.net", phone ="+401324567", postal_code = "710000", country = "SE",  
                 event_name = "consumer.added", webhook_url="http://url.com"):
        self.set_order_id()
        self.empty_payment={
            "order":{
                "items":[],
                "amount":amount,
                "currency":currency,
                "reference":self.get_order_id()},
             "checkout":{
                 "url":url,
                 "consumer":{
                            "reference": reference,
                            "email": email,
                            "phone": phone,
                            "postalCode": postal_code,
                            "country": country
                     }
                 
                 },
                "merchantNumber": merchantId,
                "notifications": {
                    "webHooks": [
                        {
                            "eventName": event_name,
                            "url": webhook_url
                            }
                                 ]
                            }  
                    }  
        pass
        
    def payMoney(self, money_amount):
        return True
   
    def set_order_id(self):
      return True

    def get_order_id(self):
      return 1
```

Next I created test file like below:
```robotframework
*** Settings ***
Library    PaymentMessageUtilities.py    10    http://www.google.pl    10
*** Test Cases ***
T1
    Log    ok
```

I save the file and as I see RED autodiscovery (it base on Robot Framework _dryrun_) successfully found the library file, which is `PaymentMessageUtilities.py`, but the issue is that even library was found successfully RED currently, it does not give possibility to store also parameters need for `def __init__` library method. You can see this issue if You will try to manually generate libdocs with RF `python -m robot.libdoc ${path_to_paymentMessageUtilities.py_script} show`. You will get an error message that: `Test Library 'PaymentMessageUtilities' expected 3 to 11 arguments, got 0.`. Therefore some workaround is need by creating init method, which do not required any arguments in constructor:

```python
    def __init__(self, *args, **kwargs):
      if len(args) == 0 and len(kwargs) == 0:
        pass
      else:
        self.__init2__(self, args, kwargs)
```
The original method `__init__` was renamed to be `__init2__`. After this modification You will be able to get keywords from Your library.

**Comment by docian** [comment]
I'm not sure... Look at this:
class RestKw(object):

    def __init__(self, url=None, headers=None):      
        self.url = url  
        self.headers = headers
        pass

and the Robot file that works well:

*** Settings ***  
Library  RestKw    https://www.google.ro

How comes?

**Comment by michalanglart** [comment]
In short: this works because you can call this constructor without providing parameters. 

In current state when RED generates library specification it does not provide arguments to robot.libdoc module. In your original code constructor requires 3 arguments and cannot be called without providing any of them.

**Comment by michalanglart** [comment]
To see that create two libraries:

```python
class lib_without_arguments(object):
    def __init__(self, required = 0):
        pass
        
    def keyword(self):
        pass
```

and 

```python
class lib_with_arguments(object):
    def __init__(self, required):
        pass
        
    def keyword(self):
        pass
```

and then try to use libdoc in order to list available keywords:

```
python -m robot.libdoc lib_without_arguments.py list
```

Output:
```
Keyword
```

and then:

```
python -m robot.libdoc lib_with_arguments.py list
```

Error:

```
Test Library 'lib _with_arguments' expected 1 argument, got 0
```

**Comment by adam-wypych** [comment]
@docian Yeap it will be works also in Your `PaymentMessageUtilities` when You will set _default value_ for parameters: `merchantId`, `url` and `reference`.

**Comment by docian** [comment]
I've changed in:
    def __init__(self, merchantId = None , url = None, reference = None, amount = 0, currency="SEK",  email="test@test.net", phone ="+401324567", postal_code = "710000", country = "SE",  
                 event_name = "consumer.added", webhook_url="http://url.com"):

and I get the same result

**Comment by docian** [comment]
Sorry... now I'm getting:
Additional info: (u"Importing test library 'PaymentMessageUtils' failed: ImportError: No module named PaymentMessageUtils

**Comment by adam-wypych** [comment]
Can You change method name from `init` to be `__init__` and check again?

**Comment by docian** [comment]
I've changed in:

PaymentMessageUtils.py file
class PaymentMessageUtilities():
    
    ROBOT_LIBRARY_VERSION = 1.0

    def __init__(self, merchantId = None , url = None, reference = None, amount = 0, currency="SEK",  email="test@test.net", phone ="+401324567", postal_code = "710000", country = "SE",  
                 event_name = "consumer.added", webhook_url="http://url.com"):

in robot file
*** Settings ***
Library  PaymentMessageUtils  1  2  3   

and  I'm getting: 

Status: Not added to project configuration
Source: Unknown
Importers: C:\tst_work\ecomm-test-sit\keywords\functionalKeywords\functionalKeywords.robot
Additional info: (u"Importing test library 'PaymentMessageUtils' failed: ImportError: No module named PaymentMessageUtils

**Comment by michalanglart** [comment]
Please read: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-library-names

In your case the module name (file name) is PaymentMessageUtils and is different than the library name (class name): PaymentMessageUtilities.

In user guide:
> Python classes are always inside a module. If the name of a class implementing a library is the same as the name of the module, Robot Framework allows dropping the class name when importing the library.

which is not your case, so you cannot use import this way.

You can either rename file or class, so that they will be the same and then use it in import, or you have to use qualified import:

```
Library    PaymentMessageUtil.PaymentMessageUtilities
```

**Comment by docian** [comment]
Bottom line: it cannot see the file anymore despite the fact that i've enlisted in red.xml like you can see bellow:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<projectConfiguration>
    <configVersion>1.0</configVersion>
    <relativeTo>WORKSPACE</relativeTo>
    <referencedLibrary type="PYTHON" name="environmentLocators" path="ecomm-test-sit/pythonFiles/generalIdentifiers"/>
    <referencedLibrary type="PYTHON" name="paymentApiLocators" path="ecomm-test-sit/pythonFiles/generalIdentifiers"/>
    <referencedLibrary type="PYTHON" name="generalMethods" path="ecomm-test-sit/pythonFiles/generalMethods"/>
    <referencedLibrary type="PYTHON" name="generalMethods.generalMethods" path="ecomm-test-sit/pythonFiles/generalMethods"/>
    <referencedLibrary type="PYTHON" name="BrowserSupport" path="ecomm-test-sit/pythonFiles/paymentAPI"/>
    <referencedLibrary type="PYTHON" name="NewPayments" path="ecomm-test-sit/pythonFiles/paymentAPI"/>
    <referencedLibrary type="PYTHON" name="PaymentApiTemplates" path="ecomm-test-sit/pythonFiles/paymentAPI"/>
    <referencedLibrary type="PYTHON" name="PaymentRequest" path="ecomm-test-sit/pythonFiles/paymentAPI"/>
    <referencedLibrary type="PYTHON" name="PaymentRequest.Consumer" path="ecomm-test-sit/pythonFiles/paymentAPI"/>
    <referencedLibrary type="PYTHON" name="PaymentRequest.OrderItems" path="ecomm-test-sit/pythonFiles/paymentAPI"/>
    <referencedLibrary type="PYTHON" name="PaymentRequest.Urls" path="ecomm-test-sit/pythonFiles/paymentAPI"/>
    <referencedLibrary type="PYTHON" name="RestKw" path="ecomm-test-sit/pythonFiles/paymentAPI"/>
    <referencedLibrary type="PYTHON" name="PaymentConstants" path="ecomm-test-sit/pythonFiles/paymentAPI"/>
    <referencedLibrary type="PYTHON" name="paymentsKeywords" path="ecomm-test-sit/pythonFiles/paymentsModule"/>
    <referencedLibrary type="PYTHON" name="Test" path="ecomm-test-sit/pythonFiles/paymentAPI"/>
    <referencedLibrary type="PYTHON" name="PaymentMessageUtilities" path="ecomm-test-sit/pythonFiles/paymentAPI"/>
    <pythonpath/>
    <classpath/>
    <excludedForValidation/>
    <isValidatedFileSizeCheckingEnabled>true</isValidatedFileSizeCheckingEnabled>
    <validatedFileMaxSize>1024</validatedFileMaxSize>
    <isReferencedLibrariesAutoReloadEnabled>true</isReferencedLibrariesAutoReloadEnabled>
    <isReferencedLibrariesAutoDiscoveringEnabled>true</isReferencedLibrariesAutoDiscoveringEnabled>
    <isLibrariesAutoDiscoveringSummaryWindowEnabled>false</isLibrariesAutoDiscoveringSummaryWindowEnabled>
</projectConfiguration>

**Comment by docian** [comment]
sorry... my mistake...  the names are the same: PaymentMessageUtilities... i've changed in robot file. anyhow the question still remains for 
 *** Settings ***
Library  RestKw    https://www.google.ro

and RestKw.py is:
class RestKw(object):

    def __init__(self, url=None, headers=None):      
        self.url = url  
        self.headers = headers
        pass
 
and it works...

**Comment by michalanglart** [comment]
Ok, but what is the question actually?

In attachement I've created simple project with PaymentMessageUtilities and everything works fine for me in RED 0.7.2
[test.zip](https://github.com/nokia/RED/files/654993/test.zip)

**Comment by docian** [comment]
ok... thank you. made the corrections and now it is working

**Comment by humbienri** [comment]
Is this a Robot problem or a RED issue?

**Comment by michalanglart** [comment]
This is not a problem nor an issue: it was closed 2.5 year ago with reporter changing his library constructor in order to be able to generate library documentation without passing any parameters so that it would overcome RED limitation from #47

**Comment by humbienri** [comment]
Hello @michalanglart , thanks for the response.  I realize this is an old ticket/issue in Github.  My question was that is the underlying issue described in this Github ticket still a problem? Or a shortcoming of RED.

I realize the original poster changed his code to make it work around what couldn't be done in/with RED.  So although parameterized constructors were a problem back in 2016, it seems they are still a problem in 2019?

What I was trying to understand is if they are a problem for RED or if they are a problem for the Robot Framework as a whole?

**Comment by michalanglart** [comment]
Yes, library constructors which cannot be called without providing arguments are still not supported by RED when it comes to generating library documentation files for them. This is why #47 is remaining open. It has nothing to with Robot Framework as a whole.
