### ISSUE TITLE
Have right click Open/Run/Debug menu option also in Outline panel.

### ISSUE THREAD

**Issue by kootstra** [nokia/RED#66]
In RED 0.73 the Project explorer menu allows for a test case to be run via the right click menu.

In the Outline panel the same test cases are shown but the right click option is not present. 

The motivation for this enhancement is that the folder structure of the Project explorer isn't always fully expanded, where that is the case for the outline. For this reason it saves time not to have to click 2 times to open the test cases under project explorer and then run the test case.

**Comment by michalanglart** [comment]
Hi,

this rather straightforward and easy to implement, so I think you can expect it to be implemented with next release, although due to holiday season we're not planning 0.7.4 to happen before year end.

cheers,
Michal

**Comment by michalanglart** [comment]
Should 'Open' action be also implemented? Double click on elements in outline moves selection to corresponding item in source/table and moreover when linkage is enabled the selection in editor is synchronized with selection in outline.

**Comment by kootstra** [comment]
If with "Open" you mean a synonym to the Double Click action, then I think it would be nice. That being said, since the outline shows the already opened file perhaps the wording might be changed to "Go to"?

**Comment by michalanglart** [comment]
By "Open" I meant the menu action in navigator. Double click on suite elements in navigator actually uses the Open action. 

In outline however double click selects the element in editor, but there is no open menu action (since there is no menu at all now :) )

The question is:
1) should we also add open menu action in outline (double click will still work the same)
or
2) remove the open action from navigator elements (it actually does not make much sense to have this since double click does the same and is more natural)

**Comment by KrzysztofJozefowicz** [comment]
I would be in favor of not adding Open action to Outline and remove it from ProjectExplorer as single/double click is more natural.

**Comment by kootstra** [comment]
Considering that the project explorer is a multi file overview I think that the Open menu item is appropriate to support opening a keyword in a file that is not open in the workspace. So, no reason to remove it from the ProjectExplorer. 

As for "Open" item for the Outline, I agree that it should not be added to it, as the single click already behaves in the way I want. Debug, Run, Delete are the ones that I would expect in the Outline. Perhaps Declaration (F3) is a nice addition to that list.

What would be a nice extra is if the target panel for "Open" in the ProjectExplorer can be configured. Currently it opens to the Test Cases tab, but I personally prefer the Source Code tab. Since this may be different for everyone, I think making it configurable in the Editor preferences would be a nice addition.

**Comment by KrzysztofJozefowicz** [comment]
released in 0.7.5
