### ISSUE TITLE
Global variables are not taken into account during validation

### ISSUE THREAD

**Issue by pkomarov** [nokia/RED#7]
In keyword.txt:
Failback Performance Setup
      ...
      Set Global Variable   ${OBJECT}

In Failback_Performance.txt:
**\* Settings ***
Resource    keywords.txt
Suite Setup   Failback Performance Setup
**\* Test Cases ***
FailbackPerformance
     Delete Files    ${OBJECT}            #<- error here Variable ${OBJECT} is used, but not defined

**Comment by adam-wypych** [comment]
You are fully right that we do not propagate variables created by  ```Set Global Variable/Set Suite Variable``` to test suite, test case or keyword from where it is executed. The main reason is that Robot Framework gives possibility to perform tests in different order i.e. by declare execution by specific tags, so if you will have example like below:
```robotframework
*** Test Cases ***
TestA
              [Tags]   Prepare
              Set Suite Variable       ${z}            10
TestB
              [Tags]    Exec
             Log           ${z}
```
and only tag ```Exec``` will be take in account during test perform, You will get an information about `variable ${z} unknown`.
Therefore for better visibility we have not been decided to implement some extra but still possible to failing mechanism of variable providing - equal to create robot test execution interpreter inside RED. 

In my opinion tests are pretty the same like programming language, so you have `in\out` variables. For some special, but unlike `global` is good to have one place to check. Therefore I think You can use created variables in python file and import them to red.xml in Section `Variable files`. So in example:

`GLOBAL_VARS.py`
```python
OBJECT = None
```
should make variable `${OBJECT}` visible at whole project.
For `suite variables` is better to define them in 
```robotframework 
*** Variables  ***
``` 
section.

**Comment by pkomarov** [comment]
In a case, you described, I'm totaly agree with you. Moreover this is a bad practice, because TCs should be independent. But in a case, I've described this global variable is defined in a suite setup, which will be executed in any case. Is it possible to distinguish such a case?

**Comment by KrzysztofJozefowicz** [comment]
This is a valid argument, we will discuss this among the team. 
For now you can follow Adam advice to create sample python file variable and add it to red.xml in variable files section so it will be visible around project without changing testcases itself.

**Comment by michalanglart** [comment]
The case:

```
*** Settings ***
Suite Setup    Set Global Variable    ${X}    1
*** Test Cases ***
test
   Log    ${X}
```

is covered. We are not willing to push it further and look inside custom keywords used as a setup in order to check if they eventually call `Set Global Variable`.
