### ISSUE TITLE
Clone failed in windows

### ISSUE THREAD

**Issue by aihuasxy** [nokia/RED#72]
Can't clone in win7 because of too long filename.

**Output**
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

d:\github>git clone https://github.com/aihuasxy/RED.git
Cloning into 'RED'...
remote: Counting objects: 82471, done.
remote: Total 82471 (delta 0), reused 0 (delta 0), pack-reused 82471
Receiving objects: 100% (82471/82471), 14.64 MiB | 537.00 KiB/s, done.
Resolving deltas: 100% (42158/42158), done.
Checking connectivity... done.
error: unable to create file src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/test/resources/org/rf/ide/
core/testdata/text/write/keywords/exec/new/oneKeyword/threeExecs/KeywordExecutionActionWithThreeArgsCommentAndOneComment
edLineAndOneEmptyWithoutKeywordName.tsv (Filename too long)
error: unable to create file src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/test/resources/org/rf/ide/
core/testdata/text/write/keywords/exec/new/oneKeyword/threeExecs/KeywordExecutionActionWithThreeArgsCommentAndOneComment
edLineAndOneEmptyWithoutKeywordName.txt (Filename too long)
error: unable to create file src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/test/resources/org/rf/ide/
core/testdata/text/write/keywords/exec/new/threeKeywords/oneExecInEveryKeyword/KeywordExecutionActionWithAllCombinations
NoCommentLineWithoutOneKeywordName.tsv (Filename too long)
error: unable to create file src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/test/resources/org/rf/ide/
core/testdata/text/write/keywords/exec/new/threeKeywords/oneExecInEveryKeyword/KeywordExecutionActionWithAllCombinations
NoCommentLineWithoutOneKeywordName.txt (Filename too long)
error: unable to create file src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/test/resources/org/rf/ide/
core/testdata/text/write/testCases/exec/new/oneTestCase/threeExecs/TestExecutionActionWithThreeArgsCommentAndOneCommente
dLineAndOneEmptyWithoutTestName.tsv (Filename too long)
error: unable to create file src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/test/resources/org/rf/ide/
core/testdata/text/write/testCases/exec/new/oneTestCase/threeExecs/TestExecutionActionWithThreeArgsCommentAndOneCommente
dLineAndOneEmptyWithoutTestName.txt (Filename too long)
error: unable to create file src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/test/resources/org/rf/ide/
core/testdata/text/write/testCases/exec/new/threeTestCases/oneExecInEveryTestCase/TestExecutionActionWithAllCombinations
NoCommentLineWithoutOneTestName.tsv (Filename too long)
error: unable to create file src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/test/resources/org/rf/ide/
core/testdata/text/write/testCases/exec/new/threeTestCases/oneExecInEveryTestCase/TestExecutionActionWithAllCombinations
NoCommentLineWithoutOneTestName.txt (Filename too long)
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by adam-wypych** [comment]
Please try to use `git config --system core.longpaths true` or one of the option described in http://stackoverflow.com/questions/21123415/git-pull-aborted-with-error-filename-too-long .

**Comment by KrzysztofJozefowicz** [comment]
released in 0.7.5
