### ISSUE TITLE
when attempting repeated test runs TestRunnerAgent.py' failed: error: [Errno 32] Broken pipe is raised

### ISSUE THREAD

**Issue by mrosenhahn** [nokia/RED#75]
I have a situation where I am connection to some test equipment and the connection process can take up to 30 seconds or more to complete the connection process. This is due to the connection reserving the resources for the connection to the test equipment.

What I am trying to do is keep these sessions open between test runs and I am trying to accomplish this by looping over the test case execution. I made a custom version of the **RobotFramework.main** that I am using to manage all the connection sessions a loop the suite.run actions after building the test suite again. 

```python
    def _rf_main(self, datasources, **options):
        settings = RobotSettings(options)
           
        LOGGER.register_console_logger(**settings.console_output_config)
        LOGGER.info('Settings:\n%s' % unic(settings))
        for x in range(5):
            info(settings.log)
            info(settings.output)
            info("#######################################")
            info("############## run {0} Start #############".format(x))
            info("#######################################")
            suite = TestSuiteBuilder(settings['SuiteNames'],
                                     settings['WarnOnSkipped']).build(*datasources)
            suite.configure(**settings.suite_config)
            if settings.pre_run_modifiers:
                suite.visit(ModelModifier(settings.pre_run_modifiers,
                                          settings.run_empty_suite, LOGGER))
            with pyloggingconf.robot_handler_enabled(settings.log_level):
                result = suite.run(settings)
                LOGGER.info("Tests execution ended. Statistics:\n%s"
                            % result.suite.stat_message)
                if settings.log or settings.report or settings.xunit:
                    writer = ResultWriter(settings.output if settings.log
                                          else result)
                    writer.write_results(settings.get_rebot_settings())
            #settings = deepcopy(RobotSettings(options))
            info("#######################################")
            info("############## run {0} Stop #############".format(x))
            info("#######################################")
            YieldIfNeeded()
```

What I have observed is that in the run time mode the error the error Broken pipe is raised during one of the subsequent test iterations.

    [ ERROR ] Calling method 'report_file' of listener '/tmp/RobotTempDir7520893094995480596  /TestRunnerAgent.py' failed: error: [Errno 32] Broken pipe 

The error is generally raised after the second or third iteration of the test run. When the error would be thrown would vary, with the error sometimes being thrown as soon as the test iteration run had begun and at other times the error would be thrown after the first several commands had been sent successfully. Commands to the DUT’s were still being sent successfully which I could verify by setting up and external connection to the devices and monitor the activity to the affected devices.

The next test iterations of the test run after the error was raised no longer raise the error but the error message would persist in the subsequent logs.

When running the test in debug mode, the test execution would hang at the second test run iteration.

System:

    CentOS release: 6.8 (Final)
    Robot Framework: 3.0
    ActivePython: 2.7.8
    RED Robot Editor: 0.7.201610210837
    Eclipse Platform: 4.6.1v20160907-1200

Log File
[log.zip](https://github.com/nokia/RED/files/749151/log.zip)

Is there is a method to setup some sort of continual loop for a test so that the test can be debugged and modified at debug time while keeping the existing sessions opened? If not what can I do to prevent the **TestRunnerAgent.py** from breaking the pipe and/or causing the debug sessions to hang.

**Comment by KrzysztofJozefowicz** [comment]
Hi
from the first glance, it looks like remote host (or TestRunnerAgent.py on local machine) forcefully closes TCP connection during testrun/debug on Agent side (Connection reset by peer from log.zip).
Something is interrupting TCP connection,it is difficult to get hint why or what does it. 
You can try eavesdropping with tshark what is happening between RED and TestRunnerAgent.py or tunnel traffic from TestRunnerAgent to RED with stateless protocol (Mosh would be good idea although I have not tired it)

Remote Debug:
you can try to run simple forwarding proxy between RED and TestRunnerAgent.py to get hints why Debug session hangs.

Let's consider that you are running tests locally. 
1. in Debug Configuration,in Remote tab, set LocalIP to 127.0.0.1 , LocalPort to 50000
2. Setup proxy to accept anything from 45000 port and forward to 127.0.0.1:50000 to RED, print forwarded packet info 
3. I used http://voorloopnul.com/blog/a-python-proxy-in-less-than-100-lines-of-code/ although you need to make changes in couple of places for Python3 and change forwarding to localhost (line 15) as well as ports(lines 93,94). Proxy with changes in attachment,line 88 prints forwarded data
[proxy.zip](https://github.com/nokia/RED/files/774111/proxy.zip)

4. Start proxy
5. Start RED: Debug server is listening on 127.0.0.1:50000, you can run a remote test
6. Start TestRunnerAgent.py, my example: 
`python.exe -m robot.run --listener D:\TestRunnerAgent.py:45000:True:127.0.0.1 -s New1.Folder.1 D:\workspace_red\new1`
Changing True to False,Debug will behave like TestRun - no breakpoints will be triggered.

**Comment by mrosenhahn** [comment]
Hello, 

  Thank you for the response, I will try your debugging steps you have provided to see if I can see what is happening in T-Shark captures. I am swamped for the remainder of this week so it may not be until next week when I have some more information on the behavior I am seeing.

**Comment by KrzysztofJozefowicz** [comment]
Hi @mrosenhahn, have you tested/check hanging debug?

**Comment by mrosenhahn** [comment]
Hello @KrzysztofJozefowicz ,
  I apologize I have been very busy with other tasks at work and only now have had time to revisit looking into this behavior.

  I have the current settings for the proxy set as follows on the CentOS VM
`        server = TheServer('localhost', 45000)
        try:
            server.main_loop()
        except KeyboardInterrupt:
            print "Ctrl C - Stopping server"
            sys.exit(1)`

My debugging session for RED is set as follows:
![image](https://cloud.githubusercontent.com/assets/25513789/23809635/48f4aefc-0583-11e7-84eb-77a6e15306ab.png)

For the T-shark/Wireshark captures, I am waiting on privileged permissions to run them against on VM.

I plan on doing a baseline run where I do not attempt to re-run the test via a loop. Once I have the baseline I will then add the loop back in and run the test until I see the failure.

**Comment by mrosenhahn** [comment]
Hello @KrzysztofJozefowicz,

 I did a few experiments and it looks like one part of my problem is how the sessions in my custom robot runner are being managed. It appears that they were in a dirty state between loop iterations when I was looping through the overall test suit. By resetting these sessions before the next loop iteration, I could avoid raising the broken pipe error. 
> [ ERROR ] Calling method 'report_file' of listener '/tmp/RobotTempDir7520893094995480596  /TestRunnerAgent.py' failed: error: [Errno 32] Broken pipe 

 I still have an issue when looping while in Debug mode, the loop will stop execution after the first iteration but the debugger's run execution no longer hangs when the next loop iteration is about to start.

  Can you answer me what the difference is between the way a test is run handled in Debug mode visa Run mode in Eclipse/Red?

**Comment by michalanglart** [comment]
Hi,

debug mode is not that different than run mode. The only difference is that in debug mode RED is building some kind of context which is used to check if for example breakpoint was hit in order to pause execution. It looks like there is some place in code which somehow assume that the suites are not repeated within single tests execution.

We need to figure it out, but I can' t tell you as for now if the fix would be easy or not. 

Could you share your modified version of RobotFramework.main method after fixes you've mentioned?
