### ISSUE TITLE
Not all described ways to set breakpoints work

### ISSUE THREAD

**Issue by hpschry** [nokia/RED#78]
When trying RED 0.7.4 it seems that setting breakpoints is not in all places working as expected: 
* in source view, when clicking on line, the set breakpoint option is not always available in the context menu
* shift-ctrl-b not always available, when it is not available clicking on the line number however will still add the breakpoint

While the above options are from time to time available when trying to apply them to a test case, it seems that in resource files only clicking on the line number works.

**Comment by adam-wypych** [comment]
Breakpoint is possible to set only on `Settings`, which contains executable keywords i.e. `Suite/Test Setup`, `Suite/Test Teardown`, `Test Template`. And in settings contains executable keywords inside `Test Case` and `User Keywords`. 
You should be able for ensure to set breakpoint on executable rows, which are really steps of keyword/test case.

**Comment by modrz** [comment]
Can you provide code example with described problem?
Does it happen in Robot or Debug perspective?

**Comment by modrz** [comment]
I found that in Debug perspective:
- "Toogle Breakpoint" option from vertical ruler context menu is always unavailable 
- Ctrl+Shift+B shortcut does not work
- Only line double clicking sets a breakpoint
It seems setting breakpoints should work the same independently from selected perspective.

As @adam-wypych explained, in both perspectives breakpoint can be placed only in lines when it make sense.

**Comment by hpschry** [comment]
Where I was able to set a breakpoint it did seem to make sense, like on keyword calls.

**Comment by KrzysztofJozefowicz** [comment]
can you provide example,even screenshot will do.

**Comment by hpschry** [comment]
As requested, still setting breakpoints by double-clicking works. Let me know, if I should provide more information. 
BTW: RED is looking very promising for me, addresses many of the short-comings of other Robot Framework editors. 

![screenshot 002 screenshots](https://cloud.githubusercontent.com/assets/4648940/22853556/da4732ec-f059-11e6-9f7f-758566e00a1a.png)

**Comment by KrzysztofJozefowicz** [comment]
Hi
Still not getting your request or issue. As in this screenshot, RED will not set breakpoint on line 4 on [Arguments] line either on ctrl+shift+b, double click or right click on side bar. RED could place breakpoints on those lines but any on non-executable row would not be triggered.

This is due how to Robot works and reports through listener on which element in testcase is being executed. In essence, Robot does not go line by line in test run, it transforms testsuite into a data model,extracting lines which can be executed (executable row) and non-executable (read and interpreted either on file load or tc/kw load, this means that non-executable items are load as whole,not line by line. This also allows Robot to merge duplicated sections as [Arguments] or ***Settings *** ).

**Comment by modrz** [comment]
I think @hpschry means that setting breakpoints works differently between Robot and Debug perspectives.
In Robot perspective there are 3 possibilities to set breakpoints (double clicking on line, Ctrl+Shift+B, selecting option from ruler context menu).
In Debug perspective only one possibility works (double clicking on line).

**Comment by KrzysztofJozefowicz** [comment]
Thanks, this makes sense and indeed only double click on ruler activates breakpoint in Debug perspective. 
If this is the point of @hpschry ,he is right that it should work the same as in Robot perspective (I am also in favor of adding right click menu for Breakpoint when cursor is on executable row as now user does not get much hint from UI that setting breakpoint is even possible).
For final confirmation, @hpschry is that right what we assume?

**Comment by hpschry** [comment]
Yes, this interpretation is quite right. I was trying to set a breakpoint on a line and succeeded only with double-clicking, while the context menu did not show an entry for toggling and the keyboard shortcut didn't work either.

**Comment by KrzysztofJozefowicz** [comment]
closed and release in 0.7.7
