### ISSUE TITLE
deleting a variable in variables tab not working as expected

### ISSUE THREAD

**Issue by hpschry** [nokia/RED#79]
in 0.7.4: 

* created a variable in the variables tab:
${myvar}

* when I select the line and choose select delete, the variable name is deleted, the following remains: 
${}

This is probably not intended

**Comment by adam-wypych** [comment]
It works as expected, to delete whole variable You need to rather use `CTRL + DELETE` or use popup context menu and chose `Row->Delete row`. This behavior is to prevent unexpected remove of whole variable. Delete works in such condition as delete content of single cell.

**Comment by hpschry** [comment]
Good to know, however, a bit confusing for me at a first glance.
