### ISSUE TITLE
Input in table editor doesn't take affect

### ISSUE THREAD

**Issue by luisxiaomai** [nokia/RED#8]
Hi,

Thanks for your efforts to make this editor.

I tried it but found there are many bugs.
One obvious one is that when I input somethings in table editor of test suite,  it can't take affect.Switch  to source view, it's still empty.

My env: Eclipse Mars.1(4.5.1) + RED 0.6.1

Thanks
Luis

**Comment by adam-wypych** [comment]
Hello Luis,

Sorry, but we inform that table editor is not persistent and according to last 0.6.1 release note - section 'Known issues' - point 2 - 'Table editors edits are not persistent, changes done in Table editors will not be visible in source nor saved to file. Sync is done from Source -> Table only.'.

We are working to join this two different views, so hope soon this know issue will be one of the feature :)

If you have any other issues please feel free to provide your inputs.

Thanks in advance,
Adam

**Comment by luisxiaomai** [comment]
@adam-wypych , thanks for your quick clarification.

I have another issue need your help:
* I create a test suite which need a third party library.
* I wrote in source tab like "Library           XXXLibrary". But it still doesn't work, said unknow library.

Can you give some guide for this third party library import in test suite?

Thanks.
Luis

**Comment by adam-wypych** [comment]
@luisxiaomai For import third party library and get it know you can use **Quick Fix** (key combination on Windows and Linux: _Ctrl + 1_) in line where you importing library and marker about '**unknown library exists**'.

For more information you can check: _Help->Help Contents_ in the window which appear chapter: _RED Robot Editor User Guide > User Guide > Recognizing external libraries and variable files in RED_ or if you have RED currently run please put in your web browser link: `http://127.0.0.1:55213/help/topic/org.robotframework.ide.eclipse.main.plugin.doc.user/doc/user_guide/libs.html?cp=8_3_1`
