### ISSUE TITLE
Resource points to location outside your environment

### ISSUE THREAD

**Issue by mkswdev** [nokia/RED#82]
Hi, in version 0.7.5 I see a lot of errors which were not present in 0.7.4.
Every resource added by relative path is marked as error and text says "Path [realtivepath] points to location outside your workspace".
![image](https://cloud.githubusercontent.com/assets/25245899/22732618/11bf6004-edef-11e6-8cf2-b817b86450bd.png)

**Comment by KrzysztofJozefowicz** [comment]
is CommonData.robot somewhere inside PythonPath entry (either set on OS level or in red.xml)?

**Comment by mkswdev** [comment]
No, it is just robot resource file in parent folder, for example:
Folder
|-CommontData.robot
|-SubFolder
   |-TestSuite.robot (this test suite defines Resource ../CommonData.robot

And we have a lot of test suites defined in this way in a lot of folders and subfolders.

**Comment by KrzysztofJozefowicz** [comment]
Thank you for quick response.
which of the folders are workspace and projects ? 
folder -> workspace
subfolder -> project

**Comment by mkswdev** [comment]
Hi, 

I) May be my usage of RED is wrong, I have two independed folders one for workspace and another one for whole project structure and this project was imported into workspace. Example:
C:\RedWorkspace
C:\RedProject (contains libraries, tests, another folders etc.)

II) Those errors vanished when I restarted RED and for whole folder with tests I invoked context menu action Robot Framework => Revalidate. I tried it multiple times before I wrote this issue. I will try to find out repro steps if this issue happens again.

**Comment by KrzysztofJozefowicz** [comment]
Thank you for update, Eclipse allows to have workspace and project folders separately, in such case projects are linked to workspace (not copied as usual).  Eclipse and RED is aware of such usage although we could not find a case how such error could happened. 
If you will find how to reproduce it,we would be grateful.

**Comment by mkswdev** [comment]
I placed project into workspace folder and issue did not reappeared again.

**Comment by KrzysztofJozefowicz** [comment]
than you for report.
