### ISSUE TITLE
Add support for Intellij plugin

### ISSUE THREAD

**Issue by bkhouri** [nokia/RED#83]
According the git history,  Commit [f498955e4149e36fedaa68d1d58800f66962b8e8 ](https://github.com/nokia/RED/commit/f498955e4149e36fedaa68d1d58800f66962b8e8#diff-04c6e90faac2675aa89e2176d2eec7d8)(October 15, 2015) indicated support for IntelliJ will be coming.

Since I did not find an issue in the "Issues" list, I thought I would create this to track the changes.

I'm personally an IntelliJ user and would find it useful to have this plugin made available.

Is there an ETA on when this will be available?

**Comment by KrzysztofJozefowicz** [comment]
Hi
It was our initial plan to provide RED also as IntelliJ plugin, parts of our code is already divided to Eclipse-specific and generic to be reusable in future in non-Eclipse env. 
For now,we are limited in team size so we focus on delivering essential features to RED (major missing is testcase smart refactoring, show occurrences,show unused items). We could start intelliJ part but this would slow down current development. It's better to have at least one good robot editor than two mediocre ones ;)

**Comment by kootstra** [comment]
I concur, the community is better served by having a good IDE that is fully featured. The platform on which this is developed shouldn't matter that much for now. Besides, I think there is already a fair bit of support in the IntelliJ community, that quite a bit of the development can already be done in that IDE.
