### ISSUE TITLE
References menu in source view

### ISSUE THREAD

**Issue by AndreasRusjaev** [nokia/RED#84]
In keyword view with references menu i can find using of keyword in workspace or project.
Can You insert please this menu in sources view.
Thank You very much.

**Comment by KrzysztofJozefowicz** [comment]
Hi
Indeed this menu is missing in source view,there should not be a big deal to include it in source.

As a remark, this is a simple search function based on selected text string under cursor therefore it may provide more than expected results in certain situations such as keyword with name kw1 defined in two different files will be shown in results multiple times (2 definitions + any usage regardless of origin). 
Smart search/find occurrences and usages will be provided with implementation of #25

**Comment by KrzysztofJozefowicz** [comment]
This is search function which is accessible with CTRL+H shortcut, item under cursor will be taken into search field. 
As a workaround until References would be included into source, you can select item,press CTRL+H, press Search button. The same view as in table editor will be opened with references and occurrences.

**Comment by AndreasRusjaev** [comment]
Thank You very much.
