### ISSUE TITLE
Blank line between test cases or keywords is deleted in test / keyword view by saving.

### ISSUE THREAD

**Issue by AndreasRusjaev** [nokia/RED#85]
Dear team RED developer,

Blank line between test cases or keywords is deleted in test case view / keyword view by saving or by switch between Source View and test case view / keyword view and back if the file was not saved.

If one works with several developers in a file and commits in git, comes to conflicts, because git auto merge can not distinguish the code blocks.

RIDE at this point adds an blank line between keywords / test cases.

Can you please adjust the behavior of RED?
Thank You very much.

![source before](https://cloud.githubusercontent.com/assets/18263592/22827128/85dafc52-ef96-11e6-9770-b79c502bed23.jpg)
![test cases view](https://cloud.githubusercontent.com/assets/18263592/22827131/890cba14-ef96-11e6-9271-169d3690bdbe.jpg)
![source after](https://cloud.githubusercontent.com/assets/18263592/22827134/8e5b8f9a-ef96-11e6-82c8-85b5f4e93459.jpg)

**Comment by KrzysztofJozefowicz** [comment]
Hi Andreas
Unfortunately this is side effect of Table view and Robot (Robot does track only executable rows during execution although I don't recall specific details to this behavior), we have a plan to provide code formatter which could deal with those cases (or format code to desired format for stubborn users ;). 

Until than you can change git auto-merge to do not cause conflicts with white-lines:
http://stackoverflow.com/questions/9776527/merging-without-whitespace-conflicts

particularly 2 options are possible: 
git merge -Xignore-space-change  
git merge -Xignore-all-space
