### ISSUE TITLE
RED offline installation

### ISSUE THREAD

**Issue by xyngfei** [nokia/RED#87]
Can i download the zip version below and import into eclipse in offline mode?

https://github.com/nokia/RED/releases/download/0.7.5/RED_0.7.5.20170207135223-win32.win32.x86_64.zip

**Comment by kootstra** [comment]
There is indeed a download for off line installation but it's the feature download you need:  [RED_feature_0.7.5.201702071352.zip ](https://github.com/nokia/RED/releases/download/0.7.5/RED_feature_0.7.5.201702071352.zip)

**Comment by michalanglart** [comment]
Hi,

the file you've linked is a product for 64-bit Windows i.e. a standalone version of eclipse platform with RED preinstalled and branded with our icons/logos etc. You can download it and use it straight away, although you cannot "install it" in other eclipse installation.

You may download only the feature:
https://github.com/nokia/RED/releases/download/0.7.5/RED_feature_0.7.5.201702071352.zip

and then install it in your existing eclipse installation. Use "Help" menu, then "Install new software"; in "Work with" field click "Add" button, then "Archive" and choose the zip you've downloaded above.

Depending on your eclipse version you may need to install e4tools, which is a feature available on standard eclipse update site in newest releases like mars/neon. Your installation may already have it depending on what package it is and what was installed there later. Normally feature installation process will contact update site if e4tools is not yet installed. If your machine is totally offline, then e4tools would have to be also installed offline and as for now I have to figure it out where it can be downloaded as zip.

Hope this helps

**Comment by xyngfei** [comment]
Hey All

I can download the file from the link mention above. I will proceed to close this ticket.
