### ISSUE TITLE
Integration of pydev into Red

### ISSUE THREAD

**Issue by AndreasRusjaev** [nokia/RED#88]
Do You can integrate pydev plugin into Red packages?

linux.gtk.x86_64.zip,
macosx.cocoa.x86_64.zip,
win32.win32.x86_64.zip

Thank You very much.

**Comment by KrzysztofJozefowicz** [comment]
Hi
I don't think this is a good idea to bundle external plugin to RED.
Not everybody uses PyDev together with RED, also there might be the cases where users use certain PyDev version so this could break their workflow. 

With RED product update, PyDev can be install only once, there is also a way to install additional plugins by CLI via external script (we use it in regression tests in one of the setup stages):
`
./eclipse \
-clean -purgeHistory \
-application org.eclipse.equinox.p2.director \
-noSplash \
-repository <repo1>,<repo2>,<repo3> \
-installIUs <feature1>,<feature2>,<feature3>,...
`
