### ISSUE TITLE
How to configure Path of cromedriver

### ISSUE THREAD

**Issue by imdanielalves** [nokia/RED#89]
Hello,
  I'm using RED in Eclipse to run RobotFramework. When running the test, the following error is displayed:

> Check out google dot com                                              [ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: No browser is open
| FAIL |
WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**How should I proceed?**

**Comment by KrzysztofJozefowicz** [comment]
Hi
This is not related to RED, this is an installation setup for chromeDriver as Robot which is executed by RED needs to know where chromedriver is located.

Following instructions from chromedriver home:
_include the ChromeDriver location in your PATH environment variable_

1. under Windows (up to 7,I don't have 10 but should be similar), right click on My Computer,under Properties select Advanced System Settings. There is an Environment Variables button, inside you will find PATH variable which can be edited. Append path to executable to chromeDriver at the end of string.

2. under Linux:
execute this command to add chromedriver exec path to PATH replacing </path/to/chromeDriverExecutable> with proper path:
`export PATH=$PATH:</path/to/chromeDriverExecutable>`

**Comment by sajeerk123** [comment]
Hi 
I'm using RED in Eclipse to run RobotFramework on mac. I got the same error. Please help me how to configure chrome driver path on mac os Sierra
I got the same error.
WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Thanks

**Comment by yaoxiao1993** [comment]
Hi
I'm using RED in Eclipse to run RobotFramework on mac. I got the same error. Please help me how to configure chrome driver path on mac os Sierra
I got the same error.
WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Thanks

**Comment by joanna-may** [comment]
Hi,
you have 3 solutions. First you must download driver and unpack it:
https://sites.google.com/a/chromium.org/chromedriver/downloads

Examples are for Windows, but I think they can by easily change to any system.

1. Add path where driver was unpack to %{PATH} variable to your system
2. Add this path to %{PATH} using Robot:
```robotframework
*** Settings ***
Library    SeleniumLibrary
Library    OperatingSystem    
*** Test Cases ***
example 1
    Log  %{PATH}     
    Append To Environment Variable  PATH   c:\\selenium_drivers
    Log  %{PATH}     
    Open Browser  https://www.google.com  browser=chrome
    Close All Browsers
```
3. Add path to driver to "Create Webdriver" keyword
```robotframework
*** Settings ***
Library    SeleniumLibrary  
*** Test Cases ***
    
example 2
        Create Webdriver     Chrome     executable_path=c:\\selenium_drivers\\chromedriver.exe
        go to  https://www.google.com
        Close All Browsers 
```

**Comment by YanFenGuo** [comment]
Thanks @joanna-may , the same issue block me the whole day and finally your third way saved me!

I already downloaded the chromedriver and put it in system path, but RED still reporting can't find chromedriver. Execute from commadline out of Eclipse can launch the browser but not from RED in Eclipse.

I tried below:
Log   %{PATH}   == ===> I get "/usr/bin:/bin:/usr/sbin:/sbin"
$PATH   =====> From Mac terminal I get "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:"

My chromedriver was installd by brew and under "usr/local/bin". I think the problem is either RED or Eclipse that it is not using the system PATH, wondering how it missing part of the location.

**Comment by michalanglart** [comment]
@YanFenGuo If you're changing `PATH` environment variable in your system you need to exit eclipse/RED and launch it again so that the new value is visible. Have you tried that?

**Comment by YanFenGuo** [comment]
@michalanglart Yes, I even tried restarting my Mac several times, still don't work.

**Comment by michalanglart** [comment]
Looks like #174 

How do you modify your `PATH` variable?

**Comment by YanFenGuo** [comment]
While, I tried several ways to configure PATH:
1. Add the chromedriver folder location to ~/.bash_profile
2. Add the chromedriver folder location to /etc/paths
3. Put the chromedriver under /user/local/bin directly
4. Install chromedriver by home-brew, but I found it put a chromedriver quick path under /user/local/bin. Quite like my item 3.

All of the above options doesn't work then it comes to me execute the case from command line, then bingo, I found the root cause and this issue.

**Comment by jayeshd7** [comment]
@YanFenGuo  any update ,how you are solve the issue.
I am using mac and i am facing same issue which you faced.
Please let me know .
Thanks.

**Comment by YanFen-Guo** [comment]
@jayeshd7 The third way in joanna-may's above comment (https://github.com/nokia/RED/issues/89#issuecomment-396613202) works for me.

**Comment by d-saravanan** [comment]
I am using Mac OS Mojave. I am able to run the tests using the command line 
`robot test.robot`

However, when i try to run from RED, i am getting the below error

> WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

I am not sure how to configure RED. Even tried to add the environment variable that points to chromedriver, but still not working.

Below is the path variable command and its values

echo $PATH
/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Application Support/WebDriverManager/chrome/2.46/chromedriver_mac64:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/saravanan/Documents/DB/mongodb-osx-x86_64-4.0.6/bin

**Comment by d-saravanan** [comment]
Using the below given code also fails with the same error message

```
*** Settings ***
Library    SeleniumLibrary  
Library    OperatingSystem
*** Test Cases ***
    
example 1
    Log  %{PATH}     
    Append To Environment Variable  PATH   ~/Library/Application\ Support/ZAP/webdriver/macos/64/chromedriver
    Log  %{PATH}   
    Open Browser  https://www.google.com  browser=chrome
    Close All Browsers
example 2
    Create Webdriver     Chrome     executable_path=~/Library/Application\ Support/ZAP/webdriver/macos/64/chromedriver
    go to  https://www.google.com
    Close All Browsers
```

**Comment by joanna-may** [comment]
Hi,
we don't have MAC to check this problem but I tried do this on Centos. I was logged as root and I have chrome driver in:
`/root/Library/Application Support`
so I added this path to $PATH by:
`export PATH=$PATH:"/root/Library/Application\ Support"`
but this is not working (This "\" is not supported". I changed to
`export PATH=$PATH:"/root/Library/Application Support"`
and after running RED it was able to see driver (I have some problem with chrome and graphic env but now I don't have this error).  I run this sript:
```robotframework
*** Settings ***
Library    Selenium2Library  
Library    OperatingSystem 
*** Test Cases ***
    
example 1
    Log  %{PATH}     
    #Append To Environment Variable  PATH   ~/Library/Application\ Support
    Log  %{PATH}   
    Open Browser  https://www.google.com  browser=chrome
    Close All Browsers

```

I checked the command
```robotframework
Append To Environment Variable  PATH   ~/Library/Application\ Support
```

and after LOG $PATH
I see at the end:  
` :~/Library/Application Support'`
so Robot do not resolve this as a path but as a string. In other robot commands "~" resolving works but not in Append To Environment Variable  so here can be your problem too.
