### ISSUE TITLE
Keyword completion from external java libraries

### ISSUE THREAD

**Issue by baudren** [nokia/RED#9]
Does RED provide keyword completion from external java libraries? This was one of my major gripe with [RobotFramework-EclipseIDE](https://github.com/NitorCreations/RobotFramework-EclipseIDE) which prevented adoption of RF entirely.
Often, it is very impractical to write the keywords with RF directly, and not being able to have code completion on these keywords is a big hindrance.

In any case, good luck with the project - I feel it is one of the missing piece for a wider adoption of RF! Thanks for that

**Comment by KrzysztofJozefowicz** [comment]
Hi
We support KW assistance from external libs although there might be cases where list of KW will not be available (we discovered one flaw today with jython and external libs, next version v.0.6.2 will have this patch). Still, it is possible to get content assist for KW by manually generating libdocs and including libdoc xml file into red.xml (this is also a way to work with RED when not all of the required external libraries are installed on your pc but you are able to get list of KW into xml).
For libdoc generation have a look into official docs:
http://robot-framework.readthedocs.org/en/2.9.1/_modules/robot/libdoc.html

for jython, simplified command:
jython  -m robot.libdoc <lib_name_jar> <output_libdoc_file_xml>

**Comment by baudren** [comment]
Ok. Just to be clear: it should do it automatically, but in case it fails, one can always do the generating libdocs? Because this is a big deal in the development flow, for developers: write or update your keyword, and have it refactored inside your robot file (or at least told that this keyword does not exist anymore).

**Comment by KrzysztofJozefowicz** [comment]
Hi
From RED and RF point of view, whenever external lib is included in testcase and in red.xml, RED is executing libdoc generation in background (command as above depending of python interpreter used in project) to get list of KW&docs - if libdoc command fails, libname is in red. Also when lib is changed, you can manually force RED to regenerate KW from changed files by right clicking on lib name under Robot Referenced Libraries in Project Explorer ( in v.0.6.2 there will be mechanism to detect and regenerate KW list when files where changed configurable in red.xml). 
So when KW name is changed in external libs, error for unknown KW in robot tests will be rised on file or on whole project if validated (you can also use headless validation in CI to get the same but in automatic way as for instance post-commit action).
I hope this is clear for you.

**Comment by baudren** [comment]
Yep, thanks a lot! I will give it a spin, then, and maybe I will finally manage to convince my team to use RF, in order to keep our sanity. Cheers
