### ISSUE TITLE
Logical to physical variables map file

### ISSUE THREAD

**Issue by MarcoAPA** [nokia/RED#93]
We want to define a new dictionary variables "GUIMAP" that will be used by Robot Framework tests to map application controls to GUI Object names (such as the keypad keys).
For instance if we have a Keyword like this to press Button 6 in Calculator app:
Control Click    Calculator    ${EMPTY}    6      #Button15
We want to enter logical number 6 that corresponds to physical Button15 and Eclipse to change this automatically when you edit your Keyword. 
Would it be possible to achieve this and also to saw some additional information about this change?
Is there any configuration file that Eclipse supports to configure this?

**Comment by michalanglart** [comment]
Hi,

I don't fully understand the question: do you want the source editor to change values you're typing to other defined in some mapping? What is the exact scenario you would like to have working out of the box?

**Comment by MarcoAPA** [comment]
Yes I want the source editor or the variables tab to transform/change logical values to physical values defined in a mapping file. 
In red.xml configuration file inside a Robot project there is a global variables tab, I would like to have a tab with a mapping file for example, with the relation between logical and physical variables.
The scenario is having RED as test cases and keywords editor with this kind of features to facilitate the work for a person with a non technical profile. This person is going to work with different technologies and we don't want him/her to see the technology below the editor.

**Comment by KrzysztofJozefowicz** [comment]
Hi

As far as I understands, dynamic KW library could be used here. such python library which would generate keyword names (each keyword corresponds to keypad), return value of keyword would be GuiObject.
Mapping could be held in simple txt file.
mapping.txt file:
`key1 = GuiObject1
key2 = GuiObject2
key3 = GuiObject3
key4 = GuiObject4`

library: dynamic.py:
`class dynamic(object):

    def get_keyword_names(self):
        print('32')
        return list(self.dict.keys())

    def run_keyword(self, name, args):
        
        return(self.dict[name]) 
        
    def __init__(self):
        self.mapping='<ABSOLUTE_PATH_TO_mapping.txt>'
        self.dict=self.getDict(self.mapping)

    def getDict(self,mappingFile ):
        mydict = {}
        file = open(mappingFile, 'r')
        for i in file:
            b = i.rstrip().split(' = ')
            mydict[b[0]] = b[1]
        return (mydict)

`

This way, from RED/tester perspective, tester can use keywords like "key1" which during the test execution will return proper GuiObject.

For more info check dynamic api: 
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#dynamic-library-api

**Comment by MarcoAPA** [comment]
Thanks @KrzysztofJozefowicz . Ill work on this and see if I can achieve it using a dynamic library. Seems like a doable idea. Thanks!
