### ISSUE TITLE
Empty lines get removed when test case is edited from TestCases tab

### ISSUE THREAD

**Issue by BeastModeActivated** [nokia/RED#95]
Empty lines in file get removed automatically when test case is edited from TestCases tab of robot file.
Version: 0.7.6

**Comment by BeastModeActivated** [comment]
Images attached.
Empty lines get removed. 3 empty new lines get removed automatically on editing test case in TestCases tab.
![1 before_edit](https://cloud.githubusercontent.com/assets/10611789/24702673/77464726-1a1d-11e7-888f-157a1dfcea75.jpg)
![2 edit](https://cloud.githubusercontent.com/assets/10611789/24702675/774914f6-1a1d-11e7-8974-751ebc585920.jpg)
![3 after_edit](https://cloud.githubusercontent.com/assets/10611789/24702674/77489774-1a1d-11e7-95f9-0ac983d1f63b.jpg)

**Comment by KrzysztofJozefowicz** [comment]
That is know issue that RED does not keep empty lines table editors.
We are analyzing how to fix it.
We have an idea for automatic code formatter,this needs to wait for more important features to be provided though.
