### ISSUE TITLE
Font size not changing in TestCases and Keywords tab

### ISSUE THREAD

**Issue by BeastModeActivated** [nokia/RED#99]
Font size doesn't seem to change in TestCases and Keywords tab.
Though it changes in the Source tab.

**Comment by KrzysztofJozefowicz** [comment]
Thanks, we will have a look into it. It should be no problem to fix it (together with other styling options for eclipse themes in table editors).

**Comment by BeastModeActivated** [comment]
Thank you.
Is this expected in next release ?

**Comment by KrzysztofJozefowicz** [comment]
yes, it should be included.

**Comment by michalanglart** [comment]
With 0.7.8 it is possible to change font in preferences:

Preferences -> General -> Appearance -> Colors and Fonts and then inisde this page: Robot -> Table Editor -> Table Font

**Comment by KrzysztofJozefowicz** [comment]
released in 0.7.8
